%% 问题3：Similar10情景与因果仿射滚动调度
% 负载采用AS-Ridge，光伏由附件3预报与前三条同发布时间历史路径动态融合。
% 每次从最近30条完整记录中选择10条相似的净负荷残差路径，不再做K-means压缩。
% 普通购电量对各情景共享，储能按照当前残差作因果仿射响应。
% TIMEFIX：附件数据按原始144列使用，不做循环移位。
% 第1、36、37、72、73、108、109、144列分别对应
% 00:10、06:00、06:10、12:00、12:10、18:00、18:10和次日00:00。
% 每次向前优化24 h，只执行到下一次预报发布时间；6/12/18时基于真实SOC重新求解。
% 相对0时计划的增购、减购违约和紧急购电分别按电价的1.5、0.5和5倍计费。

clear;
clc;
close all;
rng(20260912,'twister');
fprintf(' 问题3 Similar10 + 因果仿射追索\n');
fprintf(' TIMEFIX + 24h滚动优化\n');

%% 文件与参数

rootDir = fileparts(mfilename('fullpath'));
dataDir = fullfile(rootDir, 'data');
baseDir = fullfile(rootDir, '支撑材料');
actualFile = fullfile(dataDir, '附件2.xlsx');
predictionFile = fullfile(baseDir, 'Q2_16combo_4models_predictions.mat');
forecastFile = fullfile(dataDir, '附件3.xlsx');
priceFile = fullfile(dataDir, '附件1.xlsx');
loadForecastCache = fullfile(baseDir, 'Q3_causal_load_ASRidge_tau08_TIMEFIX_cache.mat');
resultMatFile = fullfile(baseDir, 'Q3_Similar10_Affine_TIMEFIX_FINAL.mat');
resultExcelFile = fullfile(baseDir, 'Q3_Similar10_Affine_TIMEFIX_FINAL.xlsx');
figCostPng = fullfile(baseDir, 'Q3_Similar10_Affine_策略总成本.png');
figMonthPng = fullfile(baseDir, 'Q3_Similar10_Affine_逐月节省.png');
figSOCPng = fullfile(baseDir, 'Q3_Similar10_Affine_SOC.png');
figWeightPng = fullfile(baseDir, 'Q3_Similar10_Affine_动态权重.png');
% result3模板位置
result3File = fullfile(rootDir, 'result3.xlsx');
writeOfficialResult3 = true;
inputFiles = {
    actualFile
    predictionFile
    forecastFile
    priceFile
    };
for i = 1:length(inputFiles)
    if ~isfile(inputFiles{i})
        error( ...
            '找不到输入文件：%s', ...
            inputFiles{i});
    end
end

% 储能与时间参数

dt = 10/60;
eta = 0.90;
Ecapacity = 12000;
Emin = 1200;
Emax = 10800;
Einitial = 6000;
Efinal = 6000;
Pmax = 5000;
Wmax = Pmax*dt;
issueHours = [0,6,12,18];

% Similar10参数

similarWindow = 30;
similarMinHistory = 7;
similarCount = 10;

% 光伏动态融合参数

pvBlendWindow = 30;
pvBlendMinHistory = 7;

% AS-Ridge参数

tauLoad = 0.80;
loadWindowDays = 56;
asLambda = 1e-3;
asMaxIter = 50;
asTol = 1e-6;

% 优化参数
% P2使用极小吞吐惩罚作为tie-break
% 不是储能真实费用。

cyclePenalty = 1e-5;
curtailPenalty = 1e-5;
forceFinalSOC = false;
useTerminalValue = true;
usePVBlend = true;

% true：
% 跑5种策略，时间较长
% false：
% 只跑正式主方案

runAblation = true;
rebuildLoadForecast = false;

% 是否写入官方result3.xlsx

writeOfficialResult3 = true;

%% 数据读取与时间轴

fprintf('读取附件2...\n');
loadRaw = readmatrix(actualFile, 'Sheet','小区负载', 'Range','B2:EO366');
pvRaw = readmatrix(actualFile, 'Sheet','光伏发电实际功率', 'Range','B2:EO366');
if ~isequal(size(loadRaw),[365,144]) ...
        || ~isequal(size(pvRaw),[365,144])
    error( ...
        '附件2负载、光伏必须为365×144。');
end
if any(~isfinite(loadRaw),'all') ...
        || any(~isfinite(pvRaw),'all')
    error( ...
        '附件2存在NaN或非法值。');
end
loadAll = loadRaw;
pvAll = pvRaw;
dateAll = ( datetime(2025,1,1): days(1): datetime(2025,12,31))';
targetDays = 32:365;
predDates = dateAll(targetDays);
nDay = length(targetDays);
nTime = 144;
fprintf('\nTIMEFIX：附件原始144列直接使用。\n\n');

% 分时电价

fprintf('读取附件1电价...\n');
Tprice = readtable(priceFile, 'VariableNamingRule','preserve');
price = Tprice{:,2};
price = price(:);
if length(price)~=144
    error( ...
        '附件1电价必须为144点。');
end
if any(~isfinite(price)) ...
        || any(price<0)
    error( ...
        '附件1存在非法电价。');
end
if useTerminalValue
    terminalValue = eta*mean(price);
else
    terminalValue = 0;
end

%% 负载与光伏预测

fprintf('读取附件3...\n');
F = readForecastSingleSheet(forecastFile, 'Sheet1');
if ~all( ...
        ismember( ...
        issueHours, ...
        unique(F.issueHour)'))
    error( ...
        '附件3没有完整0/6/12/18时预报。');
end

% 生成严格因果的AS-Ridge负载预测

cacheOK = false;
if isfile(loadForecastCache) ...
        && ~rebuildLoadForecast
    C = load(loadForecastCache);
    cacheOK = ...
        isfield(C,'loadForecastToday') ...
        && isfield(C,'loadForecastNext') ...
        && isfield(C,'timeAxisVersion') ...
        && strcmp( ...
        C.timeAxisVersion, ...
        'ORIGINAL_0010_TO_NEXT_0000') ...
        && isequal( ...
        size(C.loadForecastToday), ...
        [365,144]) ...
        && isequal( ...
        size(C.loadForecastNext), ...
        [365,144]);
end
if cacheOK
    loadForecastToday = C.loadForecastToday;
    loadForecastNext = C.loadForecastNext;
    fprintf('读取AS-Ridge TIMEFIX缓存完成。\n');
else
    fprintf('重新生成AS-Ridge负载预测...\n');
    [loadForecastToday,loadForecastNext] = ...
        buildCausalLoadASRidge( ...
        loadAll, ...
        dateAll, ...
        tauLoad, ...
        asLambda, ...
        asMaxIter, ...
        asTol, ...
        loadWindowDays);
    timeAxisVersion = 'ORIGINAL_0010_TO_NEXT_0000';
    save( ...
        loadForecastCache, ...
        'loadForecastToday', ...
        'loadForecastNext', ...
        'tauLoad', ...
        'asLambda', ...
        'asMaxIter', ...
        'asTol', ...
        'loadWindowDays', ...
        'timeAxisVersion', ...
        '-v7.3');
end

% 读取问题2预测用于对照

S2 = load(predictionFile);
modelNamesQ2 = string(S2.modelNames(:));
loadModelID = find(strcmpi(modelNamesQ2, 'AS-Ridge'), 1);
if isempty(loadModelID)
    error( ...
        'Q2缓存找不到AS-Ridge。');
end
predLoadQ2 = S2.predLoad(:,:,loadModelID);
if ~isequal( ...
        size(predLoadQ2), ...
        [334,144])
    error( ...
        'Q2 AS-Ridge负载尺寸必须为334×144。');
end
loadForecastToday(targetDays,:) = ...
    max( ...
    predLoadQ2, ...
    0);
fprintf('第三问负载：AS-Ridge。\n');
fprintf('第三问不使用Q0.8风险校准。\n\n');

% 建立光伏融合标定库

fprintf('建立光伏动态融合标定库...\n');
PVlib = buildPVBlendCalibrationLibrary(F, pvAll, dateAll);
fprintf( ...
    '完整光伏历史路径：%d条。\n', ...
    sum(PVlib.complete));

% 计算四个发布时间的滚动融合权重

wDynamic = ones(nDay,4);
nWeightHistory = zeros(nDay,4);
for kd = 1:nDay
    d = targetDays(kd);
    for ki = 1:4
        hIssue = issueHours(ki);
        currentTime = dateAll(d) +hours(hIssue);
        if usePVBlend
            [ ...
                wDynamic(kd,ki), ...
                nWeightHistory(kd,ki) ...
                ] = ...
                getRollingPVBlendWeight( ...
                PVlib, ...
                hIssue, ...
                currentTime, ...
                pvBlendWindow, ...
                pvBlendMinHistory);
        else
            wDynamic(kd,ki) = ...
                1;
        end
    end
end
weightTable = ...
    table( ...
    predDates, ...
    wDynamic(:,1), ...
    wDynamic(:,2), ...
    wDynamic(:,3), ...
    wDynamic(:,4), ...
    nWeightHistory(:,1), ...
    nWeightHistory(:,2), ...
    nWeightHistory(:,3), ...
    nWeightHistory(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'Weight_0h', ...
    'Weight_6h', ...
    'Weight_12h', ...
    'Weight_18h', ...
    'HistoryN_0h', ...
    'HistoryN_6h', ...
    'HistoryN_12h', ...
    'HistoryN_18h'} ...
    );

%% Similar10联合残差
% 与原K-means版不同：
% 这里不仅保存残差，
% 还保存每条历史记录当时的：
% baseLoad
% basePV
% 用于之后计算“预测形态相似度”。

fprintf('建立Similar10历史预测-残差库...\n');
Rlib = ...
    buildSimilarResidualLibraryDynamic( ...
    F, ...
    loadAll, ...
    pvAll, ...
    loadForecastToday, ...
    loadForecastNext, ...
    dateAll, ...
    PVlib, ...
    pvBlendWindow, ...
    pvBlendMinHistory, ...
    usePVBlend);
fprintf( ...
    '完整历史联合记录：%d条。\n\n', ...
    sum(Rlib.complete));

%% 滚动策略与优化求解

strategyNames = [
    "仅0时预报，不调整"
    "0时+6时"
    "0时+6时+12时"
    "四次Similar10仿射滚动（主方案）"
    "三次调整，冻结0时光伏"
    ];
updateMask = logical([
    1 0 0 0
    1 1 0 0
    1 1 1 0
    1 1 1 1
    1 1 1 1
    ]);
freezePV = [
    false
    false
    false
    false
    true
    ];
if runAblation
    strategyID = 1:length(strategyNames);
else
    strategyID = 4;
end

% 线性规划求解设置

lpOptions = optimoptions('linprog', 'Algorithm','dual-simplex-highs', 'Display','none');

% 运行各更新策略

allResult = struct([]);
timerAll = tic;
for ir = 1:length(strategyID)
    sID = strategyID(ir);
    fprintf('\n');
    fprintf( ...
        '[%d/%d] %s\n', ...
        ir, ...
        length(strategyID), ...
        strategyNames(sID));
    thisResult = ...
        runOneStrategySimilar10( ...
        strategyNames(sID), ...
        updateMask(sID,:), ...
        freezePV(sID), ...
        targetDays, ...
        predDates, ...
        dateAll, ...
        loadAll, ...
        pvAll, ...
        loadForecastToday, ...
        loadForecastNext, ...
        F, ...
        Rlib, ...
        wDynamic, ...
        price, ...
        dt, ...
        eta, ...
        Emin, ...
        Emax, ...
        Einitial, ...
        Efinal, ...
        Wmax, ...
        terminalValue, ...
        cyclePenalty, ...
        curtailPenalty, ...
        forceFinalSOC, ...
        similarWindow, ...
        similarMinHistory, ...
        similarCount, ...
        lpOptions);
    if isempty(allResult)
        allResult = thisResult;
    else
        allResult(end+1,1) = ...
            thisResult;
    end
end
runtimeMin = toc(timerAll)/60;

%% 结果统计

summaryTable = table();
for i = 1:length(allResult)
    R = allResult(i);
    row = ...
        table( ...
        string(R.name), ...
        R.totalRetainedPlanCost, ...
        R.totalIncreaseCost, ...
        R.totalDecreasePenalty, ...
        R.totalEmergencyCost, ...
        R.totalCost, ...
        R.totalIncreaseEnergy, ...
        R.totalDecreaseEnergy, ...
        R.totalEmergencyEnergy, ...
        R.emergencyDays, ...
        R.emergencySlots, ...
        R.finalSOC, ...
        R.planSimultaneousSlots, ...
        R.actualSimultaneousSlots, ...
        R.maxLPConstraintViolation, ...
        'VariableNames',{ ...
        'Strategy', ...
        'RetainedPlanCost_Yuan', ...
        'IncreaseCost_Yuan', ...
        'DecreasePenalty_Yuan', ...
        'EmergencyCost_Yuan', ...
        'TotalCost_Yuan', ...
        'IncreaseEnergy_kWh', ...
        'DecreaseEnergy_kWh', ...
        'EmergencyEnergy_kWh', ...
        'EmergencyDays', ...
        'EmergencySlots', ...
        'FinalSOC_kWh', ...
        'PlanSimultaneousSlots', ...
        'ActualSimultaneousSlots', ...
        'MaxLPViolation'} ...
        );
    summaryTable = [summaryTable;row];
end
if runAblation
    baseCost = summaryTable.TotalCost_Yuan(1);
    summaryTable.SavingVsNoUpdate_Yuan = ...
        baseCost ...
        -summaryTable.TotalCost_Yuan;
else
    summaryTable.SavingVsNoUpdate_Yuan = ...
        NaN(height(summaryTable),1);
end
disp(summaryTable);

% 主方案结果

mainRow = find(arrayfun(@(x) string(x.name)==strategyNames(4), allResult), 1);
if isempty(mainRow)
    mainRow = 1;
end
Main = allResult(mainRow);
costIdentityError = ...
    abs( ...
    Main.totalCost ...
    -( ...
    Main.totalRetainedPlanCost ...
    +Main.totalIncreaseCost ...
    +Main.totalDecreasePenalty ...
    +Main.totalEmergencyCost));
fprintf('\n');
fprintf(' 第三问 Similar10 + 因果仿射主方案\n');
fprintf( ...
    '保留0时计划购电费：%.2f 元\n', ...
    Main.totalRetainedPlanCost);
fprintf( ...
    '上调购电费用：%.2f 元\n', ...
    Main.totalIncreaseCost);
fprintf( ...
    '下调计划损失：%.2f 元\n', ...
    Main.totalDecreasePenalty);
fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    Main.totalEmergencyCost);
fprintf('\n');
fprintf( ...
    '全年总成本：%.2f 元\n', ...
    Main.totalCost);
fprintf( ...
    '全年紧急购电量：%.2f kWh\n', ...
    Main.totalEmergencyEnergy);
fprintf( ...
    '紧急购电天数：%d\n', ...
    Main.emergencyDays);
fprintf( ...
    '紧急购电时段：%d\n', ...
    Main.emergencySlots);
fprintf('\n');
fprintf( ...
    '计划基础轨迹同时充放电时段：%d\n', ...
    Main.planSimultaneousSlots);
fprintf( ...
    '实际同时充放电时段：%d\n', ...
    Main.actualSimultaneousSlots);
fprintf('\n');
fprintf( ...
    '年末SOC：%.6f kWh\n', ...
    Main.finalSOC);
fprintf( ...
    '最大LP约束违反量：%.3e\n', ...
    Main.maxLPConstraintViolation);
fprintf( ...
    '成本核对误差：%.3e 元\n', ...
    costIdentityError);

% Similar10诊断

similarTable = ...
    table( ...
    predDates, ...
    Main.similarCount(:,1), ...
    Main.similarCount(:,2), ...
    Main.similarCount(:,3), ...
    Main.similarCount(:,4), ...
    Main.similarMeanDistance(:,1), ...
    Main.similarMeanDistance(:,2), ...
    Main.similarMeanDistance(:,3), ...
    Main.similarMeanDistance(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'SimilarN_0h', ...
    'SimilarN_6h', ...
    'SimilarN_12h', ...
    'SimilarN_18h', ...
    'MeanDistance_0h', ...
    'MeanDistance_6h', ...
    'MeanDistance_12h', ...
    'MeanDistance_18h'} ...
    );

% 分月统计

monthList = (2:12)';
monthlyTable = table(monthList, 'VariableNames',{'Month'});
monthlyTable.MainCost_Yuan = ...
    zeros(11,1);
monthlyTable.NoUpdateCost_Yuan = ...
    nan(11,1);
for im = 1:11
    hit = month(predDates)==monthList(im);
    monthlyTable.MainCost_Yuan(im) = ...
        sum(Main.dailyCost(hit));
    if runAblation
        monthlyTable.NoUpdateCost_Yuan(im) = ...
            sum(allResult(1).dailyCost(hit));
    end
end
monthlyTable.Saving_Yuan = ...
    monthlyTable.NoUpdateCost_Yuan ...
    -monthlyTable.MainCost_Yuan;

%% 保存结果

if isfile(resultExcelFile)
    delete(resultExcelFile);
end
writetable( ...
    summaryTable, ...
    resultExcelFile, ...
    'Sheet','策略对照');
writetable( ...
    monthlyTable, ...
    resultExcelFile, ...
    'Sheet','逐月结果');
writetable( ...
    Main.dailyTable, ...
    resultExcelFile, ...
    'Sheet','主方案每日结果');
writetable( ...
    Main.adjustmentTable, ...
    resultExcelFile, ...
    'Sheet','主方案调整明细');
writetable( ...
    weightTable, ...
    resultExcelFile, ...
    'Sheet','动态融合权重');
writetable( ...
    similarTable, ...
    resultExcelFile, ...
    'Sheet','Similar10诊断');

% 写入官方结果表

if writeOfficialResult3
    fprintf('\n开始写入官方 result3.xlsx...\n');
    result3File = fullfile(rootDir, 'result3.xlsx');
    if ~isfile(result3File)
        error( ...
            '找不到官方result3：%s', ...
            result3File);
    end
    backupFile = ...
        fullfile( ...
        rootDir, ...
        [ ...
        'result3_backup_SIM10_', ...
        char(datetime( ...
        'now', ...
        'Format','yyyyMMdd_HHmmss')), ...
        '.xlsx' ...
        ]);
    copyfile( ...
        result3File, ...
        backupFile);

    % 19.1 0时计划购电量

    planOut = Main.plan0;
    planEnergyDay = sum(planOut,2);
    planCostDay = sum(planOut .*price', 2);
    writematrix( ...
        planOut, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','B2');
    writematrix( ...
        planEnergyDay, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','EP2');
    writematrix( ...
        planCostDay, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','EQ2');

    % 19.2 调整后普通购电

    adjustedOut = Main.executedPlan;
    adjustedEnergyDay = sum(adjustedOut,2);
    adjustedCostDay = ...
        Main.dailyTable.RetainedPlanCost_Yuan ...
        +Main.dailyTable.IncreaseCost_Yuan ...
        +Main.dailyTable.DecreasePenalty_Yuan;
    writematrix( ...
        adjustedOut, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','B2');
    writematrix( ...
        adjustedEnergyDay, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','EP2');
    writematrix( ...
        adjustedCostDay, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','EQ2');

    % 19.3 充放电量

    timeBlockName = {
        '0:00-4:00'
        '4:00-8:00'
        '8:00-12:00'
        '12:00-16:00'
        '16:00-20:00'
        '20:00-24:00'
        };
    nBlock = 6;
    charge4h = zeros(nDay,nBlock);
    discharge4h = zeros(nDay,nBlock);
    for kd = 1:nDay
        for b = 1:nBlock
            s1 = (b-1)*24+1;
            s2 = b*24;
            charge4h(kd,b) = ...
                sum( ...
                Main.actualCharge(kd,s1:s2));
            discharge4h(kd,b) = ...
                sum( ...
                Main.actualDischarge(kd,s1:s2));
        end
    end
    nCDRow = nDay*nBlock;
    cdOut = cell(nCDRow,6);
    rr = 1;
    for kd = 1:nDay
        for b = 1:nBlock
            if b==1
                cdOut{rr,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');
            else
                cdOut{rr,1} = ...
                    '';
            end
            cdOut{rr,2} = ...
                timeBlockName{b};
            cdOut{rr,3} = ...
                charge4h(kd,b);
            cdOut{rr,4} = ...
                discharge4h(kd,b);
            if b==1
                cdOut{rr,5} = ...
                    '0:00';
                cdOut{rr,6} = ...
                    Main.SOCstart(kd);
            elseif b==2
                cdOut{rr,5} = ...
                    '24:00';
                cdOut{rr,6} = ...
                    Main.SOCend(kd);
            else
                cdOut{rr,5} = ...
                    '';
                cdOut{rr,6} = ...
                    [];
            end
            rr = rr+1;
        end
    end
    writecell( ...
        cdOut, ...
        result3File, ...
        'Sheet','充放电量', ...
        'Range','A2');

    % 19.4 紧急购电

    % 先清理历史残留
    blankRows = cell(5000,3);
    writecell( ...
        blankRows, ...
        result3File, ...
        'Sheet','紧急购电量', ...
        'Range','A2');
    emergencyRows = cell(0,3);
    outRow = 0;
    for kd = 1:nDay
        x = Main.actualEmergency(kd,:);
        active = x>1e-8;
        if ~any(active)
            continue;
        end
        edge = diff([false,active,false]);
        starts = find(edge==1);
        ends = find(edge==-1)-1;
        for kk = 1:length(starts)
            s = starts(kk);
            e = ends(kk);
            outRow = outRow+1;
            if kk==1
                emergencyRows{outRow,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');
            else
                emergencyRows{outRow,1} = ...
                    '';
            end
            emergencyRows{outRow,2} = ...
                makeEmergencyTimeRange(s,e);
            emergencyRows{outRow,3} = ...
                sum(x(s:e));
        end
    end
    if ~isempty(emergencyRows)
        writecell( ...
            emergencyRows, ...
            result3File, ...
            'Sheet','紧急购电量', ...
            'Range','A2');
    end
    fprintf('\n');
    fprintf(' 官方result3写入完成\n');
    fprintf( ...
        '0时计划购电量：%.2f kWh\n', ...
        sum(Main.plan0,'all'));
    fprintf( ...
        '最终普通购电量：%.2f kWh\n', ...
        sum(Main.executedPlan,'all'));
    fprintf( ...
        '实际充电量：%.2f kWh\n', ...
        sum(Main.actualCharge,'all'));
    fprintf( ...
        '实际放电量：%.2f kWh\n', ...
        sum(Main.actualDischarge,'all'));
    fprintf( ...
        '紧急购电量：%.2f kWh\n', ...
        sum(Main.actualEmergency,'all'));
    fprintf( ...
        '调整普通购电费用：%.2f 元\n', ...
        sum(adjustedCostDay));
    fprintf( ...
        '紧急购电费用：%.2f 元\n', ...
        Main.totalEmergencyCost);
    fprintf( ...
        '最终总费用：%.2f 元\n', ...
        Main.totalCost);
end
%% 写入官方result3.xlsx

if writeOfficialResult3

    if ~isfile(result3File)
        error('找不到result3模板：%s', result3File);
    end

    % 先备份原模板
    result3Dir = fileparts(result3File);
    backupFile = fullfile(result3Dir, ...
        ['result3_backup_', char(datetime('now', ...
        'Format','yyyyMMdd_HHmmss')), '.xlsx']);
    copyfile(result3File, backupFile);

    %% 1. 计划购电量
    % Main.plan0是每天0时制定的原始计划
    planOut = Main.plan0;
    planEnergyDay = sum(planOut, 2);
    planCostDay = sum(planOut .* price', 2);

    writematrix(planOut, result3File, ...
        'Sheet','计划购电量', 'Range','B2');

    writematrix(planEnergyDay, result3File, ...
        'Sheet','计划购电量', 'Range','EP2');

    writematrix(planCostDay, result3File, ...
        'Sheet','计划购电量', 'Range','EQ2');

    %% 2. 调整购电量
    % 写调整后的普通购电计划本身，不是与0时计划的差值
    adjustedOut = Main.executedPlan;
    adjustedEnergyDay = sum(adjustedOut, 2);

    adjustedCostDay = ...
        Main.dailyTable.RetainedPlanCost_Yuan ...
        + Main.dailyTable.IncreaseCost_Yuan ...
        + Main.dailyTable.DecreasePenalty_Yuan;

    writematrix(adjustedOut, result3File, ...
        'Sheet','调整购电量', 'Range','B2');

    writematrix(adjustedEnergyDay, result3File, ...
        'Sheet','调整购电量', 'Range','EP2');

    writematrix(adjustedCostDay, result3File, ...
        'Sheet','调整购电量', 'Range','EQ2');

    %% 3. 充放电量
    % 每天按6个4小时区间统计
    blockName = {
        '0:00-4:00'
        '4:00-8:00'
        '8:00-12:00'
        '12:00-16:00'
        '16:00-20:00'
        '20:00-24:00'
        };

    charge4h = zeros(nDay, 6);
    discharge4h = zeros(nDay, 6);

    for d = 1:nDay
        for b = 1:6
            firstSlot = (b-1)*24 + 1;
            lastSlot = b*24;

            charge4h(d,b) = sum( ...
                Main.actualCharge(d,firstSlot:lastSlot));

            discharge4h(d,b) = sum( ...
                Main.actualDischarge(d,firstSlot:lastSlot));
        end
    end

    cdOut = cell(nDay*6, 6);
    row = 1;

    for d = 1:nDay
        for b = 1:6

            if b == 1
                cdOut{row,1} = datestr(predDates(d),'yyyy-mm-dd');
            else
                cdOut{row,1} = '';
            end

            cdOut{row,2} = blockName{b};
            cdOut{row,3} = charge4h(d,b);
            cdOut{row,4} = discharge4h(d,b);

            if b == 1
                cdOut{row,5} = '0:00';
                cdOut{row,6} = Main.SOCstart(d);
            elseif b == 2
                cdOut{row,5} = '24:00';
                cdOut{row,6} = Main.SOCend(d);
            else
                cdOut{row,5} = '';
                cdOut{row,6} = [];
            end

            row = row + 1;
        end
    end

    writecell(cdOut, result3File, ...
        'Sheet','充放电量', 'Range','A2');

    %% 4. 紧急购电量
    % 先清除上一次运行可能留下的记录
    writecell(cell(5000,3), result3File, ...
        'Sheet','紧急购电量', 'Range','A2');

    emergencyOut = cell(0,3);
    row = 0;

    for d = 1:nDay

        emergency = Main.actualEmergency(d,:);
        active = emergency > 1e-8;

        if ~any(active)
            continue;
        end

        edge = diff([false, active, false]);
        startSlot = find(edge == 1);
        endSlot = find(edge == -1) - 1;

        for k = 1:length(startSlot)

            row = row + 1;

            if k == 1
                emergencyOut{row,1} = ...
                    datestr(predDates(d),'yyyy-mm-dd');
            else
                emergencyOut{row,1} = '';
            end

            emergencyOut{row,2} = ...
                makeEmergencyTimeRange(startSlot(k),endSlot(k));

            emergencyOut{row,3} = ...
                sum(emergency(startSlot(k):endSlot(k)));
        end
    end

    if ~isempty(emergencyOut)
        writecell(emergencyOut, result3File, ...
            'Sheet','紧急购电量', 'Range','A2');
    end

    fprintf('\nresult3.xlsx写入完成。\n');
    fprintf('计划购电量：%.2f kWh\n', sum(Main.plan0,'all'));
    fprintf('调整后购电量：%.2f kWh\n', ...
        sum(Main.executedPlan,'all'));
    fprintf('实际充电量：%.2f kWh\n', ...
        sum(Main.actualCharge,'all'));
    fprintf('实际放电量：%.2f kWh\n', ...
        sum(Main.actualDischarge,'all'));
    fprintf('紧急购电量：%.2f kWh\n', ...
        sum(Main.actualEmergency,'all'));
    fprintf('全年总成本：%.2f 元\n', Main.totalCost);

end
% 保存MAT结果

save( ...
    resultMatFile, ...
    'allResult', ...
    'summaryTable', ...
    'monthlyTable', ...
    'weightTable', ...
    'similarTable', ...
    'wDynamic', ...
    'Main', ...
    'PVlib', ...
    'Rlib', ...
    'strategyNames', ...
    'predDates', ...
    'similarWindow', ...
    'similarCount', ...
    'similarMinHistory', ...
    'runtimeMin', ...
    '-v7.3');

%% 结果图

fig1 = figure('Color','w', 'Position',[100,100,1200,700]);
bar( ...
    summaryTable.TotalCost_Yuan/1e4, ...
    0.65);
set( ...
    gca, ...
    'XTick',1:height(summaryTable), ...
    'XTickLabel',summaryTable.Strategy, ...
    'TickLabelInterpreter','none', ...
    'FontName','Microsoft YaHei', ...
    'FontSize',11);
ylabel('全年总费用 / 万元');
title( ...
    'Similar10因果仿射滚动方案总费用');
grid on;
exportgraphics( ...
    fig1, ...
    figCostPng, ...
    'Resolution',300);

% 月度节省

if runAblation
    fig2 = figure('Color','w', 'Position',[100,100,1200,650]);
    bar( ...
        monthlyTable.Month, ...
        monthlyTable.Saving_Yuan/1e4, ...
        0.65);
    yline(0,'k-');
    xlabel('月份');
    ylabel('相对0时不调整方案节省 / 万元');
    title( ...
        'Similar10滚动调整逐月节省');
    grid on;
    exportgraphics( ...
        fig2, ...
        figMonthPng, ...
        'Resolution',300);
end

% SOC轨迹

fig3 = figure('Color','w', 'Position',[100,100,1300,650]);
plot( ...
    predDates, ...
    Main.SOCend, ...
    'LineWidth',1.1);
hold on;
yline(Emin,'--','SOC下限');
yline(Emax,'--','SOC上限');
yline(Efinal,':','6000 kWh参考线');
xlabel('日期');
ylabel('日末SOC / kWh');
title( ...
    'Similar10因果仿射方案日末SOC');
grid on;
exportgraphics( ...
    fig3, ...
    figSOCPng, ...
    'Resolution',300);

% 动态融合权重

fig4 = figure('Color','w', 'Position',[100,100,1300,700]);
plot(predDates,wDynamic(:,1),'LineWidth',1);
hold on;
plot(predDates,wDynamic(:,2),'LineWidth',1);
plot(predDates,wDynamic(:,3),'LineWidth',1);
plot(predDates,wDynamic(:,4),'LineWidth',1);
ylim([0,1]);
xlabel('日期');
ylabel('附件3正式预报权重');
title( ...
    '0/6/12/18时光伏动态融合权重');
legend( ...
    '0时', ...
    '6时', ...
    '12时', ...
    '18时', ...
    'Location','best');
grid on;
exportgraphics( ...
    fig4, ...
    figWeightPng, ...
    'Resolution',300);
fprintf('\n');
fprintf(' 第三问 Similar10 + Affine 完成\n');
fprintf( ...
    'Excel：%s\n', ...
    resultExcelFile);
fprintf( ...
    'MAT：%s\n', ...
    resultMatFile);
fprintf( ...
    '总运行时间：%.2f min\n', ...
    runtimeMin);

% 运行一个策略

%% 局部函数
function R = runOneStrategySimilar10( ...
    strategyName, ...
    updateMask, ...
    freezePV, ...
    targetDays, ...
    predDates, ...
    dateAll, ...
    loadAll, ...
    pvAll, ...
    loadForecastToday, ...
    loadForecastNext, ...
    F, ...
    Rlib, ...
    wDynamic, ...
    price, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Einitial, ...
    Efinal, ...
    Wmax, ...
    terminalValue, ...
    cyclePenalty, ...
    curtailPenalty, ...
    forceFinalSOC6000, ...
    similarWindow, ...
    similarMinHistory, ...
    similarCountMax, ...
    lpOptions)
nDay = length(targetDays);
nTime = 144;
issueHours = [0,6,12,18];
plan0 = zeros(nDay,nTime);
executedPlan = zeros(nDay,nTime);
planAfter = nan(nDay,nTime,4);

% 当前日基础储能轨迹

baseChargePlan = zeros(nDay,nTime);
baseDischargePlan = zeros(nDay,nTime);
actualCharge = zeros(nDay,nTime);
actualDischarge = zeros(nDay,nTime);
actualEmergency = zeros(nDay,nTime);
actualSurplus = zeros(nDay,nTime);
SOCstart = zeros(nDay,1);
SOCend = zeros(nDay,1);
retainedPlanCostDay = zeros(nDay,1);
increaseCostDay = zeros(nDay,1);
decreasePenaltyDay = zeros(nDay,1);
emergencyCostDay = zeros(nDay,1);
increaseEnergyDay = zeros(nDay,1);
decreaseEnergyDay = zeros(nDay,1);
similarCount = nan(nDay,4);
similarMeanDistance = nan(nDay,4);
adjustmentTable = table();
maxLPViolation = 0;
Ecurrent = Einitial;
for kd = 1:nDay
    d = targetDays(kd);
    thisDate = dateAll(d);
    isLastDay = d==365;
    forceFinalToday = isLastDay && forceFinalSOC6000;
    terminalValueToday = terminalValue;
    if isLastDay ...
            && ~forceFinalSOC6000
        terminalValueToday = 0;
    end
    SOCstart(kd) = ...
        Ecurrent;
    if mod(kd-1,20)==0 ...
            || isLastDay
        fprintf( ...
            '  [%03d/%03d] %s SOC %.2f\n', ...
            kd, ...
            nDay, ...
            string(thisDate), ...
            Ecurrent);
    end

    % 冻结光伏消融

    w0 = wDynamic(kd,1);
    frozenPV48 = buildFrozenPV48(F, pvAll, dateAll, d, w0);
    currentPlan = zeros(nTime,1);
    currentChBase = zeros(nTime,1);
    currentDisBase = zeros(nTime,1);
    g0 = zeros(nTime,1);
    for ki = 1:4
        hIssue = issueHours(ki);
        startSlot = hIssue*6+1;
        endSlot = min(startSlot+35, nTime);
        qCurrent = nTime-startSlot+1;
        shouldOptimize = ki==1 || updateMask(ki);
        if shouldOptimize

            % 当前24h负载预测

            baseLoad24 = makeLoadForecast24(loadForecastToday, loadForecastNext, d, hIssue);

            % 当前24h光伏预测

            if freezePV ...
                    && ki>1
                basePV24 = frozenPV48(startSlot: startSlot+143);
            else
                wNow = wDynamic(kd,ki);
                basePV24 = makeOfficialPV24Blend(F, pvAll, dateAll, d, hIssue, wNow);
            end

            % Similar10

            currentTime = thisDate +hours(hIssue);
            S = ...
                getSimilarResidualScenarios( ...
                Rlib, ...
                hIssue, ...
                currentTime, ...
                baseLoad24, ...
                basePV24, ...
                similarWindow, ...
                similarMinHistory, ...
                similarCountMax);
            similarCount(kd,ki) = ...
                S.nSelected;
            similarMeanDistance(kd,ki) = ...
                S.meanDistance;

            % 基础净负荷

            forecastNet24 = baseLoad24(:) -basePV24(:);

            % 24h电价

            price24 = [ price(startSlot:end); price(1:(startSlot-1)) ];

            % 0时计划基准

            if ki==1
                g0Remain = [];
            else
                g0Remain = g0(startSlot:end);
            end

            % Similar10 因果仿射LP

            P = ...
                solveRolling24hCausalAffineLP( ...
                forecastNet24, ...
                S.netResidual, ...
                S.prob, ...
                price24, ...
                qCurrent, ...
                g0Remain, ...
                Ecurrent, ...
                forceFinalToday, ...
                Efinal, ...
                dt, ...
                eta, ...
                Emin, ...
                Emax, ...
                Wmax, ...
                terminalValueToday, ...
                cyclePenalty, ...
                curtailPenalty, ...
                lpOptions);
            maxLPViolation = max(maxLPViolation, P.maxConstraintViolation);

            % 0时

            if ki==1
                g0 = P.currentGrid;
                currentPlan = g0;
                currentChBase = P.currentChargeBase;
                currentDisBase = P.currentDischargeBase;
                plan0(kd,:) = ...
                    g0';

            % 6/12/18时调整

            else
                oldPlan = currentPlan(startSlot:end);
                currentPlan(startSlot:end) = ...
                    P.currentGrid;
                currentChBase(startSlot:end) = ...
                    P.currentChargeBase;
                currentDisBase(startSlot:end) = ...
                    P.currentDischargeBase;
                oneInc = sum(max(P.currentGrid -g0(startSlot:end), 0));
                oneDec = sum(max(g0(startSlot:end) -P.currentGrid, 0));
                logRow = ...
                    table( ...
                    string(strategyName), ...
                    thisDate, ...
                    hIssue, ...
                    wDynamic(kd,ki), ...
                    S.nSelected, ...
                    S.meanDistance, ...
                    sum( ...
                    abs( ...
                    P.currentGrid-oldPlan) ...
                    >1e-6), ...
                    oneInc, ...
                    oneDec, ...
                    P.objective, ...
                    P.maxConstraintViolation, ...
                    'VariableNames',{ ...
                    'Strategy', ...
                    'Date', ...
                    'IssueHour', ...
                    'PVBlendWeight', ...
                    'SimilarCount', ...
                    'SimilarMeanDistance', ...
                    'ChangedSlots', ...
                    'IncreaseVs0_kWh', ...
                    'DecreaseVs0_kWh', ...
                    'RollingObjective', ...
                    'MaxConstraintViolation'} ...
                    );
                adjustmentTable = [adjustmentTable;logRow];
            end
        end
        planAfter(kd,:,ki) = ...
            currentPlan';

        % 当前6h实际执行

        blockSlots = startSlot:endSlot;
        A = ...
            replayActualBlockWithBase( ...
            loadAll(d,blockSlots)', ...
            pvAll(d,blockSlots)', ...
            currentPlan(blockSlots), ...
            currentChBase(blockSlots), ...
            currentDisBase(blockSlots), ...
            Ecurrent, ...
            blockSlots, ...
            forceFinalToday, ...
            Efinal, ...
            dt, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax);
        executedPlan(kd,blockSlots) = ...
            currentPlan(blockSlots)';
        baseChargePlan(kd,blockSlots) = ...
            currentChBase(blockSlots)';
        baseDischargePlan(kd,blockSlots) = ...
            currentDisBase(blockSlots)';
        actualCharge(kd,blockSlots) = ...
            A.Wch';
        actualDischarge(kd,blockSlots) = ...
            A.Wdis';
        actualEmergency(kd,blockSlots) = ...
            A.Wem';
        actualSurplus(kd,blockSlots) = ...
            A.Wsur';
        Ecurrent = A.Eend;
    end
    SOCend(kd) = ...
        Ecurrent;

    % 当日结算

    inc = max(executedPlan(kd,:)' -g0, 0);
    dec = max(g0 -executedPlan(kd,:)', 0);
    retainedPlanCostDay(kd) = ...
        sum( ...
        price ...
        .*min( ...
        g0, ...
        executedPlan(kd,:)'));
    increaseCostDay(kd) = ...
        1.5 ...
        *sum( ...
        price ...
        .*inc);
    decreasePenaltyDay(kd) = ...
        0.5 ...
        *sum( ...
        price ...
        .*dec);
    emergencyCostDay(kd) = ...
        5 ...
        *sum( ...
        price ...
        .*actualEmergency(kd,:)');
    increaseEnergyDay(kd) = ...
        sum(inc);
    decreaseEnergyDay(kd) = ...
        sum(dec);
end

% 检验

if forceFinalSOC6000 ...
        && abs(SOCend(end)-Efinal)>1e-5
    error( ...
        '%s最终SOC未回6000。', ...
        strategyName);
end
if any(SOCend<Emin-1e-5) ...
        || any(SOCend>Emax+1e-5)
    error( ...
        '%s日末SOC越界。', ...
        strategyName);
end
dailyCost = retainedPlanCostDay +increaseCostDay +decreasePenaltyDay +emergencyCostDay;
dailyTable = ...
    table( ...
    predDates, ...
    SOCstart, ...
    SOCend, ...
    retainedPlanCostDay, ...
    increaseCostDay, ...
    decreasePenaltyDay, ...
    emergencyCostDay, ...
    dailyCost, ...
    increaseEnergyDay, ...
    decreaseEnergyDay, ...
    sum(actualEmergency,2), ...
    'VariableNames',{ ...
    'Date', ...
    'SOCstart_kWh', ...
    'SOCend_kWh', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh'} ...
    );
R.name = ...
    strategyName;
R.plan0 = ...
    plan0;
R.executedPlan = ...
    executedPlan;
R.planAfter = ...
    planAfter;
R.baseChargePlan = ...
    baseChargePlan;
R.baseDischargePlan = ...
    baseDischargePlan;
R.actualCharge = ...
    actualCharge;
R.actualDischarge = ...
    actualDischarge;
R.actualEmergency = ...
    actualEmergency;
R.actualSurplus = ...
    actualSurplus;
R.SOCstart = ...
    SOCstart;
R.SOCend = ...
    SOCend;
R.dailyCost = ...
    dailyCost;
R.dailyTable = ...
    dailyTable;
R.adjustmentTable = ...
    adjustmentTable;
R.similarCount = ...
    similarCount;
R.similarMeanDistance = ...
    similarMeanDistance;
R.totalRetainedPlanCost = ...
    sum(retainedPlanCostDay);
R.totalIncreaseCost = ...
    sum(increaseCostDay);
R.totalDecreasePenalty = ...
    sum(decreasePenaltyDay);
R.totalEmergencyCost = ...
    sum(emergencyCostDay);
R.totalCost = ...
    sum(dailyCost);
R.totalIncreaseEnergy = ...
    sum(increaseEnergyDay);
R.totalDecreaseEnergy = ...
    sum(decreaseEnergyDay);
R.totalEmergencyEnergy = ...
    sum(actualEmergency,'all');
R.emergencyDays = ...
    sum( ...
    any( ...
    actualEmergency>1e-8, ...
    2));
R.emergencySlots = ...
    nnz(actualEmergency>1e-8);
R.finalSOC = ...
    SOCend(end);
R.planSimultaneousSlots = ...
    nnz( ...
    baseChargePlan>1e-8 ...
    &baseDischargePlan>1e-8);
R.actualSimultaneousSlots = ...
    nnz( ...
    actualCharge>1e-8 ...
    &actualDischarge>1e-8);
R.maxLPConstraintViolation = ...
    maxLPViolation;
end

% Similar10 因果仿射滚动24h LP

function P = solveRolling24hCausalAffineLP( ...
    forecastNet, ...
    residualScenarios, ...
    prob, ...
    price24, ...
    qCurrent, ...
    g0Remain, ...
    Estart, ...
    forceFinalToday, ...
    Efinal, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    terminalValue, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)
forecastNet = forecastNet(:);
price24 = price24(:);
H = length(forecastNet);
if H~=144
    error( ...
        '滚动窗口必须为144点。');
end
[K,H2] = ...
    size(residualScenarios);
if H2~=H
    error( ...
        '残差情景尺寸错误。');
end
prob = prob(:);
prob = prob/sum(prob);

% 转换为每10min电量

Wbase = forecastNet *dt;
R = residualScenarios *dt;
Rp = max(R,0);
Rn = max(-R,0);

% 变量
% G        未来24h共同普通购电
% 如果6/12/18时：
% INC DEC  当前日至午夜部分相对0时计划的调整量
% C0 D0    零残差基础储能轨迹
% ACP ACN ADP ADN
%          因果仿射响应系数
% Ebase    基础SOC
% SpBase   基础富余
% 对每个相似情景：
% E
% Em
% Sp

idxG = 1:H;
base = H;
isInitial = isempty(g0Remain);
if isInitial
    idxInc = [];
    idxDec = [];
else
    idxInc = base+(1:qCurrent);
    base = base+qCurrent;
    idxDec = base+(1:qCurrent);
    base = base+qCurrent;
    g0Remain = g0Remain(:);
end
idxC0 = base+(1:H);
base = base+H;
idxD0 = base+(1:H);
base = base+H;
idxACP = base+(1:H);
base = base+H;
idxACN = base+(1:H);
base = base+H;
idxADP = base+(1:H);
base = base+H;
idxADN = base+(1:H);
base = base+H;
idxEbase = base+(1:H+1);
base = base+H+1;
idxSpBase = base+(1:H);
base = base+H;
idxE = reshape(base+(1:K*(H+1)), H+1,K)';
base = base+K*(H+1);
idxEm = reshape(base+(1:K*H), H,K)';
base = base+K*H;
idxSp = reshape(base+(1:K*H), H,K)';
nVar = base+K*H;

% 目标函数

f = zeros(nVar,1);

% 整个24h普通购电
% 当前日剩余部分会实际执行，
% 午夜后的部分仅用于避免短视。

f(idxG) = ...
    price24;

% 6/12/18调整费用
% G = g0 + inc - dec
% p*G + 0.5p*inc + 0.5p*dec
% 等价题目：
% 增购1.5倍
% 减购支付0.5倍违约费

if ~isInitial
    f(idxInc) = ...
        0.5 ...
        *price24(1:qCurrent);
    f(idxDec) = ...
        0.5 ...
        *price24(1:qCurrent);
end

% 期望紧急购电成本

for s = 1:K
    f(idxEm(s,:)) = ...
        prob(s) ...
        *5 ...
        *price24;
    f(idxSp(s,:)) = ...
        prob(s) ...
        *curtailPenalty;
    f(idxE(s,end)) = ...
        f(idxE(s,end)) ...
        -prob(s) ...
        *terminalValue;
end

% P2思想：
% 对期望充放电吞吐加极小tie-break

mRp = (prob' * Rp)';
mRn = (prob' * Rn)';
f(idxC0) = ...
    cyclePenalty;
f(idxD0) = ...
    cyclePenalty;
f(idxACP) = ...
    -cyclePenalty ...
    *mRp;
f(idxACN) = ...
    cyclePenalty ...
    *mRn;
f(idxADP) = ...
    cyclePenalty ...
    *mRp;
f(idxADN) = ...
    -cyclePenalty ...
    *mRn;

% 等式约束

nAdjustEq = double(~isInitial) *qCurrent;
nBaseEq = 2*H+1;
nScenarioEq = K*(2*H+1);
nEq = nAdjustEq +nBaseEq +nScenarioEq;
Aeq = spalloc(nEq, nVar, max(1, 20*nEq));
beq = zeros(nEq,1);
row = 0;

% 相对0时计划的调整关系

if ~isInitial
    for t = 1:qCurrent
        row = row+1;
        Aeq(row,idxG(t)) = ...
            1;
        Aeq(row,idxInc(t)) = ...
            -1;
        Aeq(row,idxDec(t)) = ...
            1;
        beq(row) = ...
            g0Remain(t);
    end
end

% 零残差基础路径

for t = 1:H
    row = row+1;
    Aeq(row,idxG(t)) = ...
        1;
    Aeq(row,idxD0(t)) = ...
        1;
    Aeq(row,idxC0(t)) = ...
        -1;
    Aeq(row,idxSpBase(t)) = ...
        -1;
    beq(row) = ...
        Wbase(t);
end
for t = 1:H
    row = row+1;
    Aeq(row,idxEbase(t)) = ...
        -1;
    Aeq(row,idxEbase(t+1)) = ...
        1;
    Aeq(row,idxC0(t)) = ...
        -eta;
    Aeq(row,idxD0(t)) = ...
        1/eta;
end
row = row+1;
Aeq(row,idxEbase(1)) = ...
    1;
beq(row) = ...
    Estart;

% Similar10情景

for s = 1:K

    % 供需平衡

    for t = 1:H
        row = row+1;
        Aeq(row,idxG(t)) = ...
            1;
        Aeq(row,idxC0(t)) = ...
            -1;
        Aeq(row,idxD0(t)) = ...
            1;

% C = C0 - ACP Rp + ACN Rn
% D = D0 + ADP Rp - ADN Rn

        Aeq(row,idxACP(t)) = ...
            Rp(s,t);
        Aeq(row,idxACN(t)) = ...
            -Rn(s,t);
        Aeq(row,idxADP(t)) = ...
            Rp(s,t);
        Aeq(row,idxADN(t)) = ...
            -Rn(s,t);
        Aeq(row,idxEm(s,t)) = ...
            1;
        Aeq(row,idxSp(s,t)) = ...
            -1;
        beq(row) = ...
            Wbase(t) ...
            +R(s,t);
    end

    % SOC

    for t = 1:H
        row = row+1;
        Aeq(row,idxE(s,t)) = ...
            -1;
        Aeq(row,idxE(s,t+1)) = ...
            1;
        Aeq(row,idxC0(t)) = ...
            -eta;
        Aeq(row,idxD0(t)) = ...
            1/eta;
        Aeq(row,idxACP(t)) = ...
            eta ...
            *Rp(s,t);
        Aeq(row,idxACN(t)) = ...
            -eta ...
            *Rn(s,t);
        Aeq(row,idxADP(t)) = ...
            Rp(s,t)/eta;
        Aeq(row,idxADN(t)) = ...
            -Rn(s,t)/eta;
    end

% 初始SOC

    row = row+1;
    Aeq(row,idxE(s,1)) = ...
        1;
    beq(row) = ...
        Estart;
end
if row~=nEq
    error( ...
        '内部等式约束行数错误。');
end

% 不等式：
% 每个情景的仿射充放电必须在[0,Wmax]

nIneq = 4*K*H;
A = spalloc(nIneq, nVar, 12*K*H);
b = zeros(nIneq,1);
row = 0;
for s = 1:K
    for t = 1:H

        % C <= Wmax
        % C0 - ACP Rp + ACN Rn <= Wmax

        row = row+1;
        A(row,idxC0(t)) = ...
            1;
        A(row,idxACP(t)) = ...
            -Rp(s,t);
        A(row,idxACN(t)) = ...
            Rn(s,t);
        b(row) = ...
            Wmax;

        % C >= 0

        row = row+1;
        A(row,idxC0(t)) = ...
            -1;
        A(row,idxACP(t)) = ...
            Rp(s,t);
        A(row,idxACN(t)) = ...
            -Rn(s,t);
        b(row) = ...
            0;

        % D <= Wmax

        row = row+1;
        A(row,idxD0(t)) = ...
            1;
        A(row,idxADP(t)) = ...
            Rp(s,t);
        A(row,idxADN(t)) = ...
            -Rn(s,t);
        b(row) = ...
            Wmax;

        % D >= 0

        row = row+1;
        A(row,idxD0(t)) = ...
            -1;
        A(row,idxADP(t)) = ...
            -Rp(s,t);
        A(row,idxADN(t)) = ...
            Rn(s,t);
        b(row) = ...
            0;
    end
end

% 上下界

lb = zeros(nVar,1);
ub = inf(nVar,1);

% 基础充放电

ub(idxC0) = ...
    Wmax;
ub(idxD0) = ...
    Wmax;

% 仿射响应系数0~1

ub(idxACP) = ...
    1;
ub(idxACN) = ...
    1;
ub(idxADP) = ...
    1;
ub(idxADN) = ...
    1;

% 基础SOC

lb(idxEbase) = ...
    Emin;
ub(idxEbase) = ...
    Emax;

% 情景SOC

lb(idxE(:)) = ...
    Emin;
ub(idxE(:)) = ...
    Emax;

% 减购不能超过原计划

if ~isInitial
    ub(idxDec) = ...
        g0Remain;
end

% 如果最后一天强制午夜回6000

if forceFinalToday
    midnightState = qCurrent+1;
    lb(idxEbase(midnightState)) = ...
        Efinal;
    ub(idxEbase(midnightState)) = ...
        Efinal;
    for s = 1:K
        lb(idxE(s,midnightState)) = ...
            Efinal;
        ub(idxE(s,midnightState)) = ...
            Efinal;
    end
end

% 求解

[x,fval,exitflag,output] = ...
    linprog( ...
    f, ...
    A, ...
    b, ...
    Aeq, ...
    beq, ...
    lb, ...
    ub, ...
    options);
if exitflag<=0
    error( ...
        'Similar10因果仿射LP失败：%s', ...
        output.message);
end

% 约束误差

eqViolation = max(abs(Aeq*x-beq));
if isempty(A)
    ineqViolation = 0;
else
    ineqViolation = max([ A*x-b; 0 ]);
end
boundViolation = max([ lb-x; x-ub; 0 ]);
maxViolation = max([ eqViolation, ineqViolation, boundViolation ]);

% 返回当前日至午夜部分

P.currentGrid = ...
    x(idxG(1:qCurrent));
P.currentChargeBase = ...
    x(idxC0(1:qCurrent));
P.currentDischargeBase = ...
    x(idxD0(1:qCurrent));
P.fullGrid = ...
    x(idxG);
P.fullChargeBase = ...
    x(idxC0);
P.fullDischargeBase = ...
    x(idxD0);
P.objective = ...
    fval;
P.exitflag = ...
    exitflag;
P.maxConstraintViolation = ...
    maxViolation;
end

% 实际因果回放
% 保留P2思想：
% 先采用零残差基础充放电轨迹，
% 然后根据当前实际偏差即时修正。
% 不使用未来实际数据。

function A = replayActualBlockWithBase( ...
    Pload, ...
    Ppv, ...
    Wgrid, ...
    WchPlan, ...
    WdisPlan, ...
    Estart, ...
    globalSlots, ...
    forceFinalToday, ...
    Efinal, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax)
Wload = Pload(:)*dt;
Wpv = Ppv(:)*dt;
Wgrid = Wgrid(:);
WchPlan = WchPlan(:);
WdisPlan = WdisPlan(:);
N = length(Wgrid);
Wch = zeros(N,1);
Wdis = zeros(N,1);
Wem = zeros(N,1);
Wsur = zeros(N,1);
E = zeros(N+1,1);
E(1) = ...
    Estart;
for j = 1:N
    ec = E(j);
    tGlobal = globalSlots(j);

    % 下一时刻SOC允许区间

    if forceFinalToday
        remainingSlots = 144-tGlobal;
        nextLow = max(Emin, Efinal -remainingSlots *eta *Wmax);
        nextHigh = min(Emax, Efinal +remainingSlots *Wmax/eta);
    else
        nextLow = Emin;
        nextHigh = Emax;
    end

    % 基础储能计划

    c = min(max(WchPlan(j),0), Wmax);
    d = min(max(WdisPlan(j),0), Wmax);
    en = ec +eta*c -d/eta;

    % 基础动作若造成SOC过低：
    % 先减少放电，再增加充电

    if en<nextLow
        reduceDis = min(d, (nextLow-en)*eta);
        d = d-reduceDis;
        en = ec +eta*c -d/eta;
        if en<nextLow-1e-10
            addCh = min(Wmax-c, (nextLow-en)/eta);
            c = c+addCh;
            en = ec +eta*c -d/eta;
        end
    end

    % 基础动作SOC过高：
    % 先减少充电，再增加放电

    if en>nextHigh
        reduceCh = min(c, (en-nextHigh)/eta);
        c = c-reduceCh;
        en = ec +eta*c -d/eta;
        if en>nextHigh+1e-10
            addDis = min(Wmax-d, (en-nextHigh)*eta);
            d = d+addDis;
            en = ec +eta*c -d/eta;
        end
    end

    % 当前真实供需偏差
    % 正：缺电
    % 负：富余

    residual = Wload(j) -Wpv(j) -Wgrid(j) -(d-c);

    % 缺电

    if residual>1e-12

% 先减少充电

        maxReduceChargeSOC = max((en-nextLow)/eta, 0);
        reduceCharge = min([ residual, c, maxReduceChargeSOC ]);
        c = c-reduceCharge;
        residual = residual-reduceCharge;
        en = en -eta*reduceCharge;

% 再增加放电

        if residual>1e-12
            maxExtraDisSOC = eta *max(en-nextLow, 0);
            extraDis = min([ residual, Wmax-d, maxExtraDisSOC ]);
            d = d+extraDis;
            residual = residual-extraDis;
            en = en -extraDis/eta;
        end
        Wem(j) = ...
            max( ...
            residual, ...
            0);

    % 富余

    elseif residual<-1e-12
        surplus = -residual;

% 先减少放电

        maxReduceDisSOC = eta *max(nextHigh-en, 0);
        reduceDis = min([ surplus, d, maxReduceDisSOC ]);
        d = d-reduceDis;
        surplus = surplus-reduceDis;
        en = en +reduceDis/eta;

% 再增加充电

        if surplus>1e-12
            maxExtraChargeSOC = max(nextHigh-en, 0) /eta;
            extraCharge = min([ surplus, Wmax-c, maxExtraChargeSOC ]);
            c = c+extraCharge;
            surplus = surplus-extraCharge;
            en = en +eta*extraCharge;
        end
        Wsur(j) = ...
            max( ...
            surplus, ...
            0);
    end
    Enew = ec +eta*c -d/eta;
    if Enew<nextLow-1e-6 ...
            || Enew>nextHigh+1e-6
        error( ...
            ['实际回放SOC越界：', ...
             'slot=%d, E=%.8f'], ...
            tGlobal, ...
            Enew);
    end
    Wch(j) = ...
        c;
    Wdis(j) = ...
        d;
    E(j+1) = ...
        Enew;
end
A.Wch = ...
    Wch;
A.Wdis = ...
    Wdis;
A.Wem = ...
    Wem;
A.Wsur = ...
    Wsur;
A.E = ...
    E;
A.Eend = ...
    E(end);
end

% 光伏动态融合历史库

function L = buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll)
nRec = length(F.dates);
formal = nan(nRec,144);
history = nan(nRec,144);
actual = nan(nRec,144);
complete = false(nRec,1);
for i = 1:nRec
    d = find(dateAll==F.dates(i), 1);
    if isempty(d) ...
            || d<=3
        continue;
    end
    hIssue = F.issueHour(i);
    actual24 = extractActual24(pvAll, d, hIssue);
    if isempty(actual24)
        continue;
    end
    formal24 = makeFormalPV24(F, pvAll, dateAll, d, hIssue);
    history24 = makeHistoryPV24(pvAll, d, hIssue);
    formal(i,:) = ...
        formal24';
    history(i,:) = ...
        history24';
    actual(i,:) = ...
        actual24';
    complete(i) = ...
        all(isfinite(formal(i,:))) ...
        && all(isfinite(history(i,:))) ...
        && all(isfinite(actual(i,:)));
end
L.date = ...
    F.dates;
L.issueHour = ...
    F.issueHour;
L.issueTime = ...
    F.issueTime;
L.formal = ...
    formal;
L.history = ...
    history;
L.actual = ...
    actual;
L.complete = ...
    complete;
end

% 动态融合权重

function [w,nHistory] = getRollingPVBlendWeight( ...
    L, ...
    issueHour, ...
    currentTime, ...
    windowN, ...
    minHistory)
valid = L.complete &L.issueHour==issueHour &( L.issueTime+hours(24) <=currentTime);
rows = find(valid);
if isempty(rows)
    w = 1;
    nHistory = 0;
    return;
end
[~,ord] = ...
    sort(L.issueTime(rows));
rows = rows(ord);
firstKeep = max(1, length(rows)-windowN+1);
rows = rows(firstKeep:end);
nHistory = length(rows);
if nHistory<minHistory
    w = 1;
    return;
end
formal = L.formal(rows,:);
history = L.history(rows,:);
actual = L.actual(rows,:);
formal = formal(:);
history = history(:);
actual = actual(:);
good = isfinite(formal) &isfinite(history) &isfinite(actual);
formal = formal(good);
history = history(good);
actual = actual(good);
den = sum((formal-history).^2);
if isempty(actual) ...
        || den<1e-12
    w = 1;
    return;
end
w = sum((actual-history) .*(formal-history)) /den;
w = min(max(w,0), 1);
end

% Similar10历史库
% 保存：
% 当时基础负载预测
% 当时基础光伏预测
% 真实负载
% 真实光伏
% 负载残差
% 光伏残差
% 净负荷残差

function Rlib = buildSimilarResidualLibraryDynamic( ...
    F, ...
    loadAll, ...
    pvAll, ...
    loadPredToday, ...
    loadPredNext, ...
    dateAll, ...
    PVlib, ...
    blendWindow, ...
    blendMinHistory, ...
    useBlend)
nRec = length(F.dates);
baseLoad = nan(nRec,144);
basePV = nan(nRec,144);
eLoad = nan(nRec,144);
ePV = nan(nRec,144);
eNet = nan(nRec,144);
blendWeight = nan(nRec,1);
complete = false(nRec,1);
for i = 1:nRec
    d = find(dateAll==F.dates(i), 1);
    if isempty(d) ...
            || d<16
        continue;
    end
    if any( ...
            ~isfinite( ...
            loadPredToday(d,:))) ...
            || any( ...
            ~isfinite( ...
            loadPredNext(d,:)))
        continue;
    end
    hIssue = F.issueHour(i);
    actualLoad24 = extractActual24(loadAll, d, hIssue);
    actualPV24 = extractActual24(pvAll, d, hIssue);
    if isempty(actualLoad24) ...
            || isempty(actualPV24)
        continue;
    end
    oneBaseLoad = makeLoadForecast24(loadPredToday, loadPredNext, d, hIssue);
    if useBlend
        [wHist,~] = ...
            getRollingPVBlendWeight( ...
            PVlib, ...
            hIssue, ...
            F.issueTime(i), ...
            blendWindow, ...
            blendMinHistory);
    else
        wHist = 1;
    end
    oneBasePV = makeOfficialPV24Blend(F, pvAll, dateAll, d, hIssue, wHist);
    baseLoad(i,:) = ...
        oneBaseLoad';
    basePV(i,:) = ...
        oneBasePV';
    eLoad(i,:) = ...
        ( ...
        actualLoad24 ...
        -oneBaseLoad ...
        )';
    ePV(i,:) = ...
        ( ...
        actualPV24 ...
        -oneBasePV ...
        )';
    eNet(i,:) = ...
        eLoad(i,:) ...
        -ePV(i,:);
    blendWeight(i) = ...
        wHist;
    complete(i) = ...
        all(isfinite(baseLoad(i,:))) ...
        && all(isfinite(basePV(i,:))) ...
        && all(isfinite(eNet(i,:)));
end
Rlib.date = ...
    F.dates;
Rlib.issueHour = ...
    F.issueHour;
Rlib.issueTime = ...
    F.issueTime;
Rlib.baseLoad = ...
    baseLoad;
Rlib.basePV = ...
    basePV;
Rlib.eLoad = ...
    eLoad;
Rlib.ePV = ...
    ePV;
Rlib.eNet = ...
    eNet;
Rlib.blendWeight = ...
    blendWeight;
Rlib.complete = ...
    complete;
end

% Similar10选择

function S = getSimilarResidualScenarios( ...
    Rlib, ...
    issueHour, ...
    currentTime, ...
    currentLoad24, ...
    currentPV24, ...
    historyWindow, ...
    minHistory, ...
    similarCount)

% 只能使用已经完整结束的历史24h记录

valid = Rlib.complete &Rlib.issueHour==issueHour &( Rlib.issueTime+hours(24) <=currentTime);
rows = find(valid);
if isempty(rows)
    S.netResidual = ...
        zeros(1,144);
    S.prob = ...
        1;
    S.nHistory = ...
        0;
    S.nSelected = ...
        1;
    S.meanDistance = ...
        NaN;
    S.selectedDate = ...
        NaT;
    return;
end

% 按时间排序，取最近30条

[~,ord] = ...
    sort(Rlib.issueTime(rows));
rows = rows(ord);
firstKeep = max(1, length(rows)-historyWindow+1);
rows = rows(firstKeep:end);
nHistory = length(rows);

% 历史不足时：
% 使用零残差情景

if nHistory<minHistory
    S.netResidual = ...
        zeros(1,144);
    S.prob = ...
        1;
    S.nHistory = ...
        nHistory;
    S.nSelected = ...
        1;
    S.meanDistance = ...
        NaN;
    S.selectedDate = ...
        NaT;
    return;
end
currentLoad24 = currentLoad24(:)';
currentPV24 = currentPV24(:)';
loadScale = max(mean(abs(currentLoad24)), 1);
pvScale = max(mean(abs(currentPV24)), 1);
loadDistance = sqrt(mean(( ( Rlib.baseLoad(rows,:) -currentLoad24) /loadScale).^2, 2));
pvDistance = sqrt(mean(( ( Rlib.basePV(rows,:) -currentPV24) /pvScale).^2, 2));
totalDistance = loadDistance +pvDistance;
[~,order] = ...
    sort( ...
    totalDistance, ...
    'ascend');
keepN = min(similarCount, length(order));
keep = order(1:keepN);
selectedRows = rows(keep);

% 直接保留真实净负荷残差路径

S.netResidual = ...
    Rlib.eNet(selectedRows,:);
S.prob = ...
    ones(keepN,1) ...
    /keepN;
S.nHistory = ...
    nHistory;
S.nSelected = ...
    keepN;
S.meanDistance = ...
    mean( ...
    totalDistance(keep));
S.selectedDate = ...
    Rlib.date(selectedRows);
S.distance = ...
    totalDistance(keep);
end

% 正式PV未来24h

function formal24 = makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour)
date0 = dateAll(d);
id = find(F.dates==date0 &F.issueHour==issueHour, 1);
if isempty(id)
    error( ...
        '找不到%s %02d时正式预报。', ...
        string(date0), ...
        issueHour);
end
anchor = observedPVAtIssue(pvAll, d, issueHour);
xSlot = 0:6:144;
querySlot = 1:144;
formal24 = interp1(xSlot, [ anchor, F.forecast(id,:) ], querySlot, 'linear')';
formal24 = max(formal24, 0);
end

% 光伏融合

function pv24 = makeOfficialPV24Blend( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    w)
formal24 = makeFormalPV24(F, pvAll, dateAll, d, issueHour);
history24 = makeHistoryPV24(pvAll, d, issueHour);
pv24 = w*formal24 +(1-w)*history24;
pv24 = max(pv24, 0);
end

% 前3天同发布时间实际光伏平均

function history24 = makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour)
paths = zeros(144,3);
for k = 1:3
    histDay = d-k;
    onePath = extractActual24(pvAll, histDay, issueHour);
    if isempty(onePath)
        error( ...
            '历史光伏路径不足。');
    end
    paths(:,k) = ...
        onePath;
end
history24 = mean(paths,2);
end

% 负载未来24h

function load24 = makeLoadForecast24( ...
    predToday, ...
    predNext, ...
    d, ...
    issueHour)
startSlot = issueHour*6+1;
load24 = [ predToday(d,startSlot:end), predNext(d,1:startSlot-1) ]';
end

% 冻结0时PV 48h

function frozen48 = buildFrozenPV48( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    w0)
today = makeOfficialPV24Blend(F, pvAll, dateAll, d, 0, w0);
historyNext = mean(pvAll(d-(1:3),:), 1)';
frozen48 = max([today;historyNext], 0);
end

% 当前发布时间真实光伏锚点

function value = observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour)
if issueHour==0
    if d<=1
        error( ...
            '无法获得0时锚点。');
    end
    value = pvAll(d-1,144);
else
    issueCol = issueHour*6;
    value = pvAll(d,issueCol);
end
end

% 提取发布时间以后连续24h真实路径

function path = extractActual24( ...
    data, ...
    d, ...
    issueHour)
startSlot = issueHour*6+1;
if issueHour==0
    path = data(d,:)';
elseif d<size(data,1)
    todayPart = data(d,startSlot:end);
    nextPart = data(d+1,1:startSlot-1);
    path = [ todayPart, nextPart ]';
else
    path = [];
end
end

% AS-Ridge负载

function [predToday,predNext] = buildCausalLoadASRidge( ...
    loadAll, ...
    dateAll, ...
    tau, ...
    lambda, ...
    maxIter, ...
    tol, ...
    windowDays)
[nDay,nTime] = ...
    size(loadAll);
predToday = nan(nDay,nTime);
predNext = nan(nDay,nTime);
slot = (0:nTime-1)';
sinDay = sin(2*pi*slot/nTime);
cosDay = cos(2*pi*slot/nTime);
for d = 16:nDay
    firstDay = max(15, d-windowDays);
    trainDays = firstDay:(d-1);
    X = zeros(length(trainDays)*nTime, 7);
    y = zeros(length(trainDays)*nTime, 1);
    r0 = 1;
    for j = trainDays
        rr = r0:(r0+nTime-1);
        wd = weekday(dateAll(j));
        X(rr,:) = ...
            [ ...
            loadAll(j-1,:)', ...
            loadAll(j-7,:)', ...
            loadAll(j-14,:)', ...
            sinDay, ...
            cosDay, ...
            repmat( ...
            sin(2*pi*(wd-1)/7), ...
            nTime,1), ...
            repmat( ...
            cos(2*pi*(wd-1)/7), ...
            nTime,1) ...
            ];
        y(rr) = ...
            loadAll(j,:)';
        r0 = r0+nTime;
    end
    wdToday = weekday(dateAll(d));
    Xtoday = ...
        [ ...
        loadAll(d-1,:)', ...
        loadAll(d-7,:)', ...
        loadAll(d-14,:)', ...
        sinDay, ...
        cosDay, ...
        repmat( ...
        sin(2*pi*(wdToday-1)/7), ...
        nTime,1), ...
        repmat( ...
        cos(2*pi*(wdToday-1)/7), ...
        nTime,1) ...
        ];
    yToday = fitASRidgeLocal(X, y, Xtoday, tau, lambda, maxIter, tol);
    wdNext = weekday(dateAll(d)+days(1));
    Xnext = ...
        [ ...
        yToday, ...
        loadAll(d+1-7,:)', ...
        loadAll(d+1-14,:)', ...
        sinDay, ...
        cosDay, ...
        repmat( ...
        sin(2*pi*(wdNext-1)/7), ...
        nTime,1), ...
        repmat( ...
        cos(2*pi*(wdNext-1)/7), ...
        nTime,1) ...
        ];
    yNext = fitASRidgeLocal(X, y, Xnext, tau, lambda, maxIter, tol);
    predToday(d,:) = ...
        max(yToday,0)';
    predNext(d,:) = ...
        max(yNext,0)';
end
end

% AS-Ridge

function yPred = fitASRidgeLocal( ...
    Xtrain, ...
    Ytrain, ...
    Xtest, ...
    tau, ...
    lambda, ...
    maxIter, ...
    tol)
muX = mean(Xtrain,1);
sdX = std(Xtrain,0,1);
sdX( ...
    sdX<1e-10 ...
    |~isfinite(sdX)) = ...
    1;
Xtr = (Xtrain-muX)./sdX;
Xte = (Xtest-muX)./sdX;
muY = mean(Ytrain);
sdY = std(Ytrain);
if sdY<1e-10 ...
        || ~isfinite(sdY)
    sdY = 1;
end
y = (Ytrain-muY)/sdY;
X1 = [ ones(size(Xtr,1),1), Xtr ];
Xt = [ ones(size(Xte,1),1), Xte ];
R = eye(size(X1,2));
R(1,1) = ...
    0;
beta = ( X1'*X1 +lambda*R) \(X1'*y);
for iter = 1:maxIter
    e = y -X1*beta;
    w = (1-tau) *ones(size(e));
    w(e>=0) = ...
        tau;
    w = max(w,1e-6);
    Xw = X1.*sqrt(w);
    yw = y.*sqrt(w);
    betaNew = ( Xw'*Xw +lambda*R) \(Xw'*yw);
    change = norm(betaNew-beta) /max(norm(beta), 1e-8);
    beta = betaNew;
    if change<tol
        break;
    end
end
yPred = (Xt*beta) *sdY +muY;
yPred = yPred(:);
end

% 附件3读取

function F = readForecastSingleSheet( ...
    filename, ...
    sheetName)
C = readcell(filename, 'Sheet',sheetName);
[nRow,nCol] = ...
    size(C);
headerRow = NaN;
for r = 1:min(nRow,30)
    for c = 1:nCol
        txt = replace(strtrim(string(C{r,c})), " ", "");
        if txt=="预报1小时" ...
                || txt=="预测1小时"
            headerRow = r;
            break;
        end
    end
    if ~isnan(headerRow)
        break;
    end
end
if isnan(headerRow)
    error( ...
        '附件3找不到表头。');
end
dateCol = NaN;
issueCol = NaN;
for c = 1:nCol
    txt = replace(strtrim(string(C{headerRow,c})), " ", "");
    if contains(txt,"日期")
        dateCol = c;
    end
    if contains(txt,"预报时刻") ...
            || contains(txt,"预测时刻")
        issueCol = c;
    end
end
forecastCols = nan(1,24);
for h = 1:24
    for c = 1:nCol
        txt = replace(strtrim(string(C{headerRow,c})), " ", "");
        if txt==sprintf( ...
                '预报%d小时',h) ...
                || txt==sprintf( ...
                '预测%d小时',h)
            forecastCols(h) = ...
                c;
            break;
        end
    end
    if isnan(forecastCols(h))
        error( ...
            '缺少预报%d小时列。', ...
            h);
    end
end
maxN = nRow-headerRow;
dates = NaT(maxN,1);
issueHour = nan(maxN,1);
forecast = nan(maxN,24);
count = 0;
currentDate = NaT;
for r = headerRow+1:nRow
    newDate = parseOneDate(C{r,dateCol});
    if ~isnat(newDate)
        currentDate = dateshift(newDate, 'start','day');
    end
    if isnat(currentDate)
        continue;
    end
    hIssue = parseIssueHour(C{r,issueCol});
    if isnan(hIssue) ...
            || ~ismember( ...
            hIssue, ...
            [0,6,12,18])
        continue;
    end
    vals = nan(1,24);
    for h = 1:24
        vals(h) = ...
            valueToDouble( ...
            C{r,forecastCols(h)});
    end
    if all(isnan(vals))
        continue;
    end
    count = count+1;
    dates(count) = ...
        currentDate;
    issueHour(count) = ...
        hIssue;
    forecast(count,:) = ...
        vals;
end
dates = dates(1:count);
issueHour = issueHour(1:count);
forecast = forecast(1:count,:);
T = table(dates, issueHour, (1:count)', 'VariableNames',{ 'Date','Hour','ID'});
T = sortrows(T, {'Date','Hour'});
id = T.ID;
F.dates = ...
    dates(id);
F.issueHour = ...
    issueHour(id);
F.forecast = ...
    forecast(id,:);
F.issueTime = ...
    F.dates ...
    +hours(F.issueHour);
end

% 日期解析

function d = parseOneDate(x)
d = NaT;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isdatetime(x)
    if ~isnat(x)
        d = x(1);
    end
    return;
end
if isnumeric(x)
    if isempty(x) ...
            || isnan(x)
        return;
    end
    try
        d = datetime(x, 'ConvertFrom','excel');
        return;
    catch
    end
end
s = strtrim(string(x));
if ismissing(s) ...
        || strlength(s)==0
    return;
end
try
    d = datetime(s);
catch
    d = NaT;
end
end

% 发布时间解析

function h = parseIssueHour(x)
h = NaN;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isduration(x)
    h = mod(round(hours(x)), 24);
    return;
end
if isdatetime(x)
    if ~isnat(x)
        h = hour(x);
    end
    return;
end
if isnumeric(x)
    if isempty(x) ...
            || isnan(x)
        return;
    end
    if x>=0 ...
            && x<1
        h = mod(round(24*x), 24);
        return;
    end
    if x>=0 ...
            && x<=24
        h = round(x);
        if h==24
            h = 0;
        end
        return;
    end
end
s = strtrim(string(x));
token = regexp(char(s), '(\d{1,2})\s*:', 'tokens','once');
if ~isempty(token)
    h = mod(str2double(token{1}), 24);
end
end

% 单元格转double

function y = valueToDouble(x)
y = NaN;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isnumeric(x)
    if ~isempty(x)
        y = double(x(1));
    end
    return;
end
if islogical(x)
    y = double(x);
    return;
end
s = strtrim(string(x));
if ismissing(s) ...
        || strlength(s)==0
    return;
end
y = str2double(s);
end

% 辅助：
% 紧急购电连续时段

function txt = makeEmergencyTimeRange(s,e)
startMinute = 10*(s-1);
endMinute = 10*e;
txt = ...
    sprintf( ...
    '%s-%s', ...
    formatResult3Time(startMinute), ...
    formatResult3Time(endMinute));
end

% 时间文字

function txt = formatResult3Time(totalMinute)
dayAdd = floor(totalMinute/1440);
minuteOfDay = mod(totalMinute,1440);
hh = floor(minuteOfDay/60);
mm = mod(minuteOfDay,60);
if dayAdd==0
    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh,mm);
else
    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh,mm);
end
end
