% 问题4-3：光伏与实时电价联合滚动调度
% 负载预测读取问题2结果，光伏采用四时次动态融合，净负荷误差由Similar10路径描述。
% 实时电价在0、6、12、18时严格利用已发生价格更新，决策阶段不读取未来真实电价。
% 每次求解24 h因果仿射追索模型，只执行未来6 h，并以实际SOC进入下一滚动阶段。
% TIMEFIX：附件原始144列保持不变，结果写入附件5中的result4-3.xlsx。

clear;
clc;
close all;
rng(20260912,'twister');
fprintf(' C题问题4-3\n');
fprintf(' Similar10 + Causal Affine + 滚动实时电价\n');
fprintf(' TIMEFIX\n');

%% 文件与参数

rootDir = fileparts(mfilename('fullpath'));
dataDir = fullfile(rootDir, 'data');
baseDir = fullfile(rootDir, '支撑材料');

% 问题2最终MAT

Q2File = fullfile(baseDir, 'Q2_P2_SIMILAR10_RESULT2_FINAL.mat');

% 附件2
actualFile = fullfile(dataDir, '附件2.xlsx');

% 附件3
forecastFile = fullfile(dataDir, '附件3.xlsx');

% 附件4
priceFile = fullfile(dataDir, '附件4.xlsx');

% 官方result4-3
result43File = fullfile(rootDir, 'result4-3.xlsx');

% 自己保存的MAT
resultMatFile = fullfile(baseDir, 'Q4_3_Similar10_Affine_RollingPrice_FINAL.mat');

% 自己保存的分析Excel
resultExcelFile = fullfile(baseDir, 'Q4_3_Similar10_Affine_RollingPrice_FINAL.xlsx');
filesNeed = {
    Q2File
    actualFile
    forecastFile
    priceFile
    result43File
    };
for i = 1:length(filesNeed)
    if ~isfile(filesNeed{i})
        error( ...
            '找不到文件：\n%s', ...
            filesNeed{i});
    end
end

% 储能与时间参数

dt = 1/6;
eta = 0.90;
Ecapacity = 12000;
Emin = 1200;
Emax = 10800;
Einitial = 6000;
Efinal = 6000;
Pmax = 5000;
Wmax = Pmax*dt;
issueHours = [0,6,12,18];

% Similar10参数

SIMILAR_WINDOW = 30;
SIMILAR_MIN_HISTORY = 7;
SIMILAR_COUNT = 10;

% 光伏融合参数

PV_BLEND_WINDOW = 30;
PV_BLEND_MIN_HISTORY = 7;

% 电价预测参数

PRICE_KL = 1;
PRICE_KS = 2;
USE_PRICE_ROLLING_UPDATE = true;

% 优化参数

cyclePenalty = 1e-5;
curtailPenalty = 1e-5;
USE_TERMINAL_VALUE = true;
FORCE_FINAL_SOC_6000 = false;
WRITE_OFFICIAL_RESULT43 = true;

%% 数据读取与时间轴

dateAll = ( datetime(2025,1,1): days(1): datetime(2025,12,31))';
targetDays = 32:365;
predDatesDefault = dateAll(targetDays);
nDay = 334;
nTime = 144;

% 问题2负载预测

fprintf('读取问题2最终MAT...\n');
Q2 = load(Q2File);
if ~isfield(Q2,'predLoad')
    error( ...
        '问题2 MAT中找不到 predLoad。');
end
predLoad = Q2.predLoad;
if ~isequal(size(predLoad),[334,144])
    error( ...
        '问题2 predLoad必须为334×144。');
end
predLoad = max(predLoad,0);
if isfield(Q2,'predDates')
    predDates = Q2.predDates(:);
else
    predDates = predDatesDefault;
end
if length(predDates)~=334
    error( ...
        'predDates必须为334天。');
end
fprintf('AS-Ridge负载预测读取完成。\n');
fprintf('问题4-3不再重新训练AS-Ridge。\n\n');

% 真实负载与光伏

fprintf('读取附件2...\n');
loadAll = readmatrix(actualFile, 'Sheet','小区负载', 'Range','B2:EO366');
pvAll = readmatrix(actualFile, 'Sheet','光伏发电实际功率', 'Range','B2:EO366');
if ~isequal(size(loadAll),[365,144]) ...
        ||~isequal(size(pvAll),[365,144])
    error( ...
        '附件2必须为365×144。');
end
if any(~isfinite(loadAll),'all') ...
        ||any(~isfinite(pvAll),'all')
    error( ...
        '附件2存在非法值。');
end
fprintf('附件2读取完成。\n\n');

% 实际实时电价

fprintf('读取附件4实时电价...\n');
priceSheets = sheetnames(priceFile);
priceAll = readmatrix(priceFile, 'Sheet',priceSheets(1), 'Range','B2:EO366');
if ~isequal(size(priceAll),[365,144])
    error( ...
        '附件4必须为365×144。');
end
if any(~isfinite(priceAll),'all') ...
        ||any(priceAll<0,'all')
    error( ...
        '附件4存在非法电价。');
end
actualPriceRun = priceAll(targetDays,:);

%% 滚动实时电价预测

fprintf('生成严格因果滚动实时电价预测...\n');
[ ...
    priceForecastCache, ...
    priceForecastDiagTable, ...
    price0hMAE, ...
    priceBlockMAE ...
    ] = ...
    buildRollingPriceForecastCache( ...
    priceAll, ...
    dateAll, ...
    targetDays, ...
    issueHours, ...
    PRICE_KL, ...
    PRICE_KS, ...
    USE_PRICE_ROLLING_UPDATE);
fprintf('\n');
fprintf(' 实时电价预测诊断\n');
fprintf( ...
    '0时完整144点MAE：%.6f 元/kWh\n', ...
    price0hMAE);
for ki = 1:4
    fprintf( ...
        '%2d时后未来6h MAE：%.6f 元/kWh\n', ...
        issueHours(ki), ...
        priceBlockMAE(ki));
end

%% 光伏动态融合

fprintf('读取附件3...\n');
F = readForecastSingleSheet(forecastFile, 'Sheet1');
if ~all( ...
        ismember( ...
        issueHours, ...
        unique(F.issueHour)'))
    error( ...
        '附件3未完整包含0/6/12/18时预报。');
end

% 光伏融合历史库

fprintf('建立光伏动态融合标定库...\n');
PVlib = buildPVBlendCalibrationLibrary(F, pvAll, dateAll);
fprintf( ...
    '完整光伏历史记录：%d条。\n\n', ...
    sum(PVlib.complete));

% 滚动融合权重

wDynamic = ones(nDay,4);
nWeightHistory = zeros(nDay,4);
fprintf('计算0/6/12/18时PV融合权重...\n');
for kd = 1:nDay
    thisDate = predDates(kd);
    for ki = 1:4
        hIssue = issueHours(ki);
        currentTime = thisDate +hours(hIssue);
        [ ...
            wDynamic(kd,ki), ...
            nWeightHistory(kd,ki) ...
            ] = ...
            getRollingPVBlendWeight( ...
            PVlib, ...
            hIssue, ...
            currentTime, ...
            PV_BLEND_WINDOW, ...
            PV_BLEND_MIN_HISTORY);
    end
end
weightTable = ...
    table( ...
    predDates, ...
    wDynamic(:,1), ...
    wDynamic(:,2), ...
    wDynamic(:,3), ...
    wDynamic(:,4), ...
    nWeightHistory(:,1), ...
    nWeightHistory(:,2), ...
    nWeightHistory(:,3), ...
    nWeightHistory(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'Weight_0h', ...
    'Weight_6h', ...
    'Weight_12h', ...
    'Weight_18h', ...
    'HistoryN_0h', ...
    'HistoryN_6h', ...
    'HistoryN_12h', ...
    'HistoryN_18h'} ...
    );

%% Similar10残差库
% 注意：
% 不再K-means。
% 每条历史记录保存：
% baseLoad
% basePV
% actualLoad-baseLoad
% actualPV-basePV
% eNet = eLoad-ePV

fprintf('建立Similar10历史残差库...\n');
Rlib = ...
    buildSimilarResidualLibraryQ2( ...
    F, ...
    loadAll, ...
    pvAll, ...
    predLoad, ...
    predDates, ...
    dateAll, ...
    PVlib, ...
    PV_BLEND_WINDOW, ...
    PV_BLEND_MIN_HISTORY);
fprintf( ...
    '完整Similar10历史记录：%d条。\n\n', ...
    sum(Rlib.complete));

%% 滚动优化与实际回放

lpOptions = optimoptions('linprog', 'Algorithm','dual-simplex-highs', 'Display','none');

% 结果变量

plan0 = zeros(nDay,nTime);
executedPlan = zeros(nDay,nTime);
baseChargePlan = zeros(nDay,nTime);
baseDischargePlan = zeros(nDay,nTime);
actualCharge = zeros(nDay,nTime);
actualDischarge = zeros(nDay,nTime);
actualEmergency = zeros(nDay,nTime);
actualSurplus = zeros(nDay,nTime);
SOCstart = zeros(nDay,1);
SOCend = zeros(nDay,1);
retainedPlanCostDay = zeros(nDay,1);
increaseCostDay = zeros(nDay,1);
decreasePenaltyDay = zeros(nDay,1);
emergencyCostDay = zeros(nDay,1);
increaseEnergyDay = zeros(nDay,1);
decreaseEnergyDay = zeros(nDay,1);
similarN = nan(nDay,4);
similarMeanDistance = nan(nDay,4);
adjustmentTable = table();
maxLPViolation = 0;
Ecurrent = Einitial;

% 0/6/12/18时滚动求解

fprintf(' 开始Q4-3滚动优化\n');
timerAll = tic;
for kd = 1:nDay
    thisDate = predDates(kd);
    dFull = find(dateAll==thisDate, 1);
    if isempty(dFull)
        error( ...
            '日期映射失败：%s', ...
            string(thisDate));
    end
    actualPriceDay = priceAll(dFull,:)';
    isLastDay = kd==nDay;
    forceFinalToday = isLastDay &&FORCE_FINAL_SOC_6000;
    SOCstart(kd) = ...
        Ecurrent;
    currentPlan = zeros(144,1);
    currentChBase = zeros(144,1);
    currentDisBase = zeros(144,1);
    g0 = zeros(144,1);
    if mod(kd-1,20)==0 ...
            ||isLastDay
        fprintf( ...
            '[%03d/%03d] %s | SOC %.2f\n', ...
            kd, ...
            nDay, ...
            string(thisDate), ...
            Ecurrent);
    end

    % 每日0 / 6 / 12 / 18

    for ki = 1:4
        hIssue = issueHours(ki);
        startSlot = hIssue*6+1;
        endSlot = min(startSlot+35, 144);
        blockSlots = startSlot:endSlot;
        qCurrent = 144-startSlot+1;

% 14.1 AS-Ridge未来24h负载

        baseLoad24 = makeQ2LoadForecast24(predLoad, kd, hIssue, true);

% 14.2 动态融合未来24h PV

        wNow = wDynamic(kd,ki);
        basePV24 = makeOfficialPV24Blend(F, pvAll, dateAll, dFull, hIssue, wNow);

% 14.3 Similar10

        currentTime = thisDate +hours(hIssue);
        S = ...
            getSimilarResidualScenarios( ...
            Rlib, ...
            hIssue, ...
            currentTime, ...
            baseLoad24, ...
            basePV24, ...
            SIMILAR_WINDOW, ...
            SIMILAR_MIN_HISTORY, ...
            SIMILAR_COUNT);
        similarN(kd,ki) = ...
            S.nSelected;
        similarMeanDistance(kd,ki) = ...
            S.meanDistance;

% 14.4 基础净负荷

        forecastNet24 = baseLoad24(:) -basePV24(:);

% 14.5 当前发布时间预测实时电价

        price24 = priceForecastCache{kd,ki};
        price24 = price24(:);
        if length(price24)~=144
            error( ...
                '滚动实时电价长度不是144。');
        end

% 14.6 相对0时原计划

        if ki==1
            g0Remain = [];
        else
            g0Remain = g0(startSlot:end);
        end

% 14.7 终端SOC价值

        if USE_TERMINAL_VALUE ...
                &&~isLastDay
            terminalValueNow = eta *mean(price24);
        else
            terminalValueNow = 0;
        end

% 14.8 Similar10 + Causal Affine滚动LP

        P = ...
            solveRolling24hCausalAffineLP( ...
            forecastNet24, ...
            S.netResidual, ...
            S.prob, ...
            price24, ...
            qCurrent, ...
            g0Remain, ...
            Ecurrent, ...
            forceFinalToday, ...
            Efinal, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax, ...
            terminalValueNow, ...
            cyclePenalty, ...
            curtailPenalty, ...
            lpOptions);
        maxLPViolation = max(maxLPViolation, P.maxConstraintViolation);

        % 0时形成基准计划

        if ki==1
            g0 = P.currentGrid;
            currentPlan = g0;
            currentChBase = P.currentChargeBase;
            currentDisBase = P.currentDischargeBase;
            plan0(kd,:) = ...
                g0';

        % 6/12/18调整

        else
            oldPlan = currentPlan(startSlot:end);
            currentPlan(startSlot:end) = ...
                P.currentGrid;
            currentChBase(startSlot:end) = ...
                P.currentChargeBase;
            currentDisBase(startSlot:end) = ...
                P.currentDischargeBase;
            oneInc = sum(max(P.currentGrid -g0(startSlot:end), 0));
            oneDec = sum(max(g0(startSlot:end) -P.currentGrid, 0));
            logRow = ...
                table( ...
                thisDate, ...
                hIssue, ...
                wNow, ...
                mean(price24), ...
                S.nSelected, ...
                S.meanDistance, ...
                sum( ...
                abs( ...
                P.currentGrid-oldPlan) ...
                >1e-6), ...
                oneInc, ...
                oneDec, ...
                P.objective, ...
                P.maxConstraintViolation, ...
                'VariableNames',{ ...
                'Date', ...
                'IssueHour', ...
                'PVBlendWeight', ...
                'ForecastPriceMean', ...
                'SimilarCount', ...
                'SimilarMeanDistance', ...
                'ChangedSlots', ...
                'IncreaseVs0_kWh', ...
                'DecreaseVs0_kWh', ...
                'RollingObjective', ...
                'MaxConstraintViolation'} ...
                );
            adjustmentTable = [adjustmentTable;logRow];
        end

% 14.9 实际执行未来6h
        % 从基础储能轨迹开始，再利用当前真实误差进行反馈

        A = ...
            replayActualBlockWithBase( ...
            loadAll(dFull,blockSlots)', ...
            pvAll(dFull,blockSlots)', ...
            currentPlan(blockSlots), ...
            currentChBase(blockSlots), ...
            currentDisBase(blockSlots), ...
            Ecurrent, ...
            blockSlots, ...
            forceFinalToday, ...
            Efinal, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax);
        executedPlan(kd,blockSlots) = ...
            currentPlan(blockSlots)';
        baseChargePlan(kd,blockSlots) = ...
            currentChBase(blockSlots)';
        baseDischargePlan(kd,blockSlots) = ...
            currentDisBase(blockSlots)';
        actualCharge(kd,blockSlots) = ...
            A.Wch';
        actualDischarge(kd,blockSlots) = ...
            A.Wdis';
        actualEmergency(kd,blockSlots) = ...
            A.Wem';
        actualSurplus(kd,blockSlots) = ...
            A.Wsur';
        Ecurrent = A.Eend;
    end

% 14.10 日末SOC

    SOCend(kd) = ...
        Ecurrent;

% 14.11 使用附件4真实价格进行正式结算

    inc = max(executedPlan(kd,:)' -g0, 0);
    dec = max(g0 -executedPlan(kd,:)', 0);
    retainedPlanCostDay(kd) = ...
        sum( ...
        actualPriceDay ...
        .*min( ...
        g0, ...
        executedPlan(kd,:)'));
    increaseCostDay(kd) = ...
        1.5 ...
        *sum( ...
        actualPriceDay ...
        .*inc);
    decreasePenaltyDay(kd) = ...
        0.5 ...
        *sum( ...
        actualPriceDay ...
        .*dec);
    emergencyCostDay(kd) = ...
        5 ...
        *sum( ...
        actualPriceDay ...
        .*actualEmergency(kd,:)');
    increaseEnergyDay(kd) = ...
        sum(inc);
    decreaseEnergyDay(kd) = ...
        sum(dec);
end
runtimeMin = toc(timerAll)/60;

%% 结果统计

dailyCost = retainedPlanCostDay +increaseCostDay +decreasePenaltyDay +emergencyCostDay;
totalRetainedPlanCost = sum(retainedPlanCostDay);
totalIncreaseCost = sum(increaseCostDay);
totalDecreasePenalty = sum(decreasePenaltyDay);
totalEmergencyCost = sum(emergencyCostDay);
totalCost = sum(dailyCost);
totalIncreaseEnergy = sum(increaseEnergyDay);
totalDecreaseEnergy = sum(decreaseEnergyDay);
totalEmergencyEnergy = sum(actualEmergency,'all');
emergencyDays = sum(any(actualEmergency>1e-8, 2));
emergencySlots = nnz(actualEmergency>1e-8);
planSimultaneousSlots = nnz(baseChargePlan>1e-8 &baseDischargePlan>1e-8);
actualSimultaneousSlots = nnz(actualCharge>1e-8 &actualDischarge>1e-8);
finalSOC = SOCend(end);
costIdentityError = ...
    abs( ...
    totalCost ...
    -( ...
    totalRetainedPlanCost ...
    +totalIncreaseCost ...
    +totalDecreasePenalty ...
    +totalEmergencyCost));
fprintf('\n');
fprintf(' Q4-3 Similar10 + 因果仿射主结果\n');
fprintf( ...
    '保留0时计划购电费：%.2f 元\n', ...
    totalRetainedPlanCost);
fprintf( ...
    '增加购电费用：%.2f 元\n', ...
    totalIncreaseCost);
fprintf( ...
    '减少购电违约费用：%.2f 元\n', ...
    totalDecreasePenalty);
fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    totalEmergencyCost);
fprintf('\n');
fprintf( ...
    '全年总成本：%.2f 元\n', ...
    totalCost);
fprintf( ...
    '增加购电量：%.2f kWh\n', ...
    totalIncreaseEnergy);
fprintf( ...
    '减少购电量：%.2f kWh\n', ...
    totalDecreaseEnergy);
fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    totalEmergencyEnergy);
fprintf( ...
    '紧急购电天数：%d\n', ...
    emergencyDays);
fprintf( ...
    '紧急购电时段数：%d\n', ...
    emergencySlots);
fprintf('\n');
fprintf( ...
    '年末SOC：%.6f kWh\n', ...
    finalSOC);
fprintf( ...
    '计划基础轨迹同时充放电：%d\n', ...
    planSimultaneousSlots);
fprintf( ...
    '实际同时充放电：%d\n', ...
    actualSimultaneousSlots);
fprintf( ...
    '最大LP违反量：%.3e\n', ...
    maxLPViolation);
fprintf( ...
    '成本核对误差：%.3e 元\n', ...
    costIdentityError);
fprintf( ...
    '运行时间：%.2f min\n', ...
    runtimeMin);

% 每日结果

dailyTable = ...
    table( ...
    predDates, ...
    SOCstart, ...
    SOCend, ...
    retainedPlanCostDay, ...
    increaseCostDay, ...
    decreasePenaltyDay, ...
    emergencyCostDay, ...
    dailyCost, ...
    increaseEnergyDay, ...
    decreaseEnergyDay, ...
    sum(actualEmergency,2), ...
    'VariableNames',{ ...
    'Date', ...
    'SOCstart_kWh', ...
    'SOCend_kWh', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh'} ...
    );

% Similar10诊断

similarTable = ...
    table( ...
    predDates, ...
    similarN(:,1), ...
    similarN(:,2), ...
    similarN(:,3), ...
    similarN(:,4), ...
    similarMeanDistance(:,1), ...
    similarMeanDistance(:,2), ...
    similarMeanDistance(:,3), ...
    similarMeanDistance(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'SimilarN_0h', ...
    'SimilarN_6h', ...
    'SimilarN_12h', ...
    'SimilarN_18h', ...
    'Distance_0h', ...
    'Distance_6h', ...
    'Distance_12h', ...
    'Distance_18h'} ...
    );

% 全年汇总

summaryTable = ...
    table( ...
    "AS-Ridge + PVBlend + Similar10 + Affine", ...
    price0hMAE, ...
    priceBlockMAE(1), ...
    priceBlockMAE(2), ...
    priceBlockMAE(3), ...
    priceBlockMAE(4), ...
    totalRetainedPlanCost, ...
    totalIncreaseCost, ...
    totalDecreasePenalty, ...
    totalEmergencyCost, ...
    totalCost, ...
    totalIncreaseEnergy, ...
    totalDecreaseEnergy, ...
    totalEmergencyEnergy, ...
    emergencyDays, ...
    emergencySlots, ...
    finalSOC, ...
    planSimultaneousSlots, ...
    actualSimultaneousSlots, ...
    maxLPViolation, ...
    runtimeMin, ...
    'VariableNames',{ ...
    'Model', ...
    'PriceMAE_0h', ...
    'PriceMAE_0to6', ...
    'PriceMAE_6to12', ...
    'PriceMAE_12to18', ...
    'PriceMAE_18to24', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh', ...
    'EmergencyDays', ...
    'EmergencySlots', ...
    'FinalSOC_kWh', ...
    'PlanSimultaneousSlots', ...
    'ActualSimultaneousSlots', ...
    'MaxLPViolation', ...
    'Runtime_Min'} ...
    );

%% 保存结果

if isfile(resultExcelFile)
    delete(resultExcelFile);
end
writetable( ...
    summaryTable, ...
    resultExcelFile, ...
    'Sheet','汇总');
writetable( ...
    dailyTable, ...
    resultExcelFile, ...
    'Sheet','每日结果');
writetable( ...
    adjustmentTable, ...
    resultExcelFile, ...
    'Sheet','调整明细');
writetable( ...
    weightTable, ...
    resultExcelFile, ...
    'Sheet','PV动态权重');
writetable( ...
    similarTable, ...
    resultExcelFile, ...
    'Sheet','Similar10诊断');
writetable( ...
    priceForecastDiagTable, ...
    resultExcelFile, ...
    'Sheet','滚动电价预测误差');

% 写入result4-3

if WRITE_OFFICIAL_RESULT43
    fprintf('\n开始写入官方 result4-3.xlsx...\n');

    % 备份

    backupFile = ...
        fullfile( ...
        rootDir, ...
        [ ...
        'result4-3_backup_SIMILAR10_', ...
        char( ...
        datetime( ...
        'now', ...
        'Format','yyyyMMdd_HHmmss')), ...
        '.xlsx' ...
        ]);
    copyfile( ...
        result43File, ...
        backupFile);
    fprintf( ...
        '原result4-3已备份：\n%s\n', ...
        backupFile);

% 20.1 计划购电量

    planEnergyDay = sum(plan0,2);

% 初始0时计划按真实附件4价格结算
    planCostDay = sum(plan0 .*actualPriceRun, 2);
    writematrix( ...
        plan0, ...
        result43File, ...
        'Sheet','计划购电量', ...
        'Range','B2');
    writematrix( ...
        planEnergyDay, ...
        result43File, ...
        'Sheet','计划购电量', ...
        'Range','EP2');
    writematrix( ...
        planCostDay, ...
        result43File, ...
        'Sheet','计划购电量', ...
        'Range','EQ2');
    fprintf('计划购电量写入完成。\n');

% 20.2 调整购电量

    adjustedEnergyDay = sum(executedPlan,2);
    adjustedCostDay = retainedPlanCostDay +increaseCostDay +decreasePenaltyDay;
    writematrix( ...
        executedPlan, ...
        result43File, ...
        'Sheet','调整购电量', ...
        'Range','B2');
    writematrix( ...
        adjustedEnergyDay, ...
        result43File, ...
        'Sheet','调整购电量', ...
        'Range','EP2');
    writematrix( ...
        adjustedCostDay, ...
        result43File, ...
        'Sheet','调整购电量', ...
        'Range','EQ2');
    fprintf('调整购电量写入完成。\n');

% 20.3 充放电量

    timeBlockName = {
        '0:00-4:00'
        '4:00-8:00'
        '8:00-12:00'
        '12:00-16:00'
        '16:00-20:00'
        '20:00-24:00'
        };
    nBlock = 6;
    charge4h = zeros(nDay,nBlock);
    discharge4h = zeros(nDay,nBlock);
    for kd = 1:nDay
        for b = 1:nBlock
            s1 = (b-1)*24+1;
            s2 = b*24;
            charge4h(kd,b) = ...
                sum( ...
                actualCharge(kd,s1:s2));
            discharge4h(kd,b) = ...
                sum( ...
                actualDischarge(kd,s1:s2));
        end
    end
    cdOut = cell(nDay*nBlock,6);
    r = 1;
    for kd = 1:nDay
        for b = 1:nBlock
            if b==1
                cdOut{r,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');
            else
                cdOut{r,1} = ...
                    '';
            end
            cdOut{r,2} = ...
                timeBlockName{b};
            cdOut{r,3} = ...
                charge4h(kd,b);
            cdOut{r,4} = ...
                discharge4h(kd,b);
            if b==1
                cdOut{r,5} = ...
                    '0:00';
                cdOut{r,6} = ...
                    SOCstart(kd);
            elseif b==2
                cdOut{r,5} = ...
                    '24:00';
                cdOut{r,6} = ...
                    SOCend(kd);
            else
                cdOut{r,5} = ...
                    '';
                cdOut{r,6} = ...
                    [];
            end
            r = r+1;
        end
    end
    clearCD = repmat({''},2500,6);
    writecell( ...
        clearCD, ...
        result43File, ...
        'Sheet','充放电量', ...
        'Range','A2');
    writecell( ...
        cdOut, ...
        result43File, ...
        'Sheet','充放电量', ...
        'Range','A2');
    fprintf('充放电量写入完成。\n');

% 20.4 紧急购电量

    emergencyRows = cell(0,3);
    outRow = 0;
    for kd = 1:nDay
        x = actualEmergency(kd,:);
        active = x>1e-8;
        if ~any(active)
            continue;
        end
        edge = diff([false,active,false]);
        starts = find(edge==1);
        ends = find(edge==-1)-1;
        for kk = 1:length(starts)
            s = starts(kk);
            e = ends(kk);
            outRow = outRow+1;
            if kk==1
                emergencyRows{outRow,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');
            else
                emergencyRows{outRow,1} = ...
                    '';
            end
            emergencyRows{outRow,2} = ...
                makeEmergencyTimeRangeQ43( ...
                s,e);
            emergencyRows{outRow,3} = ...
                sum(x(s:e));
        end
    end
    clearEmergency = repmat({''},5000,3);
    writecell( ...
        clearEmergency, ...
        result43File, ...
        'Sheet','紧急购电量', ...
        'Range','A2');
    if ~isempty(emergencyRows)
        writecell( ...
            emergencyRows, ...
            result43File, ...
            'Sheet','紧急购电量', ...
            'Range','A2');
    end
    fprintf('紧急购电量写入完成。\n');
end

% 保存MAT结果

save( ...
    resultMatFile, ...
    'summaryTable', ...
    'dailyTable', ...
    'adjustmentTable', ...
    'weightTable', ...
    'similarTable', ...
    'priceForecastDiagTable', ...
    'priceForecastCache', ...
    'price0hMAE', ...
    'priceBlockMAE', ...
    'predDates', ...
    'predLoad', ...
    'plan0', ...
    'executedPlan', ...
    'baseChargePlan', ...
    'baseDischargePlan', ...
    'actualCharge', ...
    'actualDischarge', ...
    'actualEmergency', ...
    'actualSurplus', ...
    'SOCstart', ...
    'SOCend', ...
    'wDynamic', ...
    'PVlib', ...
    'Rlib', ...
    'totalCost', ...
    'runtimeMin', ...
    '-v7.3');
fprintf('\n');
fprintf(' Q4-3全部完成\n');
fprintf( ...
    '0时价格MAE：%.6f\n', ...
    price0hMAE);
fprintf( ...
    '总成本：%.2f 元\n', ...
    totalCost);
fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    totalEmergencyEnergy);
fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    totalEmergencyCost);
fprintf( ...
    '最终SOC：%.2f kWh\n', ...
    finalSOC);
fprintf('\n官方result4-3：\n%s\n', ...
    result43File);
fprintf('\n分析Excel：\n%s\n', ...
    resultExcelFile);

% Q2 AS-Ridge预测 -> 发布时间以后24h

%% 局部函数
function load24 = makeQ2LoadForecast24( ...
    predLoad, ...
    kd, ...
    issueHour, ...
    allowLastDayFallback)
startSlot = issueHour*6+1;
nDay = size(predLoad,1);
if issueHour==0
    load24 = predLoad(kd,:)';
    return;
end
todayPart = predLoad(kd, startSlot:end);
if kd<nDay
    nextPart = predLoad(kd+1, 1:startSlot-1);
elseif allowLastDayFallback

% 仅作为12月31日24h展望尾部代理
    nextPart = predLoad(kd, 1:startSlot-1);
else
    load24 = [];
    return;
end
load24 = [todayPart,nextPart]';
end

% 建立Similar10残差库

function Rlib = buildSimilarResidualLibraryQ2( ...
    F, ...
    loadAll, ...
    pvAll, ...
    predLoad, ...
    predDates, ...
    dateAll, ...
    PVlib, ...
    blendWindow, ...
    blendMinHistory)
nRec = length(F.dates);
baseLoad = nan(nRec,144);
basePV = nan(nRec,144);
eLoad = nan(nRec,144);
ePV = nan(nRec,144);
eNet = nan(nRec,144);
complete = false(nRec,1);
for i = 1:nRec
    thisDate = F.dates(i);
    kd = find(predDates==thisDate, 1);
    if isempty(kd)
        continue;
    end
    dFull = find(dateAll==thisDate, 1);
    if isempty(dFull)
        continue;
    end
    hIssue = F.issueHour(i);

% 历史残差必须有完整未来24h
    oneBaseLoad = makeQ2LoadForecast24(predLoad, kd, hIssue, false);
    if isempty(oneBaseLoad)
        continue;
    end
    actualLoad24 = extractActual24(loadAll, dFull, hIssue);
    actualPV24 = extractActual24(pvAll, dFull, hIssue);
    if isempty(actualLoad24) ...
            ||isempty(actualPV24)
        continue;
    end
    [wHist,~] = ...
        getRollingPVBlendWeight( ...
        PVlib, ...
        hIssue, ...
        F.issueTime(i), ...
        blendWindow, ...
        blendMinHistory);
    oneBasePV = makeOfficialPV24Blend(F, pvAll, dateAll, dFull, hIssue, wHist);
    baseLoad(i,:) = ...
        oneBaseLoad';
    basePV(i,:) = ...
        oneBasePV';
    eLoad(i,:) = ...
        ( ...
        actualLoad24-oneBaseLoad ...
        )';
    ePV(i,:) = ...
        ( ...
        actualPV24-oneBasePV ...
        )';
    eNet(i,:) = ...
        eLoad(i,:) ...
        -ePV(i,:);
    complete(i) = ...
        all(isfinite(baseLoad(i,:))) ...
        &&all(isfinite(basePV(i,:))) ...
        &&all(isfinite(eNet(i,:)));
end
Rlib.date = F.dates;
Rlib.issueHour = F.issueHour;
Rlib.issueTime = F.issueTime;
Rlib.baseLoad = baseLoad;
Rlib.basePV = basePV;
Rlib.eLoad = eLoad;
Rlib.ePV = ePV;
Rlib.eNet = eNet;
Rlib.complete = complete;
end

% Similar10选择

function S = getSimilarResidualScenarios( ...
    Rlib, ...
    issueHour, ...
    currentTime, ...
    currentLoad24, ...
    currentPV24, ...
    historyWindow, ...
    minHistory, ...
    similarCount)
valid = Rlib.complete &Rlib.issueHour==issueHour &( Rlib.issueTime+hours(24) <=currentTime);
rows = find(valid);
if isempty(rows)
    S.netResidual = zeros(1,144);
    S.prob = 1;
    S.nHistory = 0;
    S.nSelected = 1;
    S.meanDistance = NaN;
    return;
end
[~,ord] = ...
    sort(Rlib.issueTime(rows));
rows = rows(ord);
firstKeep = max(1, length(rows)-historyWindow+1);
rows = rows(firstKeep:end);
nHistory = length(rows);
if nHistory<minHistory
    S.netResidual = zeros(1,144);
    S.prob = 1;
    S.nHistory = nHistory;
    S.nSelected = 1;
    S.meanDistance = NaN;
    return;
end
currentLoad24 = currentLoad24(:)';
currentPV24 = currentPV24(:)';
loadScale = max(mean(abs(currentLoad24)), 1);
pvScale = max(mean(abs(currentPV24)), 1);
loadDistance = sqrt(mean(( ( Rlib.baseLoad(rows,:) -currentLoad24) /loadScale).^2, 2));
pvDistance = sqrt(mean(( ( Rlib.basePV(rows,:) -currentPV24) /pvScale).^2, 2));
totalDistance = loadDistance +pvDistance;
[~,order] = ...
    sort( ...
    totalDistance, ...
    'ascend');
keepN = min(similarCount, length(order));
keep = order(1:keepN);
selectedRows = rows(keep);
S.netResidual = Rlib.eNet(selectedRows,:);
S.prob = ones(keepN,1) /keepN;
S.nHistory = nHistory;
S.nSelected = keepN;
S.meanDistance = mean(totalDistance(keep));
S.selectedDate = Rlib.date(selectedRows);
end

% Similar10因果仿射24h滚动LP

function P = solveRolling24hCausalAffineLP( ...
    forecastNet, ...
    residualScenarios, ...
    prob, ...
    price24, ...
    qCurrent, ...
    g0Remain, ...
    Estart, ...
    forceFinalToday, ...
    Efinal, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    terminalValue, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)
H = 144;
dt = 1/6;
forecastNet = forecastNet(:);
price24 = price24(:);
[K,H2] = ...
    size(residualScenarios);
if length(forecastNet)~=H ...
        ||H2~=H
    error( ...
        '预测与残差必须为144点。');
end
prob = prob(:);
prob = prob/sum(prob);
Wbase = forecastNet' *dt;
R = residualScenarios *dt;
Rp = max(R,0);
Rn = max(-R,0);

% 变量编号

idxG = 1:H;
base = H;
isInitial = isempty(g0Remain);
if isInitial
    idxInc = [];
    idxDec = [];
else
    idxInc = base+(1:qCurrent);
    base = base+qCurrent;
    idxDec = base+(1:qCurrent);
    base = base+qCurrent;
    g0Remain = g0Remain(:);
end
idxC0 = base+(1:H);
base = base+H;
idxD0 = base+(1:H);
base = base+H;
idxACP = base+(1:H);
base = base+H;
idxACN = base+(1:H);
base = base+H;
idxADP = base+(1:H);
base = base+H;
idxADN = base+(1:H);
base = base+H;
idxEbase = base+(1:H+1);
base = base+H+1;
idxSpBase = base+(1:H);
base = base+H;
idxE = reshape(base+(1:K*(H+1)), H+1,K)';
base = base+K*(H+1);
idxEm = reshape(base+(1:K*H), H,K)';
base = base+K*H;
idxSp = reshape(base+(1:K*H), H,K)';
nVar = base+K*H;

% 目标函数

f = zeros(nVar,1);

% 普通购电使用预测实时价格
f(idxG) = ...
    price24;

% 调整
if ~isInitial
    f(idxInc) = ...
        0.5 ...
        *price24(1:qCurrent);
    f(idxDec) = ...
        0.5 ...
        *price24(1:qCurrent);
end

% Scenario成本
for s = 1:K
    f(idxEm(s,:)) = ...
        prob(s) ...
        *5 ...
        *price24;
    f(idxSp(s,:)) = ...
        prob(s) ...
        *curtailPenalty;
    f(idxE(s,end)) = ...
        f(idxE(s,end)) ...
        -prob(s)*terminalValue;
end
f(idxSpBase) = ...
    curtailPenalty;

% 充放电吞吐tie-break
mRp = (prob'*Rp)';
mRn = (prob'*Rn)';
f(idxC0) = ...
    cyclePenalty;
f(idxD0) = ...
    cyclePenalty;
f(idxACP) = ...
    -cyclePenalty*mRp;
f(idxACN) = ...
    cyclePenalty*mRn;
f(idxADP) = ...
    cyclePenalty*mRp;
f(idxADN) = ...
    -cyclePenalty*mRn;

% 等式约束

nAdjustEq = double(~isInitial) *qCurrent;
nBaseEq = 2*H+1;
nScenarioEq = K*(2*H+1);
nEq = nAdjustEq +nBaseEq +nScenarioEq;
Aeq = spalloc(nEq, nVar, 20*nEq);
beq = zeros(nEq,1);
row = 0;

% 调整关系
if ~isInitial
    for t = 1:qCurrent
        row = row+1;
        Aeq(row,idxG(t)) = ...
            1;
        Aeq(row,idxInc(t)) = ...
            -1;
        Aeq(row,idxDec(t)) = ...
            1;
        beq(row) = ...
            g0Remain(t);
    end
end

% 基础路径供需
for t = 1:H
    row = row+1;
    Aeq(row,idxG(t)) = ...
        1;
    Aeq(row,idxD0(t)) = ...
        1;
    Aeq(row,idxC0(t)) = ...
        -1;
    Aeq(row,idxSpBase(t)) = ...
        -1;
    beq(row) = ...
        Wbase(t);
end

% 基础SOC
for t = 1:H
    row = row+1;
    Aeq(row,idxEbase(t)) = ...
        -1;
    Aeq(row,idxEbase(t+1)) = ...
        1;
    Aeq(row,idxC0(t)) = ...
        -eta;
    Aeq(row,idxD0(t)) = ...
        1/eta;
end
row = row+1;
Aeq(row,idxEbase(1)) = ...
    1;
beq(row) = ...
    Estart;

% Scenario
for s = 1:K
    for t = 1:H
        row = row+1;
        Aeq(row,idxG(t)) = ...
            1;
        Aeq(row,idxC0(t)) = ...
            -1;
        Aeq(row,idxD0(t)) = ...
            1;
        Aeq(row,idxACP(t)) = ...
            Rp(s,t);
        Aeq(row,idxACN(t)) = ...
            -Rn(s,t);
        Aeq(row,idxADP(t)) = ...
            Rp(s,t);
        Aeq(row,idxADN(t)) = ...
            -Rn(s,t);
        Aeq(row,idxEm(s,t)) = ...
            1;
        Aeq(row,idxSp(s,t)) = ...
            -1;
        beq(row) = ...
            Wbase(t) ...
            +R(s,t);
    end
    for t = 1:H
        row = row+1;
        Aeq(row,idxE(s,t)) = ...
            -1;
        Aeq(row,idxE(s,t+1)) = ...
            1;
        Aeq(row,idxC0(t)) = ...
            -eta;
        Aeq(row,idxD0(t)) = ...
            1/eta;
        Aeq(row,idxACP(t)) = ...
            eta*Rp(s,t);
        Aeq(row,idxACN(t)) = ...
            -eta*Rn(s,t);
        Aeq(row,idxADP(t)) = ...
            Rp(s,t)/eta;
        Aeq(row,idxADN(t)) = ...
            -Rn(s,t)/eta;
    end
    row = row+1;
    Aeq(row,idxE(s,1)) = ...
        1;
    beq(row) = ...
        Estart;
end

% 不等式：情景充放电范围

nIneq = 4*K*H;
A = spalloc(nIneq, nVar, 12*K*H);
b = zeros(nIneq,1);
row = 0;
for s = 1:K
    for t = 1:H

% C <= Wmax
        row = row+1;
        A(row,idxC0(t)) = ...
            1;
        A(row,idxACP(t)) = ...
            -Rp(s,t);
        A(row,idxACN(t)) = ...
            Rn(s,t);
        b(row) = ...
            Wmax;

% C >= 0
        row = row+1;
        A(row,idxC0(t)) = ...
            -1;
        A(row,idxACP(t)) = ...
            Rp(s,t);
        A(row,idxACN(t)) = ...
            -Rn(s,t);

% D <= Wmax
        row = row+1;
        A(row,idxD0(t)) = ...
            1;
        A(row,idxADP(t)) = ...
            Rp(s,t);
        A(row,idxADN(t)) = ...
            -Rn(s,t);
        b(row) = ...
            Wmax;

% D >= 0
        row = row+1;
        A(row,idxD0(t)) = ...
            -1;
        A(row,idxADP(t)) = ...
            -Rp(s,t);
        A(row,idxADN(t)) = ...
            Rn(s,t);
    end
end

% 上下界

lb = zeros(nVar,1);
ub = inf(nVar,1);
ub(idxC0) = ...
    Wmax;
ub(idxD0) = ...
    Wmax;
ub([
    idxACP
    idxACN
    idxADP
    idxADN
    ]) = ...
    1;
lb(idxEbase) = ...
    Emin;
ub(idxEbase) = ...
    Emax;
lb(idxE(:)) = ...
    Emin;
ub(idxE(:)) = ...
    Emax;
if ~isInitial
    ub(idxDec) = ...
        g0Remain;
end
if forceFinalToday
    midnightState = qCurrent+1;
    lb(idxEbase(midnightState)) = ...
        Efinal;
    ub(idxEbase(midnightState)) = ...
        Efinal;
    for s = 1:K
        lb(idxE(s,midnightState)) = ...
            Efinal;
        ub(idxE(s,midnightState)) = ...
            Efinal;
    end
end

% 求解

[x,fval,exitflag,output] = ...
    linprog( ...
    f, ...
    A,b, ...
    Aeq,beq, ...
    lb,ub, ...
    options);
if exitflag<=0
    error( ...
        'Q4-3 Similar10 LP失败：%s', ...
        output.message);
end
eqViolation = max(abs(Aeq*x-beq));
ineqViolation = max([ A*x-b; 0 ]);
boundViolation = max([ lb-x; x-ub; 0 ]);
P.currentGrid = x(idxG(1:qCurrent));
P.currentChargeBase = x(idxC0(1:qCurrent));
P.currentDischargeBase = x(idxD0(1:qCurrent));
P.objective = fval;
P.maxConstraintViolation = max([ eqViolation; ineqViolation; boundViolation ]);
end

% 实际因果执行

function A = replayActualBlockWithBase( ...
    Pload, ...
    Ppv, ...
    Wgrid, ...
    WchPlan, ...
    WdisPlan, ...
    Estart, ...
    globalSlots, ...
    forceFinalToday, ...
    Efinal, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax)
dt = 1/6;
Wload = Pload(:)*dt;
Wpv = Ppv(:)*dt;
Wgrid = Wgrid(:);
WchPlan = WchPlan(:);
WdisPlan = WdisPlan(:);
N = length(Wgrid);
Wch = zeros(N,1);
Wdis = zeros(N,1);
Wem = zeros(N,1);
Wsur = zeros(N,1);
E = zeros(N+1,1);
E(1) = ...
    Estart;
for j = 1:N
    ec = E(j);
    tGlobal = globalSlots(j);
    if forceFinalToday
        remainingSlots = 144-tGlobal;
        nextLow = max(Emin, Efinal -remainingSlots*eta*Wmax);
        nextHigh = min(Emax, Efinal +remainingSlots*Wmax/eta);
    else
        nextLow = Emin;
        nextHigh = Emax;
    end
    c = min(max(WchPlan(j),0), Wmax);
    d = min(max(WdisPlan(j),0), Wmax);
    en = ec +eta*c -d/eta;

% SOC太低
    if en<nextLow
        rd = min(d, (nextLow-en)*eta);
        d = d-rd;
        en = ec +eta*c -d/eta;
    end

% SOC太高
    if en>nextHigh
        rc = min(c, (en-nextHigh)/eta);
        c = c-rc;
        en = ec +eta*c -d/eta;
    end
    residual = Wload(j) -Wpv(j) -Wgrid(j) -(d-c);

% 缺电
    if residual>1e-12
        reduceCharge = min([ residual, c, max((en-nextLow)/eta, 0) ]);
        c = c-reduceCharge;
        residual = residual-reduceCharge;
        en = en -eta*reduceCharge;
        if residual>1e-12
            extraDis = min([ residual, Wmax-d, eta*max(en-nextLow,0) ]);
            d = d+extraDis;
            residual = residual-extraDis;
            en = en -extraDis/eta;
        end
        Wem(j) = ...
            max(residual,0);

% 富余
    elseif residual<-1e-12
        surplus = -residual;
        reduceDis = min([ surplus, d, eta*max(nextHigh-en,0) ]);
        d = d-reduceDis;
        surplus = surplus-reduceDis;
        en = en +reduceDis/eta;
        if surplus>1e-12
            extraCh = min([ surplus, Wmax-c, max(nextHigh-en,0)/eta ]);
            c = c+extraCh;
            surplus = surplus-extraCh;
            en = en +eta*extraCh;
        end
        Wsur(j) = ...
            max(surplus,0);
    end
    Enew = ec +eta*c -d/eta;
    if Enew<nextLow-1e-6 ...
            ||Enew>nextHigh+1e-6
        error( ...
            '实际回放SOC越界：slot=%d SOC=%.9f', ...
            tGlobal,Enew);
    end
    Wch(j) = ...
        c;
    Wdis(j) = ...
        d;
    E(j+1) = ...
        Enew;
end
A.Wch = Wch;
A.Wdis = Wdis;
A.Wem = Wem;
A.Wsur = Wsur;
A.E = E;
A.Eend = E(end);
end

% PV历史标定库

function L = buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll)
nRec = length(F.dates);
formal = nan(nRec,144);
history = nan(nRec,144);
actual = nan(nRec,144);
complete = false(nRec,1);
for i = 1:nRec
    d = find(dateAll==F.dates(i), 1);
    if isempty(d) ...
            ||d<=3
        continue;
    end
    hIssue = F.issueHour(i);
    actual24 = extractActual24(pvAll,d,hIssue);
    if isempty(actual24)
        continue;
    end
    formal24 = makeFormalPV24(F,pvAll,dateAll,d,hIssue);
    history24 = makeHistoryPV24(pvAll,d,hIssue);
    formal(i,:) = ...
        formal24';
    history(i,:) = ...
        history24';
    actual(i,:) = ...
        actual24';
    complete(i) = ...
        all(isfinite(formal(i,:))) ...
        &&all(isfinite(history(i,:))) ...
        &&all(isfinite(actual(i,:)));
end
L.date = F.dates;
L.issueHour = F.issueHour;
L.issueTime = F.issueTime;
L.formal = formal;
L.history = history;
L.actual = actual;
L.complete = complete;
end

% PV融合权重

function [w,nHistory] = getRollingPVBlendWeight( ...
    L, ...
    issueHour, ...
    currentTime, ...
    windowN, ...
    minHistory)
valid = L.complete &L.issueHour==issueHour &( L.issueTime+hours(24) <=currentTime);
rows = find(valid);
if isempty(rows)
    w = 1;
    nHistory = 0;
    return;
end
[~,ord] = ...
    sort(L.issueTime(rows));
rows = rows(ord);
rows = rows(max(1, length(rows)-windowN+1):end);
nHistory = length(rows);
if nHistory<minHistory
    w = 1;
    return;
end
formal = L.formal(rows,:);
history = L.history(rows,:);
actual = L.actual(rows,:);
formal = formal(:);
history = history(:);
actual = actual(:);
good = isfinite(formal) &isfinite(history) &isfinite(actual);
formal = formal(good);
history = history(good);
actual = actual(good);
den = sum((formal-history).^2);
if isempty(actual) ...
        ||den<1e-12
    w = 1;
    return;
end
w = sum((actual-history) .*(formal-history)) /den;
w = min(max(w,0), 1);
end

% 正式PV24h

function formal24 = makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour)
date0 = dateAll(d);
id = find(F.dates==date0 &F.issueHour==issueHour, 1);
if isempty(id)
    error( ...
        '找不到%s %02d时PV预报。', ...
        string(date0), ...
        issueHour);
end
anchor = observedPVAtIssue(pvAll,d,issueHour);
xSlot = 0:6:144;
querySlot = 1:144;
formal24 = interp1(xSlot, [anchor,F.forecast(id,:)], querySlot, 'linear')';
formal24 = max(formal24,0);
end

% PV动态融合

function pv24 = makeOfficialPV24Blend( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    w)
formal24 = makeFormalPV24(F,pvAll,dateAll,d,issueHour);
history24 = makeHistoryPV24(pvAll,d,issueHour);
pv24 = w*formal24 +(1-w)*history24;
pv24 = max(pv24,0);
end

% 前3日PV

function history24 = makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour)
paths = zeros(144,3);
for k = 1:3
    onePath = extractActual24(pvAll, d-k, issueHour);
    if isempty(onePath)
        error( ...
            '历史光伏路径不足。');
    end
    paths(:,k) = ...
        onePath;
end
history24 = mean(paths,2);
end

% 当前发布时间PV实际锚点

function value = observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour)
if issueHour==0
    value = pvAll(d-1,144);
else
    value = pvAll(d, issueHour*6);
end
end

% 提取连续未来24h真实路径

function path = extractActual24( ...
    data, ...
    d, ...
    issueHour)
startSlot = issueHour*6+1;
if issueHour==0
    path = data(d,:)';
elseif d<size(data,1)
    path = [ data(d,startSlot:end), data(d+1,1:startSlot-1) ]';
else
    path = [];
end
end

% 附件3读取

function F = readForecastSingleSheet( ...
    filename, ...
    sheetName)
C = readcell(filename, 'Sheet',sheetName);
[nRow,nCol] = ...
    size(C);
headerRow = NaN;
for r = 1:min(nRow,30)
    for c = 1:nCol
        txt = replace(strtrim(string(C{r,c})), " ","");
        if txt=="预报1小时" ...
                ||txt=="预测1小时"
            headerRow = r;
            break;
        end
    end
    if ~isnan(headerRow)
        break;
    end
end
if isnan(headerRow)
    error( ...
        '附件3找不到表头。');
end
dateCol = NaN;
issueCol = NaN;
for c = 1:nCol
    txt = replace(strtrim(string(C{headerRow,c})), " ","");
    if contains(txt,"日期")
        dateCol = c;
    end
    if contains(txt,"预报时刻") ...
            ||contains(txt,"预测时刻")
        issueCol = c;
    end
end
forecastCols = nan(1,24);
for h = 1:24
    for c = 1:nCol
        txt = replace(strtrim(string(C{headerRow,c})), " ","");
        if txt==sprintf('预报%d小时',h) ...
                ||txt==sprintf('预测%d小时',h)
            forecastCols(h) = ...
                c;
            break;
        end
    end
end
maxN = nRow-headerRow;
dates = NaT(maxN,1);
issueHour = nan(maxN,1);
forecast = nan(maxN,24);
count = 0;
currentDate = NaT;
for r = headerRow+1:nRow
    newDate = parseOneDate(C{r,dateCol});
    if ~isnat(newDate)
        currentDate = dateshift(newDate, 'start','day');
    end
    if isnat(currentDate)
        continue;
    end
    hIssue = parseIssueHour(C{r,issueCol});
    if isnan(hIssue) ...
            ||~ismember( ...
            hIssue,[0,6,12,18])
        continue;
    end
    vals = nan(1,24);
    for h = 1:24
        vals(h) = ...
            valueToDouble( ...
            C{r,forecastCols(h)});
    end
    if all(isnan(vals))
        continue;
    end
    count = count+1;
    dates(count) = ...
        currentDate;
    issueHour(count) = ...
        hIssue;
    forecast(count,:) = ...
        vals;
end
dates = dates(1:count);
issueHour = issueHour(1:count);
forecast = forecast(1:count,:);
T = table(dates, issueHour, (1:count)', 'VariableNames', {'Date','Hour','ID'});
T = sortrows(T, {'Date','Hour'});
id = T.ID;
F.dates = dates(id);
F.issueHour = issueHour(id);
F.forecast = forecast(id,:);
F.issueTime = F.dates +hours(F.issueHour);
end

% 日期解析

function d = parseOneDate(x)
d = NaT;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isdatetime(x)
    if ~isnat(x)
        d = x(1);
    end
    return;
end
if isnumeric(x)
    if isempty(x) ...
            ||isnan(x)
        return;
    end
    try
        d = datetime(x, 'ConvertFrom','excel');
        return;
    catch
    end
end
s = strtrim(string(x));
if ismissing(s) ...
        ||strlength(s)==0
    return;
end
try
    d = datetime(s);
catch
    d = NaT;
end
end

% 发布时间解析

function h = parseIssueHour(x)
h = NaN;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isduration(x)
    h = mod(round(hours(x)), 24);
    return;
end
if isdatetime(x)
    if ~isnat(x)
        h = hour(x);
    end
    return;
end
if isnumeric(x)
    if isempty(x) ...
            ||isnan(x)
        return;
    end
    if x>=0 ...
            &&x<1
        h = mod(round(24*x), 24);
        return;
    end
    if x>=0 ...
            &&x<=24
        h = round(x);
        if h==24
            h = 0;
        end
        return;
    end
end
s = strtrim(string(x));
token = regexp(char(s), '(\d{1,2})\s*:', 'tokens','once');
if ~isempty(token)
    h = mod(str2double(token{1}), 24);
end
end

function y = valueToDouble(x)
y = NaN;
if iscell(x)
    if isempty(x)
        return;
    end
    x = x{1};
end
if isnumeric(x)
    if ~isempty(x)
        y = double(x(1));
    end
    return;
end
if islogical(x)
    y = double(x);
    return;
end
s = strtrim(string(x));
if ismissing(s) ...
        ||strlength(s)==0
    return;
end
y = str2double(s);
end

% 0/6/12/18滚动实时电价缓存

function [ ...
    priceCache, ...
    diagTable, ...
    zeroHourMAE, ...
    blockMAE ...
    ] = ...
    buildRollingPriceForecastCache( ...
    priceAll, ...
    dateAll, ...
    targetDays, ...
    issueHours, ...
    kL, ...
    kS, ...
    useRollingUpdate)
nDay = length(targetDays);
priceCache = cell(nDay,4);
blockError = nan(nDay,4);
zeroPred = nan(nDay,144);
for kd = 1:nDay
    d = targetDays(kd);
    for ki = 1:4
        hIssue = issueHours(ki);
        p24 = makeRollingPrice24(priceAll, dateAll, d, hIssue, kL, kS, useRollingUpdate);
        priceCache{kd,ki} = ...
            p24(:);
        startSlot = hIssue*6+1;
        endSlot = min(startSlot+35, 144);
        nExec = endSlot-startSlot+1;
        realBlock = priceAll(d, startSlot:endSlot)';
        predBlock = p24(1:nExec);
        blockError(kd,ki) = ...
            mean( ...
            abs( ...
            predBlock-realBlock));
        if ki==1
            zeroPred(kd,:) = ...
                p24';
        end
    end
end
actualZero = priceAll(targetDays,:);
zeroHourMAE = mean(abs(zeroPred-actualZero), 'all');
blockMAE = mean(blockError, 1, 'omitnan');
diagTable = ...
    table( ...
    dateAll(targetDays), ...
    blockError(:,1), ...
    blockError(:,2), ...
    blockError(:,3), ...
    blockError(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'MAE_0to6', ...
    'MAE_6to12', ...
    'MAE_12to18', ...
    'MAE_18to24'} ...
    );
end

% 当前发布时间未来24h价格

function price24 = makeRollingPrice24( ...
    priceAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    kL, ...
    kS, ...
    useRollingUpdate)
[ ...
    todayBase, ...
    todayShape, ...
    ~ ...
    ] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    dateAll(d), ...
    d-1, ...
    kL, ...
    kS);
todayForecast = todayBase;

% 当前日滚动修正

if useRollingUpdate ...
        &&issueHour>0
    obsN = issueHour*6;
    observedPrice = priceAll(d,1:obsN)';
    observedShape = todayShape(1:obsN)';
    denom = sum(observedShape.^2);
    if denom>1e-12
        updatedLevel = sum(observedShape .*observedPrice) /denom;
        if isfinite(updatedLevel) ...
                &&updatedLevel>=0
            todayForecast = updatedLevel .*todayShape;
        end
    end
end
todayForecast = max(todayForecast,0);

% 次日预测

nextDate = dateAll(d) +days(1);
[nextForecast,~,~] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    nextDate, ...
    d-1, ...
    kL, ...
    kS);
startSlot = issueHour*6+1;
price24 = [ todayForecast(startSlot:end), nextForecast(1:startSlot-1) ]';
if length(price24)~=144
    error( ...
        '滚动价格长度错误。');
end
end

% 基础日价格预测

function [ ...
    forecastDay, ...
    shapeDay, ...
    levelDay ...
    ] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    targetDate, ...
    lastCompleteDay, ...
    kL, ...
    kS)
histDays = (1:lastCompleteDay)';
targetWeekday = weekday(targetDate);
histWeekday = weekday(dateAll(histDays));
sameWeekDays = histDays(histWeekday==targetWeekday);
if length(sameWeekDays)<max(kL,kS)
    error( ...
        '电价同星期历史不足。');
end
meanDays = sameWeekDays(end-kL+1:end);
levelDay = mean(mean(priceAll(meanDays,:), 2));
shapeDays = sameWeekDays(end-kS+1:end);
shapeMatrix = zeros(kS,144);
for k = 1:kS
    onePrice = priceAll(shapeDays(k),:);
    oneMean = mean(onePrice);
    if abs(oneMean)<1e-12
        error( ...
            '历史日均价格接近0。');
    end
    shapeMatrix(k,:) = ...
        onePrice ...
        /oneMean;
end
shapeDay = mean(shapeMatrix, 1);
forecastDay = max(levelDay .*shapeDay, 0);
end

% 紧急购电TIMEFIX

function txt = makeEmergencyTimeRangeQ43(s,e)
startMinute = 10*(s-1);
endMinute = 10*e;
txt = ...
    sprintf( ...
    '%s-%s', ...
    formatResultTimeQ43(startMinute), ...
    formatResultTimeQ43(endMinute));
end

function txt = formatResultTimeQ43(totalMinute)
dayAdd = floor(totalMinute/1440);
minuteOfDay = mod(totalMinute,1440);
hh = floor(minuteOfDay/60);
mm = mod(minuteOfDay,60);
if dayAdd==0
    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh,mm);
else
    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh,mm);
end
end
