%% ============================================================
% 2026 C题 问题2
%
% AS-Ridge负载 + AS-Ridge光伏
% 时间轴修正版测试
%
% 核心：
% 1) 不再使用 idx = [144,1:143]
% 2) 负载、光伏、预测、电价全部保持附件原始144列顺序
% 3) 最近30日净负荷残差Q0.8风险校准
% 4) 每日计划LP
% 5) 实际逐10min严格因果执行
% 6) 允许同时充放电
% 7) cyclePenalty = 0
% 8) 不强制年末SOC恢复6000
%
% 本代码当前只验证新时间轴下的成本，
% 暂时不覆盖官方result2.xlsx
%% ============================================================

clear;
clc;
close all;

rng(20260912,'twister');


fprintf('====================================================\n');
fprintf(' 问题2：AS-Ridge + AS-Ridge 时间轴修正版\n');
fprintf(' 原始144列顺序，不再旋转\n');
fprintf('====================================================\n\n');


%% ============================================================
% 0. 参数开关
%% ============================================================

FORCE_FINAL_SOC_6000 = ...
    false;

Q_LEVEL = ...
    0.80;

ROLLING_WINDOW_DAYS = ...
    30;

MIN_HISTORY_DAYS = ...
    7;


%% ============================================================
% 1. 路径
%% ============================================================

baseDir = ...
    'E:\数模\2026年正式比赛\CUMCM2026Problems\C题\附件';


actualFile = ...
    fullfile( ...
    baseDir, ...
    '附件2.xlsx');


priceFile = ...
    fullfile( ...
    baseDir, ...
    '附件1.xlsx');


predictionFile = ...
    fullfile( ...
    baseDir, ...
    'Q2_16combo_4models_predictions.mat');


matFile = ...
    fullfile( ...
    baseDir, ...
    'Q2_ASRidge_ASRidge_TIMEFIX_TEST.mat');


excelFile = ...
    fullfile( ...
    baseDir, ...
    'Q2_ASRidge_ASRidge_TIMEFIX_TEST.xlsx');


filesNeed = {
    actualFile
    priceFile
    predictionFile
    };


for i = 1:length(filesNeed)

    if ~isfile(filesNeed{i})

        error( ...
            '找不到文件：%s', ...
            filesNeed{i});

    end

end


%% ============================================================
% 2. 日期
%% ============================================================

datesAll = ...
    ( ...
    datetime(2025,1,1): ...
    days(1): ...
    datetime(2025,12,31) ...
    )';


targetDays = ...
    32:365;


predDates = ...
    datesAll(targetDays);


nDay = ...
    length(targetDays);


nTime = ...
    144;


%% ============================================================
% 3. 读取附件2
%
% 重要：
%
% 原始顺序直接保留：
%
% 0:10, 0:20, ..., 23:50, 0:00+1
%
% 不再做：
%
% idx = [144,1:143]
%% ============================================================

fprintf('读取附件2真实负载和光伏...\n');


loadRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','小区负载', ...
    'Range','B2:EO366');


pvRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','光伏发电实际功率', ...
    'Range','B2:EO366');


if ~isequal(size(loadRaw),[365,144])

    error('负载数据应为365×144。');

end


if ~isequal(size(pvRaw),[365,144])

    error('光伏数据应为365×144。');

end


if any(~isfinite(loadRaw),'all') ...
        || any(~isfinite(pvRaw),'all')

    error('附件2含NaN或非有限值。');

end


% ==========================================
% ★ 时间轴修正核心
% ==========================================

actualLoad = ...
    loadRaw(targetDays,:);


actualPV = ...
    pvRaw(targetDays,:);


%% ============================================================
% 4. 读取四模型预测
%% ============================================================

fprintf('读取四模型预测缓存...\n');


P = ...
    load(predictionFile);


required = {
    'predLoad'
    'predPV'
    'modelNames'
    };


for i = 1:length(required)

    if ~isfield(P,required{i})

        error( ...
            '预测文件缺少变量：%s', ...
            required{i});

    end

end


modelNames = ...
    string(P.modelNames(:));


asID = ...
    find( ...
    strcmpi(modelNames,'AS-Ridge'), ...
    1);


if isempty(asID)

    error('预测文件中找不到AS-Ridge。');

end


fprintf('AS-Ridge位于预测矩阵第%d层。\n',asID);


if ~isequal( ...
        size(P.predLoad), ...
        [nDay,nTime,4])

    error( ...
        'predLoad应为334×144×4。');

end


if ~isequal( ...
        size(P.predPV), ...
        [nDay,nTime,4])

    error( ...
        'predPV应为334×144×4。');

end


% ==========================================
% ★ 不旋转
% ==========================================

predLoad = ...
    P.predLoad(:,:,asID);


predPV = ...
    P.predPV(:,:,asID);


fprintf('负载模型：AS-Ridge\n');
fprintf('光伏模型：AS-Ridge\n');
fprintf('预测矩阵保持原始时间轴。\n\n');


%% ============================================================
% 5. 电价
%
% 同样保持原始顺序
%% ============================================================

fprintf('读取附件1电价...\n');


Tprice = ...
    readtable( ...
    priceFile, ...
    'VariableNamingRule','preserve');


price = ...
    Tprice{:,2};


price = ...
    price(:);


if length(price)~=144

    error('电价应为144个时段。');

end


if any(~isfinite(price)) ...
        || any(price<0)

    error('电价存在非法值。');

end


% ==========================================
% ★ 不再做：
%
% price = [priceRaw(end);priceRaw(1:end-1)]
% ==========================================


fprintf('电价保持附件1原始顺序。\n\n');


%% ============================================================
% 6. 原始净负荷预测
%% ============================================================

forecastNet = ...
    predLoad ...
    -predPV;


actualNet = ...
    actualLoad ...
    -actualPV;


%% ============================================================
% 7. 历史净负荷残差
%
% residual =
% actual net - forecast net
%% ============================================================

residualNet = ...
    actualNet ...
    -forecastNet;


%% ============================================================
% 8. 严格因果Q0.8校准
%% ============================================================

fprintf('计算Q0.8滚动风险校准...\n');


q80Correction = ...
    zeros(nDay,nTime);


calibrationActive = ...
    false(nDay,1);


historyDaysUsed = ...
    zeros(nDay,1);


for d = 1:nDay

    histEnd = ...
        d-1;


    histStart = ...
        max( ...
        1, ...
        d-ROLLING_WINDOW_DAYS);


    if histEnd<histStart

        continue;

    end


    nHist = ...
        histEnd-histStart+1;


    historyDaysUsed(d) = ...
        nHist;


    if nHist<MIN_HISTORY_DAYS

        continue;

    end


    calibrationActive(d) = ...
        true;


    for t = 1:nTime

        r = ...
            residualNet( ...
            histStart:histEnd, ...
            t);


        r = ...
            r(isfinite(r));


        if length(r)>=MIN_HISTORY_DAYS

            q80Correction(d,t) = ...
                quantile( ...
                r, ...
                Q_LEVEL);

        end

    end

end


correctedNet = ...
    forecastNet ...
    +q80Correction;


% PV预测保持不动，
% 将净负荷Q0.8修正量落实到负载侧
correctedLoad = ...
    correctedNet ...
    +predPV;


correctedLoad = ...
    max( ...
    correctedLoad, ...
    0);


%% ============================================================
% 9. Q0.8诊断
%% ============================================================

activeMask = ...
    repmat( ...
    calibrationActive, ...
    1,nTime);


qUse = ...
    q80Correction(activeMask);


if isempty(qUse)

    qMean = ...
        NaN;

    qMin = ...
        NaN;

    qMax = ...
        NaN;

else

    qMean = ...
        mean(qUse);

    qMin = ...
        min(qUse);

    qMax = ...
        max(qUse);

end


rawError = ...
    forecastNet ...
    -actualNet;


correctedError = ...
    correctedNet ...
    -actualNet;


fprintf('\n====================================================\n');
fprintf(' Q0.8风险校准\n');
fprintf('====================================================\n');

fprintf( ...
    '启用校准：%d/%d天\n', ...
    sum(calibrationActive), ...
    nDay);


if any(calibrationActive)

    firstActive = ...
        find( ...
        calibrationActive, ...
        1);

    fprintf( ...
        '首次启用：%s\n', ...
        string(predDates(firstActive)));

end


fprintf('Q0.8均值：%.4f kW\n',qMean);
fprintf('Q0.8最小：%.4f kW\n',qMin);
fprintf('Q0.8最大：%.4f kW\n',qMax);

fprintf( ...
    '原始净负荷MAE：%.4f kW\n', ...
    mean(abs(rawError),'all'));

fprintf( ...
    '校准后净负荷MAE：%.4f kW\n', ...
    mean(abs(correctedError),'all'));

fprintf( ...
    '原始净负荷Bias：%.4f kW\n', ...
    mean(rawError,'all'));

fprintf( ...
    '校准后净负荷Bias：%.4f kW\n', ...
    mean(correctedError,'all'));

fprintf('====================================================\n\n');


%% ============================================================
% 10. 储能参数
%% ============================================================

dt = ...
    10/60;


eta_ch = ...
    0.90;


eta_dis = ...
    0.90;


Ecapacity = ...
    12000;


Emin = ...
    1200;


Emax = ...
    10800;


Einitial = ...
    6000;


EfinalTarget = ...
    6000;


Pmax = ...
    5000;


Wmax = ...
    Pmax*dt;


emergencyFactor = ...
    5;


% 当前实验：
% 完全取消充放电循环惩罚
cyclePenalty = ...
    0;


curtailPenalty = ...
    1e-5;


%% ============================================================
% 11. LP
%% ============================================================

lpOptions = ...
    optimoptions( ...
    'linprog', ...
    'Algorithm','dual-simplex-highs', ...
    'Display','none');


%% ============================================================
% 12. 初始化
%% ============================================================

planGrid = ...
    zeros(nDay,nTime);


planCharge = ...
    zeros(nDay,nTime);


planDischarge = ...
    zeros(nDay,nTime);


planCurtail = ...
    zeros(nDay,nTime);


actualCharge = ...
    zeros(nDay,nTime);


actualDischarge = ...
    zeros(nDay,nTime);


actualSpill = ...
    zeros(nDay,nTime);


emergencyGrid = ...
    zeros(nDay,nTime);


SOCstart = ...
    zeros(nDay,1);


SOCend = ...
    zeros(nDay,1);


actualSOC = ...
    zeros(nDay,nTime+1);


planCostDay = ...
    zeros(nDay,1);


emergencyCostDay = ...
    zeros(nDay,1);


totalCostDay = ...
    zeros(nDay,1);


%% ============================================================
% 13. 全年逐日执行
%% ============================================================

fprintf('开始全年调度...\n\n');


Ecurrent = ...
    Einitial;


timerMain = ...
    tic;


for d = 1:nDay

    if mod(d-1,20)==0 ...
            || d==nDay

        fprintf( ...
            '[%03d/%03d] %s  SOC=%.2f\n', ...
            d, ...
            nDay, ...
            string(predDates(d)), ...
            Ecurrent);

    end


    EdayStart = ...
        Ecurrent;


    SOCstart(d) = ...
        EdayStart;


    isLastDay = ...
        d==nDay;


    if isLastDay ...
            && FORCE_FINAL_SOC_6000

        terminalLow = ...
            EfinalTarget;

        terminalHigh = ...
            EfinalTarget;

    else

        terminalLow = ...
            Emin;

        terminalHigh = ...
            Emax;

    end


    %% --------------------------------------------------------
    % 当日预测
    %% --------------------------------------------------------

    loadForecast = ...
        correctedLoad(d,:)';


    pvForecast = ...
        predPV(d,:)';


    %% --------------------------------------------------------
    % 日前计划LP
    %% --------------------------------------------------------

    plan = ...
        solveDailyPlanTerminalSOC( ...
        loadForecast, ...
        pvForecast, ...
        price, ...
        EdayStart, ...
        terminalLow, ...
        terminalHigh, ...
        dt, ...
        eta_ch, ...
        eta_dis, ...
        Emin, ...
        Emax, ...
        Wmax, ...
        cyclePenalty, ...
        curtailPenalty, ...
        lpOptions);


    planGrid(d,:) = ...
        plan.Wgrid';


    planCharge(d,:) = ...
        plan.Wch';


    planDischarge(d,:) = ...
        plan.Wdis';


    planCurtail(d,:) = ...
        plan.Wcut';


    planCostDay(d) = ...
        sum( ...
        price ...
        .*plan.Wgrid);


    %% --------------------------------------------------------
    % 当前日真实数据
    %% --------------------------------------------------------

    loadActual = ...
        actualLoad(d,:)';


    pvActual = ...
        actualPV(d,:)';


    %% --------------------------------------------------------
    % 严格因果实际执行
    %% --------------------------------------------------------

    replay = ...
        replayActualDayCausalAllowSimultaneous( ...
        loadActual, ...
        pvActual, ...
        plan.Wgrid, ...
        plan.Wch, ...
        plan.Wdis, ...
        EdayStart, ...
        dt, ...
        eta_ch, ...
        eta_dis, ...
        Emin, ...
        Emax, ...
        Wmax, ...
        isLastDay ...
            && FORCE_FINAL_SOC_6000, ...
        EfinalTarget);


    actualCharge(d,:) = ...
        replay.Wch';


    actualDischarge(d,:) = ...
        replay.Wdis';


    actualSpill(d,:) = ...
        replay.Wspill';


    emergencyGrid(d,:) = ...
        replay.Wem';


    actualSOC(d,:) = ...
        replay.E';


    Ecurrent = ...
        replay.Eend;


    SOCend(d) = ...
        Ecurrent;


    emergencyCostDay(d) = ...
        sum( ...
        emergencyFactor ...
        .*price ...
        .*replay.Wem);


    totalCostDay(d) = ...
        planCostDay(d) ...
        +emergencyCostDay(d);

end


runtime = ...
    toc(timerMain);


%% ============================================================
% 14. 结果
%% ============================================================

totalPlanEnergy = ...
    sum(planGrid,'all');


totalEmergencyEnergy = ...
    sum(emergencyGrid,'all');


totalPlanCost = ...
    sum(planCostDay);


totalEmergencyCost = ...
    sum(emergencyCostDay);


totalCost = ...
    totalPlanCost ...
    +totalEmergencyCost;


totalPlanCurtail = ...
    sum(planCurtail,'all');


totalActualSpill = ...
    sum(actualSpill,'all');


totalCharge = ...
    sum(actualCharge,'all');


totalDischarge = ...
    sum(actualDischarge,'all');


emergencyDays = ...
    sum( ...
    any( ...
    emergencyGrid>1e-8, ...
    2));


emergencySlots = ...
    nnz( ...
    emergencyGrid>1e-8);


planSimultaneousSlots = ...
    nnz( ...
    planCharge>1e-8 ...
    &planDischarge>1e-8);


actualSimultaneousSlots = ...
    nnz( ...
    actualCharge>1e-8 ...
    &actualDischarge>1e-8);


allSOC = ...
    actualSOC(:,2:end);


if any(allSOC<Emin-1e-5,'all') ...
        || any(allSOC>Emax+1e-5,'all')

    error('实际SOC存在越界。');

end


%% ============================================================
% 15. 输出
%% ============================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf(' AS-Ridge + AS-Ridge 时间轴修正版结果\n');
fprintf('====================================================\n');

fprintf( ...
    '全年计划购电量：%.2f kWh\n', ...
    totalPlanEnergy);

fprintf( ...
    '全年计划购电费：%.2f 元\n', ...
    totalPlanCost);

fprintf('\n');

fprintf( ...
    '全年紧急购电量：%.2f kWh\n', ...
    totalEmergencyEnergy);

fprintf( ...
    '全年紧急购电费：%.2f 元\n', ...
    totalEmergencyCost);

fprintf('\n');

fprintf( ...
    '全年总成本：%.2f 元\n', ...
    totalCost);

fprintf('\n');

fprintf( ...
    '计划未利用光伏：%.2f kWh\n', ...
    totalPlanCurtail);

fprintf( ...
    '实际未利用富余电量：%.2f kWh\n', ...
    totalActualSpill);

fprintf('\n');

fprintf( ...
    '实际充电量：%.2f kWh\n', ...
    totalCharge);

fprintf( ...
    '实际放电量：%.2f kWh\n', ...
    totalDischarge);

fprintf('\n');

fprintf( ...
    '紧急购电天数：%d\n', ...
    emergencyDays);

fprintf( ...
    '紧急购电时段：%d\n', ...
    emergencySlots);

fprintf('\n');

fprintf( ...
    '计划同时充放电时段：%d\n', ...
    planSimultaneousSlots);

fprintf( ...
    '实际同时充放电时段：%d\n', ...
    actualSimultaneousSlots);

fprintf('\n');

fprintf( ...
    '最终SOC：%.6f kWh\n', ...
    SOCend(end));

fprintf( ...
    '最低SOC：%.6f kWh\n', ...
    min(allSOC,[],'all'));

fprintf( ...
    '最高SOC：%.6f kWh\n', ...
    max(allSOC,[],'all'));

fprintf('\n');

fprintf( ...
    '运行时间：%.2f min\n', ...
    runtime/60);

fprintf('====================================================\n');

%% ============================================================
% 15.5 写入官方附件5/result2.xlsx
%
% 注意：
% 当前时间轴已经修正为附件原始144列顺序，
% 因此 planGrid 直接写入，不再做任何循环移位。
%% ============================================================

fprintf('\n开始写入官方 result2.xlsx...\n');

result2File = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    'result2.xlsx');


if ~isfile(result2File)

    error( ...
        '找不到官方模板：%s', ...
        result2File);

end


%% ------------------------------------------------------------
% 0. 备份原result2
%% ------------------------------------------------------------

backupFile = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    ['result2_backup_', ...
    char(datetime('now','Format','yyyyMMdd_HHmmss')), ...
    '.xlsx']);


copyfile( ...
    result2File, ...
    backupFile);


fprintf('原result2已备份：\n%s\n',backupFile);


%% ============================================================
% 1. 计划购电量
%
% B:EO = 144个10min时段
% EP   = 全天购电量
% EQ   = 全天购电费
%
% ★ 时间轴修正后：
% planGrid直接写！
% 不再使用：
% [planGrid(:,2:end),planGrid(:,1)]
%% ============================================================

planOut = ...
    planGrid;


dailyPlanEnergy = ...
    sum( ...
    planGrid, ...
    2);


% 144个时段
writematrix( ...
    planOut, ...
    result2File, ...
    'Sheet','计划购电量', ...
    'Range','B2');


% 全天购电量
writematrix( ...
    dailyPlanEnergy, ...
    result2File, ...
    'Sheet','计划购电量', ...
    'Range','EP2');


% 全天购电费
writematrix( ...
    planCostDay, ...
    result2File, ...
    'Sheet','计划购电量', ...
    'Range','EQ2');


fprintf('计划购电量写入完成。\n');


%% ============================================================
% 2. 充放电量
%
% 每天划分为6个连续4h区间，
% 每个区间24个10min点。
%
% 当前内部顺序与附件原始顺序完全一致，
% 因此直接每24列统计一次。
%% ============================================================

nBlock = ...
    6;


charge4h = ...
    zeros(nDay,nBlock);


discharge4h = ...
    zeros(nDay,nBlock);


socBlockStart = ...
    zeros(nDay,nBlock);


socBlockEnd = ...
    zeros(nDay,nBlock);


for d = 1:nDay

    for b = 1:nBlock

        s1 = ...
            (b-1)*24+1;

        s2 = ...
            b*24;


        charge4h(d,b) = ...
            sum( ...
            actualCharge(d,s1:s2));


        discharge4h(d,b) = ...
            sum( ...
            actualDischarge(d,s1:s2));


        % actualSOC的第1列是当天执行前SOC
        socBlockStart(d,b) = ...
            actualSOC(d,s1);


        socBlockEnd(d,b) = ...
            actualSOC(d,s2+1);

    end

end


% 按：
% 第1天6行
% 第2天6行
% ...
% 展开
chargeOut = ...
    reshape( ...
    charge4h', ...
    [],1);


dischargeOut = ...
    reshape( ...
    discharge4h', ...
    [],1);


socStartOut = ...
    reshape( ...
    socBlockStart', ...
    [],1);


socEndOut = ...
    reshape( ...
    socBlockEnd', ...
    [],1);


%% ------------------------------------------------------------
% 自动读取模板表头，找到对应列
%% ------------------------------------------------------------

cdHeader = ...
    readcell( ...
    result2File, ...
    'Sheet','充放电量', ...
    'Range','A1:Z3');


chargeCol = ...
    findHeaderColumn( ...
    cdHeader, ...
    {'充电量','充电'});


dischargeCol = ...
    findHeaderColumn( ...
    cdHeader, ...
    {'放电量','放电'});


socStartCol = ...
    findHeaderColumn( ...
    cdHeader, ...
    {'初始储电量','期初储电量','开始储电量','初始SOC'});


socEndCol = ...
    findHeaderColumn( ...
    cdHeader, ...
    {'结束储电量','期末储电量','最终储电量','结束SOC','储电量'});


if ~isempty(chargeCol)

    writematrix( ...
        chargeOut, ...
        result2File, ...
        'Sheet','充放电量', ...
        'Range',[excelColumnName(chargeCol),'2']);

end


if ~isempty(dischargeCol)

    writematrix( ...
        dischargeOut, ...
        result2File, ...
        'Sheet','充放电量', ...
        'Range',[excelColumnName(dischargeCol),'2']);

end


if ~isempty(socStartCol)

    writematrix( ...
        socStartOut, ...
        result2File, ...
        'Sheet','充放电量', ...
        'Range',[excelColumnName(socStartCol),'2']);

end


if ~isempty(socEndCol)

    writematrix( ...
        socEndOut, ...
        result2File, ...
        'Sheet','充放电量', ...
        'Range',[excelColumnName(socEndCol),'2']);

end


fprintf('充放电量写入完成。\n');


%% ============================================================
% 3. 紧急购电量
%
% 将同一天连续发生的紧急购电时段合并为一个区间。
%
% 当前144列：
%
% 第1列：0:10
% ...
% 第143列：23:50
% 第144列：0:00+1
%% ============================================================

emergencyDate = ...
    strings(0,1);


emergencyRange = ...
    strings(0,1);


emergencyEnergy = ...
    zeros(0,1);


for d = 1:nDay

    x = ...
        emergencyGrid(d,:);


    active = ...
        x>1e-8;


    if ~any(active)

        continue;

    end


    % 找连续区间起止位置
    edge = ...
        diff( ...
        [false,active,false]);


    starts = ...
        find(edge==1);


    ends = ...
        find(edge==-1)-1;


    for k = 1:length(starts)

        s = ...
            starts(k);


        e = ...
            ends(k);


        emergencyDate(end+1,1) = ...
            string( ...
            predDates(d), ...
            'yyyy-MM-dd');


        emergencyRange(end+1,1) = ...
            makeEmergencyTimeRange( ...
            s,e);


        emergencyEnergy(end+1,1) = ...
            sum( ...
            x(s:e));

    end

end


%% ------------------------------------------------------------
% 根据模板表头自动找列
%% ------------------------------------------------------------

emHeader = ...
    readcell( ...
    result2File, ...
    'Sheet','紧急购电量', ...
    'Range','A1:Z3');


dateCol = ...
    findHeaderColumn( ...
    emHeader, ...
    {'日期'});


timeCol = ...
    findHeaderColumn( ...
    emHeader, ...
    {'时间段','时间区间','时段','时间'});


energyCol = ...
    findHeaderColumn( ...
    emHeader, ...
    {'紧急购电量','购电量'});


if isempty(dateCol) ...
        || isempty(timeCol) ...
        || isempty(energyCol)

    warning( ...
        ['无法自动识别紧急购电量工作表的全部表头。', ...
         '请检查result2模板。']);

else

    writecell( ...
        cellstr(emergencyDate), ...
        result2File, ...
        'Sheet','紧急购电量', ...
        'Range',[excelColumnName(dateCol),'2']);


    writecell( ...
        cellstr(emergencyRange), ...
        result2File, ...
        'Sheet','紧急购电量', ...
        'Range',[excelColumnName(timeCol),'2']);


    writematrix( ...
        emergencyEnergy, ...
        result2File, ...
        'Sheet','紧急购电量', ...
        'Range',[excelColumnName(energyCol),'2']);

end


fprintf('紧急购电量写入完成。\n');


fprintf('\n====================================================\n');
fprintf(' result2.xlsx 写入完成\n');
fprintf(' 文件：%s\n',result2File);
fprintf('====================================================\n');
%% ============================================================
% 16. 保存结果
%% ============================================================

summaryTable = ...
    table( ...
    "AS-Ridge", ...
    "AS-Ridge", ...
    totalPlanEnergy, ...
    totalPlanCost, ...
    totalEmergencyEnergy, ...
    totalEmergencyCost, ...
    totalCost, ...
    totalPlanCurtail, ...
    totalActualSpill, ...
    totalCharge, ...
    totalDischarge, ...
    emergencyDays, ...
    emergencySlots, ...
    planSimultaneousSlots, ...
    actualSimultaneousSlots, ...
    SOCend(end), ...
    qMean, ...
    'VariableNames',{ ...
    'LoadModel', ...
    'PVModel', ...
    'PlanEnergy_kWh', ...
    'PlanCost_Yuan', ...
    'EmergencyEnergy_kWh', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'PlanCurtail_kWh', ...
    'ActualSpill_kWh', ...
    'ChargeEnergy_kWh', ...
    'DischargeEnergy_kWh', ...
    'EmergencyDays', ...
    'EmergencySlots', ...
    'PlanSimultaneousSlots', ...
    'ActualSimultaneousSlots', ...
    'FinalSOC_kWh', ...
    'Q80Mean_kW'});


dailyTable = ...
    table( ...
    predDates, ...
    SOCstart, ...
    SOCend, ...
    planCostDay, ...
    emergencyCostDay, ...
    totalCostDay, ...
    sum(emergencyGrid,2), ...
    'VariableNames',{ ...
    'Date', ...
    'SOCstart_kWh', ...
    'SOCend_kWh', ...
    'PlanCost_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'EmergencyEnergy_kWh'});


if isfile(excelFile)

    delete(excelFile);

end


writetable( ...
    summaryTable, ...
    excelFile, ...
    'Sheet','汇总');


writetable( ...
    dailyTable, ...
    excelFile, ...
    'Sheet','每日结果');


save( ...
    matFile, ...
    'summaryTable', ...
    'dailyTable', ...
    'predDates', ...
    'predLoad', ...
    'predPV', ...
    'actualLoad', ...
    'actualPV', ...
    'correctedLoad', ...
    'correctedNet', ...
    'q80Correction', ...
    'calibrationActive', ...
    'planGrid', ...
    'planCharge', ...
    'planDischarge', ...
    'planCurtail', ...
    'actualCharge', ...
    'actualDischarge', ...
    'actualSpill', ...
    'emergencyGrid', ...
    'actualSOC', ...
    'SOCstart', ...
    'SOCend', ...
    'planCostDay', ...
    'emergencyCostDay', ...
    'totalCostDay', ...
    'totalCost', ...
    'runtime', ...
    '-v7.3');


fprintf('\n测试结果已保存：\n');
fprintf('%s\n',excelFile);
fprintf('%s\n',matFile);


%% ============================================================
% 局部函数1：
% 日前计划LP
%% ============================================================

function plan = solveDailyPlanTerminalSOC( ...
    Pload, ...
    Pv, ...
    price, ...
    Estart, ...
    terminalLow, ...
    terminalHigh, ...
    dt, ...
    eta_ch, ...
    eta_dis, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)


N = ...
    length(price);


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Pv(:)*dt;


price = ...
    price(:);


%% 变量

idxGrid = ...
    1:N;


idxCh = ...
    N+(1:N);


idxDis = ...
    2*N+(1:N);


idxCut = ...
    3*N+(1:N);


idxE = ...
    4*N+(1:N+1);


nVar = ...
    5*N+1;


%% 目标函数

f = ...
    zeros(nVar,1);


f(idxGrid) = ...
    price;


f(idxCh) = ...
    cyclePenalty;


f(idxDis) = ...
    cyclePenalty;


f(idxCut) = ...
    curtailPenalty;


%% 等式约束

Aeq = ...
    zeros( ...
    2*N+1, ...
    nVar);


beq = ...
    zeros( ...
    2*N+1, ...
    1);


% ------------------------------------------------------------
% 电量平衡
%
% grid + PV + discharge
% =
% load + charge + curtail
% ------------------------------------------------------------

for t = 1:N

    Aeq(t,idxGrid(t)) = ...
        1;


    Aeq(t,idxCh(t)) = ...
        -1;


    Aeq(t,idxDis(t)) = ...
        1;


    Aeq(t,idxCut(t)) = ...
        -1;


    beq(t) = ...
        Wload(t) ...
        -Wpv(t);

end


% ------------------------------------------------------------
% SOC
% ------------------------------------------------------------

for t = 1:N

    r = ...
        N+t;


    Aeq(r,idxE(t)) = ...
        -1;


    Aeq(r,idxE(t+1)) = ...
        1;


    Aeq(r,idxCh(t)) = ...
        -eta_ch;


    Aeq(r,idxDis(t)) = ...
        1/eta_dis;

end


% 日初SOC
Aeq(2*N+1,idxE(1)) = ...
    1;


beq(2*N+1) = ...
    Estart;


%% 上下界

lb = ...
    zeros(nVar,1);


ub = ...
    inf(nVar,1);


% 单时段最大充电
ub(idxCh) = ...
    Wmax;


% 单时段最大放电
ub(idxDis) = ...
    Wmax;


% 弃光上限
ub(idxCut) = ...
    Wpv;


% SOC
lb(idxE) = ...
    Emin;


ub(idxE) = ...
    Emax;


lb(idxE(end)) = ...
    terminalLow;


ub(idxE(end)) = ...
    terminalHigh;


%% 求解

[x,~,exitflag,output] = ...
    linprog( ...
    f, ...
    [],[], ...
    Aeq,beq, ...
    lb,ub, ...
    options);


if exitflag<=0

    error( ...
        '计划LP失败：%s', ...
        output.message);

end


plan.Wgrid = ...
    x(idxGrid);


plan.Wch = ...
    x(idxCh);


plan.Wdis = ...
    x(idxDis);


plan.Wcut = ...
    x(idxCut);


plan.E = ...
    x(idxE);

end


%% ============================================================
% 局部函数2：
% 实际逐10min严格因果执行
%
% 允许同时充放电
%% ============================================================

function replay = replayActualDayCausalAllowSimultaneous( ...
    Pload, ...
    Pv, ...
    Wgrid, ...
    WchPlan, ...
    WdisPlan, ...
    Estart, ...
    dt, ...
    eta_ch, ...
    eta_dis, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    forceFinalSOC, ...
    EfinalTarget)


N = ...
    length(Wgrid);


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Pv(:)*dt;


Wgrid = ...
    Wgrid(:);


WchPlan = ...
    WchPlan(:);


WdisPlan = ...
    WdisPlan(:);


Wch = ...
    zeros(N,1);


Wdis = ...
    zeros(N,1);


Wspill = ...
    zeros(N,1);


Wem = ...
    zeros(N,1);


E = ...
    zeros(N+1,1);


E(1) = ...
    Estart;


for t = 1:N

    Ecurrent = ...
        E(t);


    %% --------------------------------------------------------
    % 下一时刻SOC允许范围
    %% --------------------------------------------------------

    EnextLow = ...
        Emin;


    EnextHigh = ...
        Emax;


    %% --------------------------------------------------------
    % 如果最后一天强制SOC=6000，
    % 仅通过可达区间限制当前SOC
    %% --------------------------------------------------------

    if forceFinalSOC

        remainingSlots = ...
            N-t;


        reachLow = ...
            EfinalTarget ...
            -remainingSlots ...
            *eta_ch ...
            *Wmax;


        reachHigh = ...
            EfinalTarget ...
            +remainingSlots ...
            *Wmax/eta_dis;


        EnextLow = ...
            max( ...
            Emin, ...
            reachLow);


        EnextHigh = ...
            min( ...
            Emax, ...
            reachHigh);


        if EnextLow>EnextHigh+1e-7

            error( ...
                '终端SOC不可达：t=%d', ...
                t);

        end

    end


    %% --------------------------------------------------------
    % 先保留计划充放电动作
    %% --------------------------------------------------------

    WchNow = ...
        min( ...
        max(WchPlan(t),0), ...
        Wmax);


    WdisNow = ...
        min( ...
        max(WdisPlan(t),0), ...
        Wmax);


    EnextCandidate = ...
        Ecurrent ...
        +eta_ch*WchNow ...
        -WdisNow/eta_dis;


    %% --------------------------------------------------------
    % 先确保计划动作本身不会造成SOC越界
    %% --------------------------------------------------------

    if EnextCandidate<EnextLow

        needSOC = ...
            EnextLow ...
            -EnextCandidate;


        reduceDis = ...
            min( ...
            WdisNow, ...
            needSOC*eta_dis);


        WdisNow = ...
            WdisNow ...
            -reduceDis;


        EnextCandidate = ...
            Ecurrent ...
            +eta_ch*WchNow ...
            -WdisNow/eta_dis;


        if EnextCandidate<EnextLow-1e-10

            addCh = ...
                min( ...
                Wmax-WchNow, ...
                (EnextLow-EnextCandidate)/eta_ch);


            WchNow = ...
                WchNow ...
                +addCh;


            EnextCandidate = ...
                Ecurrent ...
                +eta_ch*WchNow ...
                -WdisNow/eta_dis;

        end

    end


    if EnextCandidate>EnextHigh

        needSOC = ...
            EnextCandidate ...
            -EnextHigh;


        reduceCh = ...
            min( ...
            WchNow, ...
            needSOC/eta_ch);


        WchNow = ...
            WchNow ...
            -reduceCh;


        EnextCandidate = ...
            Ecurrent ...
            +eta_ch*WchNow ...
            -WdisNow/eta_dis;


        if EnextCandidate>EnextHigh+1e-10

            addDis = ...
                min( ...
                Wmax-WdisNow, ...
                (EnextCandidate-EnextHigh)*eta_dis);


            WdisNow = ...
                WdisNow ...
                +addDis;


            EnextCandidate = ...
                Ecurrent ...
                +eta_ch*WchNow ...
                -WdisNow/eta_dis;

        end

    end


    %% --------------------------------------------------------
    % 当前真实供需相对计划储能动作的残差
    %
    % 正值 = 缺电
    % 负值 = 富余
    %% --------------------------------------------------------

    batteryNet = ...
        WdisNow ...
        -WchNow;


    requiredBatteryNet = ...
        Wload(t) ...
        -Wpv(t) ...
        -Wgrid(t);


    residual = ...
        requiredBatteryNet ...
        -batteryNet;


    %% ========================================================
    % 缺电
    %% ========================================================

    if residual>1e-12

        % -----------------------------------------------------
        % 1. 先减少当前充电
        % -----------------------------------------------------

        maxReduceChargeSOC = ...
            max( ...
            (EnextCandidate-EnextLow)/eta_ch, ...
            0);


        reduceCharge = ...
            min( ...
            [ ...
            residual, ...
            WchNow, ...
            maxReduceChargeSOC ...
            ]);


        WchNow = ...
            WchNow ...
            -reduceCharge;


        residual = ...
            residual ...
            -reduceCharge;


        EnextCandidate = ...
            EnextCandidate ...
            -eta_ch*reduceCharge;


        % -----------------------------------------------------
        % 2. 再增加放电
        % -----------------------------------------------------

        if residual>1e-12

            maxExtraDisSOC = ...
                eta_dis ...
                *max( ...
                EnextCandidate-EnextLow, ...
                0);


            maxExtraDis = ...
                min( ...
                Wmax-WdisNow, ...
                maxExtraDisSOC);


            extraDis = ...
                min( ...
                residual, ...
                maxExtraDis);


            WdisNow = ...
                WdisNow ...
                +extraDis;


            residual = ...
                residual ...
                -extraDis;


            EnextCandidate = ...
                EnextCandidate ...
                -extraDis/eta_dis;

        end


        % -----------------------------------------------------
        % 3. 剩余缺口紧急购电
        % -----------------------------------------------------

        Wem(t) = ...
            max( ...
            residual, ...
            0);


        Wspill(t) = ...
            0;


    %% ========================================================
    % 富余
    %% ========================================================

    elseif residual<-1e-12

        surplus = ...
            -residual;


        % -----------------------------------------------------
        % 1. 先减少当前放电
        % -----------------------------------------------------

        maxReduceDisSOC = ...
            eta_dis ...
            *max( ...
            EnextHigh-EnextCandidate, ...
            0);


        reduceDis = ...
            min( ...
            [ ...
            surplus, ...
            WdisNow, ...
            maxReduceDisSOC ...
            ]);


        WdisNow = ...
            WdisNow ...
            -reduceDis;


        surplus = ...
            surplus ...
            -reduceDis;


        EnextCandidate = ...
            EnextCandidate ...
            +reduceDis/eta_dis;


        % -----------------------------------------------------
        % 2. 再增加充电
        % -----------------------------------------------------

        if surplus>1e-12

            maxExtraChargeSOC = ...
                max( ...
                EnextHigh-EnextCandidate, ...
                0) ...
                /eta_ch;


            maxExtraCharge = ...
                min( ...
                Wmax-WchNow, ...
                maxExtraChargeSOC);


            extraCharge = ...
                min( ...
                surplus, ...
                maxExtraCharge);


            WchNow = ...
                WchNow ...
                +extraCharge;


            surplus = ...
                surplus ...
                -extraCharge;


            EnextCandidate = ...
                EnextCandidate ...
                +eta_ch*extraCharge;

        end


        % -----------------------------------------------------
        % 3. 剩余记为实际未利用富余电量
        % -----------------------------------------------------

        Wspill(t) = ...
            max( ...
            surplus, ...
            0);


        Wem(t) = ...
            0;


    else

        Wem(t) = ...
            0;


        Wspill(t) = ...
            0;

    end


    %% --------------------------------------------------------
    % 保存
    %% --------------------------------------------------------

    Wch(t) = ...
        WchNow;


    Wdis(t) = ...
        WdisNow;


    E(t+1) = ...
        Ecurrent ...
        +eta_ch*Wch(t) ...
        -Wdis(t)/eta_dis;


    if abs(E(t+1)-Emin)<1e-9

        E(t+1) = ...
            Emin;

    end


    if abs(E(t+1)-Emax)<1e-9

        E(t+1) = ...
            Emax;

    end


    if E(t+1)<EnextLow-1e-6 ...
            || E(t+1)>EnextHigh+1e-6

        error( ...
            ['实际回放SOC越界：', ...
             't=%d, E=%.6f, 合法范围=[%.6f,%.6f]'], ...
            t, ...
            E(t+1), ...
            EnextLow, ...
            EnextHigh);

    end

end


if forceFinalSOC ...
        && abs(E(end)-EfinalTarget)>1e-4

    error( ...
        '最终SOC未达到目标：%.6f', ...
        E(end));

end


replay.Wch = ...
    Wch;


replay.Wdis = ...
    Wdis;


replay.Wspill = ...
    Wspill;


replay.Wem = ...
    Wem;


replay.E = ...
    E;


replay.Eend = ...
    E(end);

end
%% ============================================================
% 辅助函数1：根据表头文字寻找Excel列号
%% ============================================================

function col = findHeaderColumn(C,keywords)

col = [];

[nr,nc] = size(C);

for j = 1:nc

    txt = "";

    for i = 1:nr

        one = ...
            string(C{i,j});

        if ~ismissing(one)

            txt = ...
                txt + one;

        end

    end

    txt = ...
        replace( ...
        txt, ...
        " ", ...
        "");


    for k = 1:length(keywords)

        if contains( ...
                txt, ...
                string(keywords{k}))

            col = ...
                j;

            return;

        end

    end

end

end


%% ============================================================
% 辅助函数2：数字列号转Excel列名
%
% 1  -> A
% 26 -> Z
% 27 -> AA
%% ============================================================

function name = excelColumnName(n)

name = '';

while n>0

    r = ...
        mod(n-1,26);

    name = ...
        [char(65+r),name];

    n = ...
        floor((n-1)/26);

end

end


%% ============================================================
% 辅助函数3：紧急购电连续时段转文字
%
% 当前原始时间轴：
% slot1   = 0:10
% slot2   = 0:20
% ...
% slot143 = 23:50
% slot144 = 0:00+1
%% ============================================================

function txt = makeEmergencyTimeRange(s,e)

startMin = ...
    10*s;


endMin = ...
    10*(e+1);


txt = ...
    sprintf( ...
    '%s-%s', ...
    formatMinuteLabel(startMin), ...
    formatMinuteLabel(endMin));

end


%% ============================================================
% 辅助函数4：分钟数转时间字符串
%% ============================================================

function txt = formatMinuteLabel(m)

dayAdd = ...
    floor(m/1440);


m0 = ...
    mod(m,1440);


hh = ...
    floor(m0/60);


mm = ...
    mod(m0,60);


if dayAdd==0

    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh,mm);

else

    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh,mm);

end

end