%% ============================================================
% 2026 C题 问题3 最终版
%
% Read Q2 MAT
% + AS-Ridge基础负载预测（直接读取问题2结果，不重新训练）
% + 附件3四时次光伏动态融合
% + Similar10历史残差情景
% + Causal Affine Recourse
% + 24h滚动优化 / 6h执行
% + TIMEFIX
% + 官方 result3.xlsx 输出
%
% ============================================================
%
% 问题2输出文件：
%
% Q2_P2_SIMILAR10_RESULT2_FINAL.mat
%
% 要求至少包含：
%
% predLoad   334×144
% predDates  334×1
%
% ============================================================
%
% TIMEFIX
%
% 附件2原始144列直接使用：
%
% col1   = 00:10
% col36  = 06:00
% col37  = 06:10
% col72  = 12:00
% col73  = 12:10
% col108 = 18:00
% col109 = 18:10
% col144 = 次日00:00
%
% 绝不使用 [144,1:143] 循环移位。
%
% ============================================================
%
% 问题3流程
%
% 问题2 AS-Ridge负载预测
%        ↓
% 附件3正式PV预报
%        ↓
% 正式预报 + 前3日历史PV动态融合
%        ↓
% 最近30条已结束的同发布时间历史记录
%        ↓
% 根据“负载预测 + PV预测”寻找10个最相似历史日
%        ↓
% 直接保留10条真实净负荷残差路径
%        ↓
% Similar10 causal affine recourse
%        ↓
% 每次优化未来24h
%        ↓
% 仅执行未来6h
%        ↓
% 6/12/18时重新预测、重新选相似日、重新优化
%
% ============================================================

clear;
clc;
close all;

rng(20260912,'twister');


fprintf('====================================================\n');
fprintf(' 问题3 Similar10 + Causal Affine\n');
fprintf(' 直接读取问题2预测结果\n');
fprintf(' TIMEFIX + result3.xlsx\n');
fprintf('====================================================\n\n');


%% ============================================================
% 1. 路径
%% ============================================================

baseDir = ...
    'E:\数模\2026年正式比赛\CUMCM2026Problems\C题\附件';


actualFile = ...
    fullfile( ...
    baseDir, ...
    '附件2.xlsx');


forecastFile = ...
    fullfile( ...
    baseDir, ...
    '附件3.xlsx');


priceFile = ...
    fullfile( ...
    baseDir, ...
    '附件1.xlsx');


%% ------------------------------------------------------------
% ★直接读取问题2最终MAT
%% ------------------------------------------------------------

Q2File = ...
    fullfile( ...
    baseDir, ...
    'Q2_P2_SIMILAR10_RESULT2_FINAL.mat');


%% ------------------------------------------------------------
% 官方问题3模板
%% ------------------------------------------------------------

result3File = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    'result3.xlsx');


%% ------------------------------------------------------------
% 自己保存的完整结果
%% ------------------------------------------------------------

resultMatFile = ...
    fullfile( ...
    baseDir, ...
    'Q3_Similar10_Affine_ReadQ2_TIMEFIX_FINAL.mat');


resultExcelFile = ...
    fullfile( ...
    baseDir, ...
    'Q3_Similar10_Affine_ReadQ2_TIMEFIX_FINAL.xlsx');


figSOCPng = ...
    fullfile( ...
    baseDir, ...
    'Q3_Similar10_Affine_SOC.png');


figWeightPng = ...
    fullfile( ...
    baseDir, ...
    'Q3_Similar10_Affine_PV权重.png');


filesNeed = {
    actualFile
    forecastFile
    priceFile
    Q2File
    result3File
    };


for i = 1:length(filesNeed)

    if ~isfile(filesNeed{i})

        error( ...
            '找不到文件：\n%s', ...
            filesNeed{i});

    end

end


fprintf('数据目录：\n%s\n\n',baseDir);


%% ============================================================
% 2. 参数
%% ============================================================

dt = ...
    1/6;


eta = ...
    0.90;


Ecapacity = ...
    12000;


Emin = ...
    1200;


Emax = ...
    10800;


Einitial = ...
    6000;


Efinal = ...
    6000;


Pmax = ...
    5000;


Wmax = ...
    Pmax*dt;


issueHours = ...
    [0,6,12,18];


%% ============================================================
% 2.1 Similar10
%% ============================================================

SIMILAR_WINDOW = ...
    30;


SIMILAR_MIN_HISTORY = ...
    7;


SIMILAR_COUNT = ...
    10;


%% ============================================================
% 2.2 PV动态融合
%% ============================================================

PV_BLEND_WINDOW = ...
    30;


PV_BLEND_MIN_HISTORY = ...
    7;


%% ============================================================
% 2.3 优化
%% ============================================================

emergencyFactor = ...
    5;


%% 极小吞吐量惩罚，只作tie-break
cyclePenalty = ...
    1e-5;


%% 极小弃电惩罚
curtailPenalty = ...
    1e-5;


USE_TERMINAL_VALUE = ...
    true;


FORCE_FINAL_SOC_6000 = ...
    false;


WRITE_OFFICIAL_RESULT3 = ...
    true;


%% ============================================================
% 3. 日期
%% ============================================================

dateAll = ...
    ( ...
    datetime(2025,1,1): ...
    days(1): ...
    datetime(2025,12,31) ...
    )';


%% ============================================================
% 4. 读取问题2结果
%% ============================================================

fprintf('读取问题2 MAT...\n');


Q2 = ...
    load(Q2File);


if ~isfield(Q2,'predLoad')

    error( ...
        '问题2 MAT中找不到 predLoad。');

end


predLoad = ...
    Q2.predLoad;


if ~isequal(size(predLoad),[334,144])

    error( ...
        '问题2 predLoad 应为334×144，当前为 %d×%d。', ...
        size(predLoad,1), ...
        size(predLoad,2));

end


predLoad = ...
    max(predLoad,0);


%% ------------------------------------------------------------
% 日期优先读取问题2保存的predDates
%% ------------------------------------------------------------

if isfield(Q2,'predDates')

    predDates = ...
        Q2.predDates(:);

else

    predDates = ...
        ( ...
        datetime(2025,2,1): ...
        days(1): ...
        datetime(2025,12,31) ...
        )';

end


if length(predDates)~=334

    error( ...
        '问题2 predDates必须为334天。');

end


nDay = ...
    334;


nTime = ...
    144;


fprintf('问题2负载预测读取完成：334×144。\n');
fprintf('问题3不再重新训练AS-Ridge。\n\n');


%% ============================================================
% 5. 读取附件2
%
% 仍读取完整365天实际值，因为：
%
% 1) 光伏动态融合需要1月份历史PV；
% 2) PV当前时刻锚点需要真实观测；
% 3) Similar10历史残差需要实际值；
% 4) 最终实际回放需要实际负载/PV。
%% ============================================================

fprintf('读取附件2真实负载/PV...\n');


loadAll = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','小区负载', ...
    'Range','B2:EO366');


pvAll = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','光伏发电实际功率', ...
    'Range','B2:EO366');


if ~isequal(size(loadAll),[365,144]) ...
        || ~isequal(size(pvAll),[365,144])

    error( ...
        '附件2负载/PV必须为365×144。');

end


if any(~isfinite(loadAll),'all') ...
        || any(~isfinite(pvAll),'all')

    error( ...
        '附件2存在NaN或非法值。');

end


%% ============================================================
% 6. 电价
%% ============================================================

fprintf('读取附件1电价...\n');


Tprice = ...
    readtable( ...
    priceFile, ...
    'VariableNamingRule','preserve');


price = ...
    Tprice{:,2};


price = ...
    price(:);


if length(price)~=144

    error( ...
        '附件1电价必须为144点。');

end


if any(~isfinite(price)) ...
        || any(price<0)

    error( ...
        '附件1存在非法电价。');

end


if USE_TERMINAL_VALUE

    terminalValue = ...
        eta*mean(price);

else

    terminalValue = ...
        0;

end


%% ============================================================
% 7. 读取附件3
%% ============================================================

fprintf('读取附件3四时次光伏预测...\n');


F = ...
    readForecastSingleSheet( ...
    forecastFile, ...
    'Sheet1');


if ~all( ...
        ismember( ...
        issueHours, ...
        unique(F.issueHour)'))

    error( ...
        '附件3没有完整包含0/6/12/18时预测。');

end


%% ============================================================
% 8. PV动态融合标定库
%% ============================================================

fprintf('建立PV动态融合标定库...\n');


PVlib = ...
    buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll);


fprintf( ...
    '完整PV历史预测记录：%d条。\n\n', ...
    sum(PVlib.complete));


%% ============================================================
% 9. 计算334天 × 4时次动态融合权重
%% ============================================================

fprintf('计算PV动态融合权重...\n');


wDynamic = ...
    ones(nDay,4);


nWeightHistory = ...
    zeros(nDay,4);


for kd = 1:nDay

    thisDate = ...
        predDates(kd);


    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        currentTime = ...
            thisDate ...
            +hours(hIssue);


        [ ...
            wDynamic(kd,ki), ...
            nWeightHistory(kd,ki) ...
            ] = ...
            getRollingPVBlendWeight( ...
            PVlib, ...
            hIssue, ...
            currentTime, ...
            PV_BLEND_WINDOW, ...
            PV_BLEND_MIN_HISTORY);

    end

end


fprintf('\n');
fprintf('PV动态权重统计：\n');


for ki = 1:4

    fprintf( ...
        '%2d时：mean=%.4f median=%.4f min=%.4f max=%.4f\n', ...
        issueHours(ki), ...
        mean(wDynamic(:,ki)), ...
        median(wDynamic(:,ki)), ...
        min(wDynamic(:,ki)), ...
        max(wDynamic(:,ki)));

end


weightTable = ...
    table( ...
    predDates, ...
    wDynamic(:,1), ...
    wDynamic(:,2), ...
    wDynamic(:,3), ...
    wDynamic(:,4), ...
    nWeightHistory(:,1), ...
    nWeightHistory(:,2), ...
    nWeightHistory(:,3), ...
    nWeightHistory(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'Weight_0h', ...
    'Weight_6h', ...
    'Weight_12h', ...
    'Weight_18h', ...
    'HistoryN_0h', ...
    'HistoryN_6h', ...
    'HistoryN_12h', ...
    'HistoryN_18h'} ...
    );


%% ============================================================
% 10. 建立Similar10历史预测/残差库
%
% 注意：
% 负载预测直接来自问题2。
%
% 对每条历史0/6/12/18时记录保存：
%
% baseLoad
% basePV
% eLoad
% ePV
% eNet = eLoad - ePV
%
% 以后根据baseLoad/basePV相似度选10条。
%% ============================================================

fprintf('\n建立Similar10历史残差库...\n');


Rlib = ...
    buildSimilarResidualLibraryQ2( ...
    F, ...
    loadAll, ...
    pvAll, ...
    predLoad, ...
    predDates, ...
    dateAll, ...
    PVlib, ...
    PV_BLEND_WINDOW, ...
    PV_BLEND_MIN_HISTORY);


fprintf( ...
    '完整Similar历史记录：%d条。\n\n', ...
    sum(Rlib.complete));


%% ============================================================
% 11. LP设置
%% ============================================================

lpOptions = ...
    optimoptions( ...
    'linprog', ...
    'Algorithm','dual-simplex-highs', ...
    'Display','none');


%% ============================================================
% 12. 初始化输出
%% ============================================================

plan0 = ...
    zeros(nDay,nTime);


executedPlan = ...
    zeros(nDay,nTime);


baseChargePlan = ...
    zeros(nDay,nTime);


baseDischargePlan = ...
    zeros(nDay,nTime);


actualCharge = ...
    zeros(nDay,nTime);


actualDischarge = ...
    zeros(nDay,nTime);


actualEmergency = ...
    zeros(nDay,nTime);


actualSurplus = ...
    zeros(nDay,nTime);


SOCstart = ...
    zeros(nDay,1);


SOCend = ...
    zeros(nDay,1);


retainedPlanCostDay = ...
    zeros(nDay,1);


increaseCostDay = ...
    zeros(nDay,1);


decreasePenaltyDay = ...
    zeros(nDay,1);


emergencyCostDay = ...
    zeros(nDay,1);


increaseEnergyDay = ...
    zeros(nDay,1);


decreaseEnergyDay = ...
    zeros(nDay,1);


similarN = ...
    nan(nDay,4);


similarMeanDistance = ...
    nan(nDay,4);


adjustmentTable = ...
    table();


maxLPViolation = ...
    0;


%% ============================================================
% 13. 正式滚动优化
%% ============================================================

fprintf('====================================================\n');
fprintf(' 开始问题3正式滚动优化\n');
fprintf('====================================================\n\n');


Ecurrent = ...
    Einitial;


timerAll = ...
    tic;


for kd = 1:nDay

    thisDate = ...
        predDates(kd);


    dFull = ...
        find( ...
        dateAll==thisDate, ...
        1);


    if isempty(dFull)

        error( ...
            '找不到日期：%s', ...
            string(thisDate));

    end


    isLastDay = ...
        kd==nDay;


    forceFinalToday = ...
        isLastDay ...
        &&FORCE_FINAL_SOC_6000;


    terminalValueToday = ...
        terminalValue;


    if isLastDay ...
            &&~FORCE_FINAL_SOC_6000

        terminalValueToday = ...
            0;

    end


    SOCstart(kd) = ...
        Ecurrent;


    currentPlan = ...
        zeros(144,1);


    currentChBase = ...
        zeros(144,1);


    currentDisBase = ...
        zeros(144,1);


    g0 = ...
        zeros(144,1);


    if mod(kd-1,20)==0 ...
            ||kd==nDay

        fprintf( ...
            '[%03d/%03d] %s | SOC=%.2f\n', ...
            kd, ...
            nDay, ...
            string(thisDate), ...
            Ecurrent);

    end


    %% ========================================================
    % 每天0/6/12/18时
    %% ========================================================

    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        %% ----------------------------------------------------
        % 发布时间后的第一个未来10min
        %% ----------------------------------------------------

        startSlot = ...
            hIssue*6+1;


        %% ----------------------------------------------------
        % 本轮只执行6h
        %% ----------------------------------------------------

        endSlot = ...
            min( ...
            startSlot+35, ...
            144);


        blockSlots = ...
            startSlot:endSlot;


        %% ----------------------------------------------------
        % 从当前发布时间到当天24:00一共有多少slot
        %% ----------------------------------------------------

        qCurrent = ...
            144-startSlot+1;


        %% ====================================================
        % 13.1 问题2 AS-Ridge未来24h负载预测
        %% ====================================================

        baseLoad24 = ...
            makeQ2LoadForecast24( ...
            predLoad, ...
            kd, ...
            hIssue, ...
            true);


        %% ====================================================
        % 13.2 附件3 + 历史动态融合PV
        %% ====================================================

        wNow = ...
            wDynamic(kd,ki);


        basePV24 = ...
            makeOfficialPV24Blend( ...
            F, ...
            pvAll, ...
            dateAll, ...
            dFull, ...
            hIssue, ...
            wNow);


        %% ====================================================
        % 13.3 Similar10
        %% ====================================================

        currentTime = ...
            thisDate ...
            +hours(hIssue);


        S = ...
            getSimilarResidualScenarios( ...
            Rlib, ...
            hIssue, ...
            currentTime, ...
            baseLoad24, ...
            basePV24, ...
            SIMILAR_WINDOW, ...
            SIMILAR_MIN_HISTORY, ...
            SIMILAR_COUNT);


        similarN(kd,ki) = ...
            S.nSelected;


        similarMeanDistance(kd,ki) = ...
            S.meanDistance;


        %% ====================================================
        % 13.4 当前基础净负荷
        %% ====================================================

        forecastNet24 = ...
            baseLoad24(:) ...
            -basePV24(:);


        %% ====================================================
        % 13.5 滚动24h电价
        %
        % 例如6时：
        %
        % 6:10 ... 24:00
        % 次日00:10 ... 06:00
        %% ====================================================

        price24 = ...
            [ ...
            price(startSlot:end); ...
            price(1:startSlot-1) ...
            ];


        %% ====================================================
        % 13.6 0时计划结算基准
        %% ====================================================

        if ki==1

            g0Remain = ...
                [];

        else

            g0Remain = ...
                g0(startSlot:end);

        end


        %% ====================================================
        % 13.7 Similar10因果仿射LP
        %% ====================================================

        P = ...
            solveRolling24hCausalAffineLP( ...
            forecastNet24, ...
            S.netResidual, ...
            S.prob, ...
            price24, ...
            qCurrent, ...
            g0Remain, ...
            Ecurrent, ...
            forceFinalToday, ...
            Efinal, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax, ...
            emergencyFactor, ...
            terminalValueToday, ...
            cyclePenalty, ...
            curtailPenalty, ...
            lpOptions);


        maxLPViolation = ...
            max( ...
            maxLPViolation, ...
            P.maxConstraintViolation);


        %% ====================================================
        % 0时：
        % 形成全天原始计划
        %% ====================================================

        if ki==1

            g0 = ...
                P.currentGrid;


            currentPlan = ...
                g0;


            currentChBase = ...
                P.currentChargeBase;


            currentDisBase = ...
                P.currentDischargeBase;


            plan0(kd,:) = ...
                g0';


        %% ====================================================
        % 6/12/18时：
        % 更新当天剩余普通购电计划
        %% ====================================================

        else

            oldPlan = ...
                currentPlan(startSlot:end);


            currentPlan(startSlot:end) = ...
                P.currentGrid;


            currentChBase(startSlot:end) = ...
                P.currentChargeBase;


            currentDisBase(startSlot:end) = ...
                P.currentDischargeBase;


            oneInc = ...
                sum( ...
                max( ...
                P.currentGrid ...
                -g0(startSlot:end), ...
                0));


            oneDec = ...
                sum( ...
                max( ...
                g0(startSlot:end) ...
                -P.currentGrid, ...
                0));


            logRow = ...
                table( ...
                thisDate, ...
                hIssue, ...
                wNow, ...
                S.nSelected, ...
                S.meanDistance, ...
                sum( ...
                abs( ...
                P.currentGrid-oldPlan) ...
                >1e-6), ...
                oneInc, ...
                oneDec, ...
                P.objective, ...
                P.maxConstraintViolation, ...
                'VariableNames',{ ...
                'Date', ...
                'IssueHour', ...
                'PVBlendWeight', ...
                'SimilarCount', ...
                'MeanSimilarDistance', ...
                'ChangedSlots', ...
                'IncreaseVs0_kWh', ...
                'DecreaseVs0_kWh', ...
                'RollingObjective', ...
                'MaxConstraintViolation'} ...
                );


            adjustmentTable = ...
                [adjustmentTable;logRow];

        end


        %% ====================================================
        % 13.8 实际执行未来6h
        %
        % 只使用当前真实负载/PV进行因果反馈
        %% ====================================================

        A = ...
            replayActualBlockWithBase( ...
            loadAll(dFull,blockSlots)', ...
            pvAll(dFull,blockSlots)', ...
            currentPlan(blockSlots), ...
            currentChBase(blockSlots), ...
            currentDisBase(blockSlots), ...
            Ecurrent, ...
            blockSlots, ...
            forceFinalToday, ...
            Efinal, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax);


        executedPlan(kd,blockSlots) = ...
            currentPlan(blockSlots)';


        baseChargePlan(kd,blockSlots) = ...
            currentChBase(blockSlots)';


        baseDischargePlan(kd,blockSlots) = ...
            currentDisBase(blockSlots)';


        actualCharge(kd,blockSlots) = ...
            A.Wch';


        actualDischarge(kd,blockSlots) = ...
            A.Wdis';


        actualEmergency(kd,blockSlots) = ...
            A.Wem';


        actualSurplus(kd,blockSlots) = ...
            A.Wsur';


        Ecurrent = ...
            A.Eend;

    end


    %% ========================================================
    % 13.9 当天结束SOC
    %% ========================================================

    SOCend(kd) = ...
        Ecurrent;


    %% ========================================================
    % 13.10 题目规定结算
    %% ========================================================

    inc = ...
        max( ...
        executedPlan(kd,:)' ...
        -g0, ...
        0);


    dec = ...
        max( ...
        g0 ...
        -executedPlan(kd,:)', ...
        0);


    retainedPlanCostDay(kd) = ...
        sum( ...
        price ...
        .*min( ...
        g0, ...
        executedPlan(kd,:)'));


    increaseCostDay(kd) = ...
        1.5 ...
        *sum( ...
        price.*inc);


    decreasePenaltyDay(kd) = ...
        0.5 ...
        *sum( ...
        price.*dec);


    emergencyCostDay(kd) = ...
        emergencyFactor ...
        *sum( ...
        price ...
        .*actualEmergency(kd,:)');


    increaseEnergyDay(kd) = ...
        sum(inc);


    decreaseEnergyDay(kd) = ...
        sum(dec);

end


runtimeMin = ...
    toc(timerAll)/60;


%% ============================================================
% 14. 最终结果
%% ============================================================

dailyCost = ...
    retainedPlanCostDay ...
    +increaseCostDay ...
    +decreasePenaltyDay ...
    +emergencyCostDay;


totalRetainedPlanCost = ...
    sum(retainedPlanCostDay);


totalIncreaseCost = ...
    sum(increaseCostDay);


totalDecreasePenalty = ...
    sum(decreasePenaltyDay);


totalEmergencyCost = ...
    sum(emergencyCostDay);


totalCost = ...
    sum(dailyCost);


totalIncreaseEnergy = ...
    sum(increaseEnergyDay);


totalDecreaseEnergy = ...
    sum(decreaseEnergyDay);


totalEmergencyEnergy = ...
    sum(actualEmergency,'all');


emergencyDays = ...
    sum( ...
    any( ...
    actualEmergency>1e-8, ...
    2));


emergencySlots = ...
    nnz( ...
    actualEmergency>1e-8);


planSimultaneousSlots = ...
    nnz( ...
    baseChargePlan>1e-8 ...
    &baseDischargePlan>1e-8);


actualSimultaneousSlots = ...
    nnz( ...
    actualCharge>1e-8 ...
    &actualDischarge>1e-8);


finalSOC = ...
    SOCend(end);


costIdentityError = ...
    abs( ...
    totalCost ...
    -( ...
    totalRetainedPlanCost ...
    +totalIncreaseCost ...
    +totalDecreasePenalty ...
    +totalEmergencyCost));


fprintf('\n');
fprintf('====================================================\n');
fprintf(' 问题3 Similar10 + 因果仿射最终结果\n');
fprintf('====================================================\n');


fprintf( ...
    '保留0时计划购电费：%.2f 元\n', ...
    totalRetainedPlanCost);


fprintf( ...
    '上调购电费用：%.2f 元\n', ...
    totalIncreaseCost);


fprintf( ...
    '下调计划违约损失：%.2f 元\n', ...
    totalDecreasePenalty);


fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    totalEmergencyCost);


fprintf('\n');


fprintf( ...
    '全年总成本：%.2f 元\n', ...
    totalCost);


fprintf( ...
    '全年上调购电量：%.2f kWh\n', ...
    totalIncreaseEnergy);


fprintf( ...
    '全年下调购电量：%.2f kWh\n', ...
    totalDecreaseEnergy);


fprintf( ...
    '全年紧急购电量：%.2f kWh\n', ...
    totalEmergencyEnergy);


fprintf( ...
    '紧急购电天数：%d\n', ...
    emergencyDays);


fprintf( ...
    '紧急购电时段数：%d\n', ...
    emergencySlots);


fprintf('\n');


fprintf( ...
    '年末SOC：%.6f kWh\n', ...
    finalSOC);


fprintf( ...
    '计划基础轨迹同时充放电时段：%d\n', ...
    planSimultaneousSlots);


fprintf( ...
    '实际同时充放电时段：%d\n', ...
    actualSimultaneousSlots);


fprintf( ...
    '最大LP约束违反量：%.3e\n', ...
    maxLPViolation);


fprintf( ...
    '成本核对误差：%.3e 元\n', ...
    costIdentityError);


fprintf( ...
    '运行时间：%.2f min\n', ...
    runtimeMin);


fprintf('====================================================\n');


%% ============================================================
% 15. 每日结果表
%% ============================================================

dailyTable = ...
    table( ...
    predDates, ...
    SOCstart, ...
    SOCend, ...
    retainedPlanCostDay, ...
    increaseCostDay, ...
    decreasePenaltyDay, ...
    emergencyCostDay, ...
    dailyCost, ...
    increaseEnergyDay, ...
    decreaseEnergyDay, ...
    sum(actualEmergency,2), ...
    'VariableNames',{ ...
    'Date', ...
    'SOCstart_kWh', ...
    'SOCend_kWh', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh'} ...
    );


%% ============================================================
% 16. Similar10诊断
%% ============================================================

similarTable = ...
    table( ...
    predDates, ...
    similarN(:,1), ...
    similarN(:,2), ...
    similarN(:,3), ...
    similarN(:,4), ...
    similarMeanDistance(:,1), ...
    similarMeanDistance(:,2), ...
    similarMeanDistance(:,3), ...
    similarMeanDistance(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'SimilarN_0h', ...
    'SimilarN_6h', ...
    'SimilarN_12h', ...
    'SimilarN_18h', ...
    'Distance_0h', ...
    'Distance_6h', ...
    'Distance_12h', ...
    'Distance_18h'} ...
    );


%% ============================================================
% 17. 汇总表
%% ============================================================

summaryTable = ...
    table( ...
    "Similar10CausalAffineRolling", ...
    totalRetainedPlanCost, ...
    totalIncreaseCost, ...
    totalDecreasePenalty, ...
    totalEmergencyCost, ...
    totalCost, ...
    totalIncreaseEnergy, ...
    totalDecreaseEnergy, ...
    totalEmergencyEnergy, ...
    emergencyDays, ...
    emergencySlots, ...
    finalSOC, ...
    planSimultaneousSlots, ...
    actualSimultaneousSlots, ...
    maxLPViolation, ...
    runtimeMin, ...
    'VariableNames',{ ...
    'Model', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh', ...
    'EmergencyDays', ...
    'EmergencySlots', ...
    'FinalSOC_kWh', ...
    'PlanSimultaneousSlots', ...
    'ActualSimultaneousSlots', ...
    'MaxLPViolation', ...
    'Runtime_Min'} ...
    );


%% ============================================================
% 18. 保存自己的Excel
%% ============================================================

if isfile(resultExcelFile)

    delete(resultExcelFile);

end


writetable( ...
    summaryTable, ...
    resultExcelFile, ...
    'Sheet','汇总');


writetable( ...
    dailyTable, ...
    resultExcelFile, ...
    'Sheet','每日结果');


writetable( ...
    adjustmentTable, ...
    resultExcelFile, ...
    'Sheet','调整明细');


writetable( ...
    weightTable, ...
    resultExcelFile, ...
    'Sheet','PV动态权重');


writetable( ...
    similarTable, ...
    resultExcelFile, ...
    'Sheet','Similar10诊断');


%% ============================================================
% 19. 写官方result3.xlsx
%% ============================================================

if WRITE_OFFICIAL_RESULT3

    fprintf('\n开始写官方 result3.xlsx...\n');


    %% ========================================================
    % 19.1 备份
    %% ========================================================

    backupFile = ...
        fullfile( ...
        baseDir, ...
        '附件5', ...
        [ ...
        'result3_backup_SIMILAR10_', ...
        char( ...
        datetime( ...
        'now', ...
        'Format','yyyyMMdd_HHmmss')), ...
        '.xlsx' ...
        ]);


    copyfile( ...
        result3File, ...
        backupFile);


    fprintf( ...
        '原result3已备份：\n%s\n', ...
        backupFile);


    %% ========================================================
    % 19.2 计划购电量
    %% ========================================================

    planEnergyDay = ...
        sum(plan0,2);


    planCostDay = ...
        sum( ...
        plan0 ...
        .*price', ...
        2);


    writematrix( ...
        plan0, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','B2');


    writematrix( ...
        planEnergyDay, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','EP2');


    writematrix( ...
        planCostDay, ...
        result3File, ...
        'Sheet','计划购电量', ...
        'Range','EQ2');


    fprintf('计划购电量写入完成。\n');


    %% ========================================================
    % 19.3 调整购电量
    %% ========================================================

    adjustedEnergyDay = ...
        sum(executedPlan,2);


    adjustedCostDay = ...
        retainedPlanCostDay ...
        +increaseCostDay ...
        +decreasePenaltyDay;


    writematrix( ...
        executedPlan, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','B2');


    writematrix( ...
        adjustedEnergyDay, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','EP2');


    writematrix( ...
        adjustedCostDay, ...
        result3File, ...
        'Sheet','调整购电量', ...
        'Range','EQ2');


    fprintf('调整购电量写入完成。\n');


    %% ========================================================
    % 19.4 充放电量
    %% ========================================================

    timeBlockName = {
        '0:00-4:00'
        '4:00-8:00'
        '8:00-12:00'
        '12:00-16:00'
        '16:00-20:00'
        '20:00-24:00'
        };


    nBlock = ...
        6;


    charge4h = ...
        zeros(nDay,nBlock);


    discharge4h = ...
        zeros(nDay,nBlock);


    for kd = 1:nDay

        for b = 1:nBlock

            s1 = ...
                (b-1)*24+1;


            s2 = ...
                b*24;


            charge4h(kd,b) = ...
                sum( ...
                actualCharge(kd,s1:s2));


            discharge4h(kd,b) = ...
                sum( ...
                actualDischarge(kd,s1:s2));

        end

    end


    nCDRow = ...
        nDay*nBlock;


    cdOut = ...
        cell(nCDRow,6);


    rr = ...
        1;


    for kd = 1:nDay

        for b = 1:nBlock

            if b==1

                cdOut{rr,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');

            else

                cdOut{rr,1} = ...
                    '';

            end


            cdOut{rr,2} = ...
                timeBlockName{b};


            cdOut{rr,3} = ...
                charge4h(kd,b);


            cdOut{rr,4} = ...
                discharge4h(kd,b);


            if b==1

                cdOut{rr,5} = ...
                    '0:00';


                cdOut{rr,6} = ...
                    SOCstart(kd);

            elseif b==2

                cdOut{rr,5} = ...
                    '24:00';


                cdOut{rr,6} = ...
                    SOCend(kd);

            else

                cdOut{rr,5} = ...
                    '';


                cdOut{rr,6} = ...
                    [];

            end


            rr = ...
                rr+1;

        end

    end


    %% 清理旧数据
    clearCD = ...
        repmat({''},2500,6);


    writecell( ...
        clearCD, ...
        result3File, ...
        'Sheet','充放电量', ...
        'Range','A2');


    writecell( ...
        cdOut, ...
        result3File, ...
        'Sheet','充放电量', ...
        'Range','A2');


    fprintf('充放电量写入完成。\n');


    %% ========================================================
    % 19.5 紧急购电量
    %% ========================================================

    emergencyRows = ...
        cell(0,3);


    outRow = ...
        0;


    for kd = 1:nDay

        x = ...
            actualEmergency(kd,:);


        active = ...
            x>1e-8;


        if ~any(active)

            continue;

        end


        edge = ...
            diff( ...
            [ ...
            false, ...
            active, ...
            false ...
            ]);


        starts = ...
            find(edge==1);


        ends = ...
            find(edge==-1)-1;


        for kk = 1:length(starts)

            s = ...
                starts(kk);


            e = ...
                ends(kk);


            outRow = ...
                outRow+1;


            if kk==1

                emergencyRows{outRow,1} = ...
                    datestr( ...
                    predDates(kd), ...
                    'yyyy-mm-dd');

            else

                emergencyRows{outRow,1} = ...
                    '';

            end


            emergencyRows{outRow,2} = ...
                makeEmergencyTimeRange(s,e);


            emergencyRows{outRow,3} = ...
                sum( ...
                x(s:e));

        end

    end


    %% 清旧数据
    clearEmergency = ...
        repmat({''},5000,3);


    writecell( ...
        clearEmergency, ...
        result3File, ...
        'Sheet','紧急购电量', ...
        'Range','A2');


    if ~isempty(emergencyRows)

        writecell( ...
            emergencyRows, ...
            result3File, ...
            'Sheet','紧急购电量', ...
            'Range','A2');

    end


    fprintf('紧急购电量写入完成。\n');


    fprintf('\n');
    fprintf('====================================================\n');
    fprintf(' result3.xlsx 完成\n');
    fprintf('====================================================\n');


    fprintf( ...
        '0时计划购电量：%.2f kWh\n', ...
        sum(plan0,'all'));


    fprintf( ...
        '最终调整普通购电量：%.2f kWh\n', ...
        sum(executedPlan,'all'));


    fprintf( ...
        '实际充电量：%.2f kWh\n', ...
        sum(actualCharge,'all'));


    fprintf( ...
        '实际放电量：%.2f kWh\n', ...
        sum(actualDischarge,'all'));


    fprintf( ...
        '紧急购电量：%.2f kWh\n', ...
        totalEmergencyEnergy);


    fprintf( ...
        '调整后普通购电费用：%.2f 元\n', ...
        sum(adjustedCostDay));


    fprintf( ...
        '紧急购电费用：%.2f 元\n', ...
        totalEmergencyCost);


    fprintf( ...
        '总费用：%.2f 元\n', ...
        totalCost);


    fprintf('====================================================\n');

end


%% ============================================================
% 20. MAT
%% ============================================================

save( ...
    resultMatFile, ...
    'summaryTable', ...
    'dailyTable', ...
    'adjustmentTable', ...
    'weightTable', ...
    'similarTable', ...
    'predDates', ...
    'predLoad', ...
    'plan0', ...
    'executedPlan', ...
    'baseChargePlan', ...
    'baseDischargePlan', ...
    'actualCharge', ...
    'actualDischarge', ...
    'actualEmergency', ...
    'actualSurplus', ...
    'SOCstart', ...
    'SOCend', ...
    'wDynamic', ...
    'PVlib', ...
    'Rlib', ...
    'totalCost', ...
    'runtimeMin', ...
    '-v7.3');


%% ============================================================
% 21. 图
%% ============================================================

fig1 = ...
    figure( ...
    'Color','w', ...
    'Position',[100,100,1300,650]);


plot( ...
    predDates, ...
    SOCend, ...
    'LineWidth',1.1);


hold on;


yline(Emin,'--','SOC下限');


yline(Emax,'--','SOC上限');


yline(Efinal,':','6000 kWh参考线');


xlabel('日期');


ylabel('日末SOC / kWh');


title( ...
    '问题3 Similar10因果仿射方案日末SOC');


grid on;


exportgraphics( ...
    fig1, ...
    figSOCPng, ...
    'Resolution',300);


fig2 = ...
    figure( ...
    'Color','w', ...
    'Position',[100,100,1300,700]);


plot(predDates,wDynamic(:,1),'LineWidth',1);
hold on;
plot(predDates,wDynamic(:,2),'LineWidth',1);
plot(predDates,wDynamic(:,3),'LineWidth',1);
plot(predDates,wDynamic(:,4),'LineWidth',1);


ylim([0,1]);


xlabel('日期');


ylabel('附件3正式预报权重');


title( ...
    '问题3 0/6/12/18时PV动态融合权重');


legend( ...
    '0时','6时','12时','18时', ...
    'Location','best');


grid on;


exportgraphics( ...
    fig2, ...
    figWeightPng, ...
    'Resolution',300);


fprintf('\n');
fprintf('====================================================\n');
fprintf(' 问题3全部完成\n');
fprintf(' Excel：%s\n',resultExcelFile);
fprintf(' MAT：%s\n',resultMatFile);
fprintf(' result3：%s\n',result3File);
fprintf('====================================================\n');


%% ============================================================
% 局部函数1
%
% 问题2负载预测 -> 发布时间以后连续24h
%% ============================================================

function load24 = makeQ2LoadForecast24( ...
    predLoad, ...
    kd, ...
    issueHour, ...
    allowLastDayFallback)


startSlot = ...
    issueHour*6+1;


nDay = ...
    size(predLoad,1);


if issueHour==0

    load24 = ...
        predLoad(kd,:)';


    return;

end


todayPart = ...
    predLoad( ...
    kd, ...
    startSlot:end);


if kd<nDay

    nextPart = ...
        predLoad( ...
        kd+1, ...
        1:startSlot-1);


elseif allowLastDayFallback

    %% --------------------------------------------------------
    % 12月31日跨午夜部分没有2026-01-01预测
    %
    % 这里只作为24h展望窗口的尾部代理，
    % 并不会真正执行到2026年。
    %% --------------------------------------------------------

    nextPart = ...
        predLoad( ...
        kd, ...
        1:startSlot-1);

else

    load24 = ...
        [];

    return;

end


load24 = ...
    [ ...
    todayPart, ...
    nextPart ...
    ]';


end


%% ============================================================
% 局部函数2
%
% 建立Similar10历史残差库
%% ============================================================

function Rlib = buildSimilarResidualLibraryQ2( ...
    F, ...
    loadAll, ...
    pvAll, ...
    predLoad, ...
    predDates, ...
    dateAll, ...
    PVlib, ...
    blendWindow, ...
    blendMinHistory)


nRec = ...
    length(F.dates);


baseLoad = ...
    nan(nRec,144);


basePV = ...
    nan(nRec,144);


eLoad = ...
    nan(nRec,144);


ePV = ...
    nan(nRec,144);


eNet = ...
    nan(nRec,144);


complete = ...
    false(nRec,1);


for i = 1:nRec

    thisDate = ...
        F.dates(i);


    kd = ...
        find( ...
        predDates==thisDate, ...
        1);


    if isempty(kd)

        continue;

    end


    dFull = ...
        find( ...
        dateAll==thisDate, ...
        1);


    if isempty(dFull)

        continue;

    end


    hIssue = ...
        F.issueHour(i);


    %% --------------------------------------------------------
    % 历史库最后一天跨午夜若无下一日预测，不使用
    %% --------------------------------------------------------

    oneBaseLoad = ...
        makeQ2LoadForecast24( ...
        predLoad, ...
        kd, ...
        hIssue, ...
        false);


    if isempty(oneBaseLoad)

        continue;

    end


    actualLoad24 = ...
        extractActual24( ...
        loadAll, ...
        dFull, ...
        hIssue);


    actualPV24 = ...
        extractActual24( ...
        pvAll, ...
        dFull, ...
        hIssue);


    if isempty(actualLoad24) ...
            ||isempty(actualPV24)

        continue;

    end


    [wHist,~] = ...
        getRollingPVBlendWeight( ...
        PVlib, ...
        hIssue, ...
        F.issueTime(i), ...
        blendWindow, ...
        blendMinHistory);


    oneBasePV = ...
        makeOfficialPV24Blend( ...
        F, ...
        pvAll, ...
        dateAll, ...
        dFull, ...
        hIssue, ...
        wHist);


    baseLoad(i,:) = ...
        oneBaseLoad';


    basePV(i,:) = ...
        oneBasePV';


    eLoad(i,:) = ...
        ( ...
        actualLoad24 ...
        -oneBaseLoad ...
        )';


    ePV(i,:) = ...
        ( ...
        actualPV24 ...
        -oneBasePV ...
        )';


    eNet(i,:) = ...
        eLoad(i,:) ...
        -ePV(i,:);


    complete(i) = ...
        all(isfinite(baseLoad(i,:))) ...
        &&all(isfinite(basePV(i,:))) ...
        &&all(isfinite(eNet(i,:)));

end


Rlib.date = ...
    F.dates;


Rlib.issueHour = ...
    F.issueHour;


Rlib.issueTime = ...
    F.issueTime;


Rlib.baseLoad = ...
    baseLoad;


Rlib.basePV = ...
    basePV;


Rlib.eLoad = ...
    eLoad;


Rlib.ePV = ...
    ePV;


Rlib.eNet = ...
    eNet;


Rlib.complete = ...
    complete;


end


%% ============================================================
% 局部函数3
%
% Similar10
%% ============================================================

function S = getSimilarResidualScenarios( ...
    Rlib, ...
    issueHour, ...
    currentTime, ...
    currentLoad24, ...
    currentPV24, ...
    historyWindow, ...
    minHistory, ...
    similarCount)


%% ------------------------------------------------------------
% 必须已经完整观察24h真实结果
%% ------------------------------------------------------------

valid = ...
    Rlib.complete ...
    &Rlib.issueHour==issueHour ...
    &( ...
    Rlib.issueTime+hours(24) ...
    <=currentTime);


rows = ...
    find(valid);


if isempty(rows)

    S.netResidual = ...
        zeros(1,144);


    S.prob = ...
        1;


    S.nSelected = ...
        1;


    S.nHistory = ...
        0;


    S.meanDistance = ...
        NaN;


    return;

end


%% ------------------------------------------------------------
% 最近30条
%% ------------------------------------------------------------

[~,ord] = ...
    sort(Rlib.issueTime(rows));


rows = ...
    rows(ord);


firstKeep = ...
    max( ...
    1, ...
    length(rows)-historyWindow+1);


rows = ...
    rows(firstKeep:end);


nHistory = ...
    length(rows);


if nHistory<minHistory

    S.netResidual = ...
        zeros(1,144);


    S.prob = ...
        1;


    S.nSelected = ...
        1;


    S.nHistory = ...
        nHistory;


    S.meanDistance = ...
        NaN;


    return;

end


currentLoad24 = ...
    currentLoad24(:)';


currentPV24 = ...
    currentPV24(:)';


loadScale = ...
    max( ...
    mean(abs(currentLoad24)), ...
    1);


pvScale = ...
    max( ...
    mean(abs(currentPV24)), ...
    1);


loadDistance = ...
    sqrt( ...
    mean( ...
    ( ...
    ( ...
    Rlib.baseLoad(rows,:) ...
    -currentLoad24 ...
    ) ...
    /loadScale ...
    ).^2, ...
    2));


pvDistance = ...
    sqrt( ...
    mean( ...
    ( ...
    ( ...
    Rlib.basePV(rows,:) ...
    -currentPV24 ...
    ) ...
    /pvScale ...
    ).^2, ...
    2));


totalDistance = ...
    loadDistance ...
    +pvDistance;


[~,order] = ...
    sort( ...
    totalDistance, ...
    'ascend');


keepN = ...
    min( ...
    similarCount, ...
    length(order));


keep = ...
    order(1:keepN);


selectedRows = ...
    rows(keep);


S.netResidual = ...
    Rlib.eNet(selectedRows,:);


%% 与问题2P2一致：相似日等概率
S.prob = ...
    ones(keepN,1) ...
    /keepN;


S.nSelected = ...
    keepN;


S.nHistory = ...
    nHistory;


S.meanDistance = ...
    mean( ...
    totalDistance(keep));


S.selectedDate = ...
    Rlib.date(selectedRows);


S.distance = ...
    totalDistance(keep);


end


%% ============================================================
% 局部函数4
%
% Similar10因果仿射滚动LP
%% ============================================================

function P = solveRolling24hCausalAffineLP( ...
    forecastNet, ...
    residualScenarios, ...
    prob, ...
    price24, ...
    qCurrent, ...
    g0Remain, ...
    Estart, ...
    forceFinalToday, ...
    Efinal, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    emergencyFactor, ...
    terminalValue, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)


H = ...
    144;


forecastNet = ...
    forecastNet(:);


price24 = ...
    price24(:);


[K,H2] = ...
    size(residualScenarios);


if length(forecastNet)~=H ...
        ||H2~=H

    error( ...
        '预测和残差情景都必须为144点。');

end


prob = ...
    prob(:);


prob = ...
    prob/sum(prob);


%% ------------------------------------------------------------
% 输入forecastNet和residualScenarios均为kW
%
% 转10min电量
%% ------------------------------------------------------------

dt = ...
    1/6;


Wbase = ...
    forecastNet' ...
    *dt;


R = ...
    residualScenarios ...
    *dt;


Rp = ...
    max(R,0);


Rn = ...
    max(-R,0);


%% ============================================================
% 变量
%% ============================================================

idxG = ...
    1:H;


base = ...
    H;


isInitial = ...
    isempty(g0Remain);


if isInitial

    idxInc = ...
        [];


    idxDec = ...
        [];

else

    idxInc = ...
        base+(1:qCurrent);


    base = ...
        base+qCurrent;


    idxDec = ...
        base+(1:qCurrent);


    base = ...
        base+qCurrent;


    g0Remain = ...
        g0Remain(:);

end


idxC0 = ...
    base+(1:H);


base = ...
    base+H;


idxD0 = ...
    base+(1:H);


base = ...
    base+H;


idxACP = ...
    base+(1:H);


base = ...
    base+H;


idxACN = ...
    base+(1:H);


base = ...
    base+H;


idxADP = ...
    base+(1:H);


base = ...
    base+H;


idxADN = ...
    base+(1:H);


base = ...
    base+H;


idxEbase = ...
    base+(1:H+1);


base = ...
    base+H+1;


idxSpBase = ...
    base+(1:H);


base = ...
    base+H;


idxE = ...
    reshape( ...
    base+(1:K*(H+1)), ...
    H+1,K)';


base = ...
    base+K*(H+1);


idxEm = ...
    reshape( ...
    base+(1:K*H), ...
    H,K)';


base = ...
    base+K*H;


idxSp = ...
    reshape( ...
    base+(1:K*H), ...
    H,K)';


nVar = ...
    base+K*H;


%% ============================================================
% 目标函数
%% ============================================================

f = ...
    zeros(nVar,1);


%% 普通购电
f(idxG) = ...
    price24;


%% ------------------------------------------------------------
% 6/12/18时：
%
% G - inc + dec = G0
%
% pG + 0.5p inc + 0.5p dec
%
% 等价：
% 增购1.5p
% 减购付0.5p违约成本
%% ------------------------------------------------------------

if ~isInitial

    f(idxInc) = ...
        0.5 ...
        *price24(1:qCurrent);


    f(idxDec) = ...
        0.5 ...
        *price24(1:qCurrent);

end


%% ------------------------------------------------------------
% Scenario expected emergency/spill/terminal value
%% ------------------------------------------------------------

for s = 1:K

    f(idxEm(s,:)) = ...
        prob(s) ...
        *emergencyFactor ...
        *price24;


    f(idxSp(s,:)) = ...
        prob(s) ...
        *curtailPenalty;


    f(idxE(s,end)) = ...
        f(idxE(s,end)) ...
        -prob(s)*terminalValue;

end


%% 基础路径也加极小弃电惩罚
f(idxSpBase) = ...
    curtailPenalty;


%% ------------------------------------------------------------
% 期望储能吞吐tie-break
%% ------------------------------------------------------------

mRp = ...
    (prob'*Rp)';


mRn = ...
    (prob'*Rn)';


f(idxC0) = ...
    cyclePenalty;


f(idxD0) = ...
    cyclePenalty;


f(idxACP) = ...
    -cyclePenalty*mRp;


f(idxACN) = ...
    cyclePenalty*mRn;


f(idxADP) = ...
    cyclePenalty*mRp;


f(idxADN) = ...
    -cyclePenalty*mRn;


%% ============================================================
% 等式约束
%% ============================================================

nAdjustEq = ...
    double(~isInitial) ...
    *qCurrent;


nBaseEq = ...
    2*H+1;


nScenarioEq = ...
    K*(2*H+1);


nEq = ...
    nAdjustEq ...
    +nBaseEq ...
    +nScenarioEq;


Aeq = ...
    spalloc( ...
    nEq, ...
    nVar, ...
    20*nEq);


beq = ...
    zeros(nEq,1);


row = ...
    0;


%% ============================================================
% 相对0时计划的调整
%% ============================================================

if ~isInitial

    for t = 1:qCurrent

        row = ...
            row+1;


        Aeq(row,idxG(t)) = ...
            1;


        Aeq(row,idxInc(t)) = ...
            -1;


        Aeq(row,idxDec(t)) = ...
            1;


        beq(row) = ...
            g0Remain(t);

    end

end


%% ============================================================
% 零残差基础路径
%% ============================================================

for t = 1:H

    %% 供需平衡
    row = ...
        row+1;


    Aeq(row,idxG(t)) = ...
        1;


    Aeq(row,idxD0(t)) = ...
        1;


    Aeq(row,idxC0(t)) = ...
        -1;


    Aeq(row,idxSpBase(t)) = ...
        -1;


    beq(row) = ...
        Wbase(t);

end


for t = 1:H

    %% SOC
    row = ...
        row+1;


    Aeq(row,idxEbase(t)) = ...
        -1;


    Aeq(row,idxEbase(t+1)) = ...
        1;


    Aeq(row,idxC0(t)) = ...
        -eta;


    Aeq(row,idxD0(t)) = ...
        1/eta;

end


row = ...
    row+1;


Aeq(row,idxEbase(1)) = ...
    1;


beq(row) = ...
    Estart;


%% ============================================================
% Similar10情景路径
%% ============================================================

for s = 1:K

    for t = 1:H

        %% ----------------------------------------------------
        % 电量平衡
        %
        % C_s =
        % C0 - ACP*Rp + ACN*Rn
        %
        % D_s =
        % D0 + ADP*Rp - ADN*Rn
        %% ----------------------------------------------------

        row = ...
            row+1;


        Aeq(row,idxG(t)) = ...
            1;


        Aeq(row,idxC0(t)) = ...
            -1;


        Aeq(row,idxD0(t)) = ...
            1;


        Aeq(row,idxACP(t)) = ...
            Rp(s,t);


        Aeq(row,idxACN(t)) = ...
            -Rn(s,t);


        Aeq(row,idxADP(t)) = ...
            Rp(s,t);


        Aeq(row,idxADN(t)) = ...
            -Rn(s,t);


        Aeq(row,idxEm(s,t)) = ...
            1;


        Aeq(row,idxSp(s,t)) = ...
            -1;


        beq(row) = ...
            Wbase(t) ...
            +R(s,t);

    end


    for t = 1:H

        %% SOC
        row = ...
            row+1;


        Aeq(row,idxE(s,t)) = ...
            -1;


        Aeq(row,idxE(s,t+1)) = ...
            1;


        Aeq(row,idxC0(t)) = ...
            -eta;


        Aeq(row,idxD0(t)) = ...
            1/eta;


        Aeq(row,idxACP(t)) = ...
            eta*Rp(s,t);


        Aeq(row,idxACN(t)) = ...
            -eta*Rn(s,t);


        Aeq(row,idxADP(t)) = ...
            Rp(s,t)/eta;


        Aeq(row,idxADN(t)) = ...
            -Rn(s,t)/eta;

    end


    row = ...
        row+1;


    Aeq(row,idxE(s,1)) = ...
        1;


    beq(row) = ...
        Estart;

end


if row~=nEq

    error( ...
        'LP等式约束内部行数错误。');

end


%% ============================================================
% 仿射响应充放电上下界
%% ============================================================

nIneq = ...
    4*K*H;


A = ...
    spalloc( ...
    nIneq, ...
    nVar, ...
    12*K*H);


b = ...
    zeros(nIneq,1);


row = ...
    0;


for s = 1:K

    for t = 1:H

        %% C <= Wmax
        row = ...
            row+1;


        A(row,idxC0(t)) = ...
            1;


        A(row,idxACP(t)) = ...
            -Rp(s,t);


        A(row,idxACN(t)) = ...
            Rn(s,t);


        b(row) = ...
            Wmax;


        %% C >= 0
        row = ...
            row+1;


        A(row,idxC0(t)) = ...
            -1;


        A(row,idxACP(t)) = ...
            Rp(s,t);


        A(row,idxACN(t)) = ...
            -Rn(s,t);


        %% D <= Wmax
        row = ...
            row+1;


        A(row,idxD0(t)) = ...
            1;


        A(row,idxADP(t)) = ...
            Rp(s,t);


        A(row,idxADN(t)) = ...
            -Rn(s,t);


        b(row) = ...
            Wmax;


        %% D >= 0
        row = ...
            row+1;


        A(row,idxD0(t)) = ...
            -1;


        A(row,idxADP(t)) = ...
            -Rp(s,t);


        A(row,idxADN(t)) = ...
            Rn(s,t);

    end

end


%% ============================================================
% 变量上下界
%% ============================================================

lb = ...
    zeros(nVar,1);


ub = ...
    inf(nVar,1);


ub(idxC0) = ...
    Wmax;


ub(idxD0) = ...
    Wmax;


ub([
    idxACP
    idxACN
    idxADP
    idxADN
    ]) = ...
    1;


lb(idxEbase) = ...
    Emin;


ub(idxEbase) = ...
    Emax;


lb(idxE(:)) = ...
    Emin;


ub(idxE(:)) = ...
    Emax;


if ~isInitial

    ub(idxDec) = ...
        g0Remain;

end


%% ------------------------------------------------------------
% 最后一天若强制24:00回6000
%% ------------------------------------------------------------

if forceFinalToday

    midnightState = ...
        qCurrent+1;


    lb(idxEbase(midnightState)) = ...
        Efinal;


    ub(idxEbase(midnightState)) = ...
        Efinal;


    for s = 1:K

        lb(idxE(s,midnightState)) = ...
            Efinal;


        ub(idxE(s,midnightState)) = ...
            Efinal;

    end

end


%% ============================================================
% 求解
%% ============================================================

[x,fval,exitflag,output] = ...
    linprog( ...
    f, ...
    A,b, ...
    Aeq,beq, ...
    lb,ub, ...
    options);


if exitflag<=0

    error( ...
        'Similar10滚动LP失败：%s', ...
        output.message);

end


%% ============================================================
% 约束检查
%% ============================================================

eqViolation = ...
    max( ...
    abs( ...
    Aeq*x-beq));


ineqViolation = ...
    max( ...
    [ ...
    A*x-b; ...
    0 ...
    ]);


boundViolation = ...
    max( ...
    [ ...
    lb-x; ...
    x-ub; ...
    0 ...
    ]);


maxViolation = ...
    max( ...
    [ ...
    eqViolation; ...
    ineqViolation; ...
    boundViolation ...
    ]);


%% ============================================================
% 只返回今天剩余计划
%% ============================================================

P.currentGrid = ...
    x(idxG(1:qCurrent));


P.currentChargeBase = ...
    x(idxC0(1:qCurrent));


P.currentDischargeBase = ...
    x(idxD0(1:qCurrent));


P.objective = ...
    fval;


P.maxConstraintViolation = ...
    maxViolation;


end


%% ============================================================
% 局部函数5
%
% 实际严格因果回放
%% ============================================================

function A = replayActualBlockWithBase( ...
    Pload, ...
    Ppv, ...
    Wgrid, ...
    WchPlan, ...
    WdisPlan, ...
    Estart, ...
    globalSlots, ...
    forceFinalToday, ...
    Efinal, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax)


dt = ...
    1/6;


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Ppv(:)*dt;


Wgrid = ...
    Wgrid(:);


WchPlan = ...
    WchPlan(:);


WdisPlan = ...
    WdisPlan(:);


N = ...
    length(Wgrid);


Wch = ...
    zeros(N,1);


Wdis = ...
    zeros(N,1);


Wem = ...
    zeros(N,1);


Wsur = ...
    zeros(N,1);


E = ...
    zeros(N+1,1);


E(1) = ...
    Estart;


for j = 1:N

    ec = ...
        E(j);


    tGlobal = ...
        globalSlots(j);


    %% --------------------------------------------------------
    % 为强制年末SOC预留可达区间
    %% --------------------------------------------------------

    if forceFinalToday

        remainingSlots = ...
            144-tGlobal;


        nextLow = ...
            max( ...
            Emin, ...
            Efinal ...
            -remainingSlots*eta*Wmax);


        nextHigh = ...
            min( ...
            Emax, ...
            Efinal ...
            +remainingSlots*Wmax/eta);

    else

        nextLow = ...
            Emin;


        nextHigh = ...
            Emax;

    end


    %% --------------------------------------------------------
    % 基础充放电计划
    %% --------------------------------------------------------

    c = ...
        min( ...
        max(WchPlan(j),0), ...
        Wmax);


    d = ...
        min( ...
        max(WdisPlan(j),0), ...
        Wmax);


    en = ...
        ec ...
        +eta*c ...
        -d/eta;


    %% SOC过低：先减放电
    if en<nextLow

        rd = ...
            min( ...
            d, ...
            (nextLow-en)*eta);


        d = ...
            d-rd;


        en = ...
            ec ...
            +eta*c ...
            -d/eta;

    end


    %% SOC过高：先减充电
    if en>nextHigh

        rc = ...
            min( ...
            c, ...
            (en-nextHigh)/eta);


        c = ...
            c-rc;


        en = ...
            ec ...
            +eta*c ...
            -d/eta;

    end


    %% --------------------------------------------------------
    % 当前真实缺口
    %% --------------------------------------------------------

    residual = ...
        Wload(j) ...
        -Wpv(j) ...
        -Wgrid(j) ...
        -(d-c);


    %% ========================================================
    % 缺电：
    % 先减少充电
    % 再增加放电
    % 最后紧急购电
    %% ========================================================

    if residual>1e-12

        reduceCharge = ...
            min( ...
            [ ...
            residual, ...
            c, ...
            max( ...
            (en-nextLow)/eta, ...
            0) ...
            ]);


        c = ...
            c-reduceCharge;


        residual = ...
            residual-reduceCharge;


        en = ...
            en ...
            -eta*reduceCharge;


        if residual>1e-12

            extraDis = ...
                min( ...
                [ ...
                residual, ...
                Wmax-d, ...
                eta*max(en-nextLow,0) ...
                ]);


            d = ...
                d+extraDis;


            residual = ...
                residual-extraDis;


            en = ...
                en ...
                -extraDis/eta;

        end


        Wem(j) = ...
            max(residual,0);


    %% ========================================================
    % 富余：
    % 先减少放电
    % 再增加充电
    % 最后弃电
    %% ========================================================

    elseif residual<-1e-12

        surplus = ...
            -residual;


        reduceDis = ...
            min( ...
            [ ...
            surplus, ...
            d, ...
            eta*max(nextHigh-en,0) ...
            ]);


        d = ...
            d-reduceDis;


        surplus = ...
            surplus-reduceDis;


        en = ...
            en ...
            +reduceDis/eta;


        if surplus>1e-12

            extraCh = ...
                min( ...
                [ ...
                surplus, ...
                Wmax-c, ...
                max(nextHigh-en,0)/eta ...
                ]);


            c = ...
                c+extraCh;


            surplus = ...
                surplus-extraCh;


            en = ...
                en ...
                +eta*extraCh;

        end


        Wsur(j) = ...
            max(surplus,0);

    end


    Enew = ...
        ec ...
        +eta*c ...
        -d/eta;


    if Enew<nextLow-1e-6 ...
            ||Enew>nextHigh+1e-6

        error( ...
            '实际回放SOC越界：slot=%d SOC=%.9f', ...
            tGlobal, ...
            Enew);

    end


    Wch(j) = ...
        c;


    Wdis(j) = ...
        d;


    E(j+1) = ...
        Enew;

end


A.Wch = ...
    Wch;


A.Wdis = ...
    Wdis;


A.Wem = ...
    Wem;


A.Wsur = ...
    Wsur;


A.E = ...
    E;


A.Eend = ...
    E(end);


end


%% ============================================================
% 局部函数6
% PV动态融合标定库
%% ============================================================

function L = buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll)


nRec = ...
    length(F.dates);


formal = ...
    nan(nRec,144);


history = ...
    nan(nRec,144);


actual = ...
    nan(nRec,144);


complete = ...
    false(nRec,1);


for i = 1:nRec

    d = ...
        find( ...
        dateAll==F.dates(i), ...
        1);


    if isempty(d) ...
            ||d<=3

        continue;

    end


    hIssue = ...
        F.issueHour(i);


    actual24 = ...
        extractActual24( ...
        pvAll, ...
        d, ...
        hIssue);


    if isempty(actual24)

        continue;

    end


    formal24 = ...
        makeFormalPV24( ...
        F, ...
        pvAll, ...
        dateAll, ...
        d, ...
        hIssue);


    history24 = ...
        makeHistoryPV24( ...
        pvAll, ...
        d, ...
        hIssue);


    formal(i,:) = ...
        formal24';


    history(i,:) = ...
        history24';


    actual(i,:) = ...
        actual24';


    complete(i) = ...
        all(isfinite(formal(i,:))) ...
        &&all(isfinite(history(i,:))) ...
        &&all(isfinite(actual(i,:)));

end


L.date = ...
    F.dates;


L.issueHour = ...
    F.issueHour;


L.issueTime = ...
    F.issueTime;


L.formal = ...
    formal;


L.history = ...
    history;


L.actual = ...
    actual;


L.complete = ...
    complete;


end


%% ============================================================
% 局部函数7
% PV动态融合权重
%% ============================================================

function [w,nHistory] = getRollingPVBlendWeight( ...
    L, ...
    issueHour, ...
    currentTime, ...
    windowN, ...
    minHistory)


valid = ...
    L.complete ...
    &L.issueHour==issueHour ...
    &( ...
    L.issueTime+hours(24) ...
    <=currentTime);


rows = ...
    find(valid);


if isempty(rows)

    w = ...
        1;


    nHistory = ...
        0;


    return;

end


[~,ord] = ...
    sort(L.issueTime(rows));


rows = ...
    rows(ord);


firstKeep = ...
    max( ...
    1, ...
    length(rows)-windowN+1);


rows = ...
    rows(firstKeep:end);


nHistory = ...
    length(rows);


if nHistory<minHistory

    w = ...
        1;


    return;

end


formal = ...
    L.formal(rows,:);


history = ...
    L.history(rows,:);


actual = ...
    L.actual(rows,:);


formal = ...
    formal(:);


history = ...
    history(:);


actual = ...
    actual(:);


good = ...
    isfinite(formal) ...
    &isfinite(history) ...
    &isfinite(actual);


formal = ...
    formal(good);


history = ...
    history(good);


actual = ...
    actual(good);


den = ...
    sum( ...
    (formal-history).^2);


if isempty(actual) ...
        ||den<1e-12

    w = ...
        1;


    return;

end


w = ...
    sum( ...
    (actual-history) ...
    .*(formal-history)) ...
    /den;


w = ...
    min( ...
    max(w,0), ...
    1);


end


%% ============================================================
% 局部函数8
% 正式PV 24h预测
%% ============================================================

function formal24 = makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour)


date0 = ...
    dateAll(d);


id = ...
    find( ...
    F.dates==date0 ...
    &F.issueHour==issueHour, ...
    1);


if isempty(id)

    error( ...
        '找不到%s %02d时附件3预测。', ...
        string(date0), ...
        issueHour);

end


anchor = ...
    observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour);


%% 0h,1h,...,24h
xSlot = ...
    0:6:144;


%% 未来00:10...24h
querySlot = ...
    1:144;


formal24 = ...
    interp1( ...
    xSlot, ...
    [ ...
    anchor, ...
    F.forecast(id,:) ...
    ], ...
    querySlot, ...
    'linear')';


formal24 = ...
    max(formal24,0);


end


%% ============================================================
% 局部函数9
% PV正式+历史动态融合
%% ============================================================

function pv24 = makeOfficialPV24Blend( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    w)


formal24 = ...
    makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour);


history24 = ...
    makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour);


pv24 = ...
    w*formal24 ...
    +(1-w)*history24;


pv24 = ...
    max(pv24,0);


end


%% ============================================================
% 局部函数10
% 前3日同发布时间实际PV平均
%% ============================================================

function history24 = makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour)


paths = ...
    zeros(144,3);


for k = 1:3

    histDay = ...
        d-k;


    onePath = ...
        extractActual24( ...
        pvAll, ...
        histDay, ...
        issueHour);


    if isempty(onePath)

        error( ...
            '历史PV 24h路径不足。');

    end


    paths(:,k) = ...
        onePath;

end


history24 = ...
    mean(paths,2);


end


%% ============================================================
% 局部函数11
% 当前发布时间真实PV锚点
%% ============================================================

function value = observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour)


if issueHour==0

    if d<=1

        error( ...
            '第1天无法获取前一天0时锚点。');

    end


    value = ...
        pvAll(d-1,144);

else

    issueCol = ...
        issueHour*6;


    value = ...
        pvAll(d,issueCol);

end


end


%% ============================================================
% 局部函数12
% 提取真实未来24h
%% ============================================================

function path = extractActual24( ...
    data, ...
    d, ...
    issueHour)


startSlot = ...
    issueHour*6+1;


if issueHour==0

    path = ...
        data(d,:)';


elseif d<size(data,1)

    todayPart = ...
        data( ...
        d, ...
        startSlot:end);


    nextPart = ...
        data( ...
        d+1, ...
        1:startSlot-1);


    path = ...
        [ ...
        todayPart, ...
        nextPart ...
        ]';

else

    path = ...
        [];

end


end


%% ============================================================
% 局部函数13
% 附件3读取
%% ============================================================

function F = readForecastSingleSheet( ...
    filename, ...
    sheetName)


C = ...
    readcell( ...
    filename, ...
    'Sheet',sheetName);


[nRow,nCol] = ...
    size(C);


headerRow = ...
    NaN;


for r = 1:min(nRow,30)

    for c = 1:nCol

        txt = ...
            replace( ...
            strtrim( ...
            string(C{r,c})), ...
            " ", ...
            "");


        if txt=="预报1小时" ...
                ||txt=="预测1小时"

            headerRow = ...
                r;

            break;

        end

    end


    if ~isnan(headerRow)

        break;

    end

end


if isnan(headerRow)

    error( ...
        '附件3找不到预报表头。');

end


dateCol = ...
    NaN;


issueCol = ...
    NaN;


for c = 1:nCol

    txt = ...
        replace( ...
        strtrim( ...
        string(C{headerRow,c})), ...
        " ", ...
        "");


    if contains(txt,"日期")

        dateCol = ...
            c;

    end


    if contains(txt,"预报时刻") ...
            ||contains(txt,"预测时刻")

        issueCol = ...
            c;

    end

end


forecastCols = ...
    nan(1,24);


for h = 1:24

    for c = 1:nCol

        txt = ...
            replace( ...
            strtrim( ...
            string(C{headerRow,c})), ...
            " ", ...
            "");


        if txt==sprintf('预报%d小时',h) ...
                ||txt==sprintf('预测%d小时',h)

            forecastCols(h) = ...
                c;

            break;

        end

    end


    if isnan(forecastCols(h))

        error( ...
            '附件3缺少第%d小时预测列。', ...
            h);

    end

end


maxN = ...
    nRow-headerRow;


dates = ...
    NaT(maxN,1);


issueHour = ...
    nan(maxN,1);


forecast = ...
    nan(maxN,24);


count = ...
    0;


currentDate = ...
    NaT;


for r = headerRow+1:nRow

    newDate = ...
        parseOneDate( ...
        C{r,dateCol});


    if ~isnat(newDate)

        currentDate = ...
            dateshift( ...
            newDate, ...
            'start','day');

    end


    if isnat(currentDate)

        continue;

    end


    hIssue = ...
        parseIssueHour( ...
        C{r,issueCol});


    if isnan(hIssue) ...
            ||~ismember( ...
            hIssue, ...
            [0,6,12,18])

        continue;

    end


    vals = ...
        nan(1,24);


    for h = 1:24

        vals(h) = ...
            valueToDouble( ...
            C{r,forecastCols(h)});

    end


    if all(isnan(vals))

        continue;

    end


    count = ...
        count+1;


    dates(count) = ...
        currentDate;


    issueHour(count) = ...
        hIssue;


    forecast(count,:) = ...
        vals;

end


dates = ...
    dates(1:count);


issueHour = ...
    issueHour(1:count);


forecast = ...
    forecast(1:count,:);


T = ...
    table( ...
    dates, ...
    issueHour, ...
    (1:count)', ...
    'VariableNames',{ ...
    'Date','Hour','ID'} ...
    );


T = ...
    sortrows( ...
    T, ...
    {'Date','Hour'} ...
    );


id = ...
    T.ID;


F.dates = ...
    dates(id);


F.issueHour = ...
    issueHour(id);


F.forecast = ...
    forecast(id,:);


F.issueTime = ...
    F.dates ...
    +hours(F.issueHour);


end


%% ============================================================
% 局部函数14
% 日期解析
%% ============================================================

function d = parseOneDate(x)


d = ...
    NaT;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isdatetime(x)

    if ~isnat(x)

        d = ...
            x(1);

    end


    return;

end


if isnumeric(x)

    if isempty(x) ...
            ||isnan(x)

        return;

    end


    try

        d = ...
            datetime( ...
            x, ...
            'ConvertFrom','excel');

        return;

    catch
    end

end


s = ...
    strtrim(string(x));


if ismissing(s) ...
        ||strlength(s)==0

    return;

end


try

    d = ...
        datetime(s);

catch

    d = ...
        NaT;

end


end


%% ============================================================
% 局部函数15
% 发布时间解析
%% ============================================================

function h = parseIssueHour(x)


h = ...
    NaN;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isduration(x)

    h = ...
        mod( ...
        round(hours(x)), ...
        24);

    return;

end


if isdatetime(x)

    if ~isnat(x)

        h = ...
            hour(x);

    end

    return;

end


if isnumeric(x)

    if isempty(x) ...
            ||isnan(x)

        return;

    end


    if x>=0 ...
            &&x<1

        h = ...
            mod( ...
            round(24*x), ...
            24);

        return;

    end


    if x>=0 ...
            &&x<=24

        h = ...
            round(x);


        if h==24

            h = ...
                0;

        end

        return;

    end

end


s = ...
    strtrim(string(x));


token = ...
    regexp( ...
    char(s), ...
    '(\d{1,2})\s*:', ...
    'tokens','once');


if ~isempty(token)

    h = ...
        mod( ...
        str2double(token{1}), ...
        24);

end


end


%% ============================================================
% 局部函数16
% 单元格转数值
%% ============================================================

function y = valueToDouble(x)


y = ...
    NaN;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isnumeric(x)

    if ~isempty(x)

        y = ...
            double(x(1));

    end

    return;

end


if islogical(x)

    y = ...
        double(x);

    return;

end


s = ...
    strtrim(string(x));


if ismissing(s) ...
        ||strlength(s)==0

    return;

end


y = ...
    str2double(s);


end


%% ============================================================
% 局部函数17
% 紧急购电连续时间段
%% ============================================================

function txt = makeEmergencyTimeRange(s,e)


startMinute = ...
    10*(s-1);


endMinute = ...
    10*e;


txt = ...
    sprintf( ...
    '%s-%s', ...
    formatResult3Time(startMinute), ...
    formatResult3Time(endMinute));


end


%% ============================================================
% 局部函数18
% 分钟转时间文字
%% ============================================================

function txt = formatResult3Time(totalMinute)


dayAdd = ...
    floor(totalMinute/1440);


minuteOfDay = ...
    mod(totalMinute,1440);


hh = ...
    floor(minuteOfDay/60);


mm = ...
    mod(minuteOfDay,60);


if dayAdd==0

    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh,mm);

else

    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh,mm);

end


end