%% ============================================================
% 2026 C题 问题4-2
%
% 波动实时电价下重新计算问题2
%
% ============================================================
% 核心：
%
% 1. 复用问题2已经训练完成的4种负载预测、4种光伏预测
% 2. 不重新训练预测模型
% 3. 重新跑4×4=16种预测组合
% 4. 问题2Q0.8净负荷风险校准保持不变
% 5. 实时电价预测：
%
%       kL = 1
%       kS = 2
%
%    预测电价
%    =
%    最近1个同星期日的日均价
%    ×
%    最近2个同星期日平均日内相对形状
%
% 6. 每天0:00制定计划：
%       LP目标函数使用“预测实时电价”
%
% 7. 最终实际结算：
%       计划购电 × 附件4真实实时电价
%
% 8. 紧急购电：
%       5 × 附件4真实实时电价
%
% 9. TIMEFIX：
%       附件2、附件4、预测均保持原始144列顺序
%       不进行 [144,1:143]
%
% 10. 最终自动写入：
%
% E:\数模\2026年正式比赛\CUMCM2026Problems\C题\附件\
% 附件5\result4-2.xlsx
%
%% ============================================================

clear;
clc;
close all;

rng(20260912,'twister');


fprintf('====================================================\n');
fprintf(' C题问题4-2：波动电价下重新计算问题2\n');
fprintf(' TIMEFIX + 电价预测 + 16组合重新经济筛选\n');
fprintf('====================================================\n\n');


%% ============================================================
% 0. 参数
%% ============================================================

FORCE_FINAL_SOC_6000 = false;

Q_LEVEL = 0.80;

ROLLING_WINDOW_DAYS = 30;

MIN_HISTORY_DAYS = 7;


%% 实时电价预测最终参数

PRICE_KL = 1;

PRICE_KS = 2;


%% ============================================================
% 1. 路径
%% ============================================================

baseDir = ...
    'E:\数模\2026年正式比赛\CUMCM2026Problems\C题\附件';


actualFile = ...
    fullfile( ...
    baseDir, ...
    '附件2.xlsx');


price4File = ...
    fullfile( ...
    baseDir, ...
    '附件4.xlsx');


predictionFile = ...
    fullfile( ...
    baseDir, ...
    'Q2_16combo_4models_predictions.mat');


result4File = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    'result4-2.xlsx');


resultMatFile = ...
    fullfile( ...
    baseDir, ...
    'Q4_2_TIMEFIX_FINAL_results.mat');


resultExcelFile = ...
    fullfile( ...
    baseDir, ...
    'Q4_2_TIMEFIX_analysis.xlsx');


dispatchCheckpoint = ...
    fullfile( ...
    baseDir, ...
    'Q4_2_TIMEFIX_dispatch_checkpoint.mat');


heatmapFile = ...
    fullfile( ...
    baseDir, ...
    'Q4_2_TIMEFIX_16组合总成本热力图.png');


%% ============================================================
% 2. 文件检查
%% ============================================================

filesNeed = {
    actualFile
    price4File
    predictionFile
    result4File
    };


for i = 1:length(filesNeed)

    if ~isfile(filesNeed{i})

        error( ...
            '找不到文件：\n%s', ...
            filesNeed{i});

    end

end


%% ============================================================
% 3. 日期
%% ============================================================

datesAll = ...
    ( ...
    datetime(2025,1,1): ...
    days(1): ...
    datetime(2025,12,31) ...
    )';


targetDays = ...
    32:365;


predDates = ...
    datesAll(targetDays);


nPredDay = ...
    length(targetDays);


nTime = ...
    144;


%% ============================================================
% 4. 读取附件2
%
% TIMEFIX：
% 保持原始144列顺序
%% ============================================================

fprintf('读取附件2负载和光伏...\n');


loadRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','小区负载', ...
    'Range','B2:EO366');


pvRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','光伏发电实际功率', ...
    'Range','B2:EO366');


if ~isequal(size(loadRaw),[365,144])

    error('负载数据不是365×144。');

end


if ~isequal(size(pvRaw),[365,144])

    error('光伏数据不是365×144。');

end


if any(~isfinite(loadRaw),'all') ...
        || any(~isfinite(pvRaw),'all')

    error('附件2存在NaN或非有限值。');

end


actualLoadRun = ...
    loadRaw(targetDays,:);


actualPVRun = ...
    pvRaw(targetDays,:);


actualNetRun = ...
    actualLoadRun ...
    -actualPVRun;


%% ============================================================
% 5. 读取问题2四模型预测
%
% 不重新训练
%% ============================================================

fprintf('读取问题2已有四模型预测...\n');


P = ...
    load(predictionFile);


if ~isfield(P,'predLoad') ...
        || ~isfield(P,'predPV') ...
        || ~isfield(P,'modelNames')

    error( ...
        '预测文件缺少predLoad、predPV或modelNames。');

end


predLoadRun = ...
    P.predLoad;


predPVRun = ...
    P.predPV;


modelNames = ...
    string(P.modelNames(:));


if ~isequal(size(predLoadRun),[334,144,4])

    error('predLoad尺寸异常。');

end


if ~isequal(size(predPVRun),[334,144,4])

    error('predPV尺寸异常。');

end


nModel = ...
    length(modelNames);


nCombo = ...
    nModel*nModel;


fprintf('预测缓存读取成功，不重新训练。\n\n');


%% ============================================================
% 6. 读取附件4真实实时电价
%
% TIMEFIX：
% 原始365×144直接使用
%% ============================================================

fprintf('读取附件4实时电价...\n');


priceSheets = ...
    sheetnames(price4File);


priceAll = ...
    readmatrix( ...
    price4File, ...
    'Sheet',priceSheets(1), ...
    'Range','B2:EO366');


if ~isequal(size(priceAll),[365,144])

    error( ...
        '附件4电价读取结果不是365×144。');

end


if any(~isfinite(priceAll),'all') ...
        || any(priceAll<0,'all')

    error( ...
        '附件4存在非法电价。');

end


%% 真实结算电价

actualPriceRun = ...
    priceAll(targetDays,:);


%% ============================================================
% 7. 严格因果实时电价预测
%
% kL=1：
% 最近1个同星期日的日均价
%
% kS=2：
% 最近2个同星期日的平均相对形状
%% ============================================================

fprintf('生成严格因果实时电价预测...\n');


priceForecastRun = ...
    nan( ...
    nPredDay, ...
    nTime);


for kd = 1:nPredDay

    d = ...
        targetDays(kd);


    targetWD = ...
        weekday( ...
        datesAll(d));


    histDays = ...
        1:(d-1);


    histWD = ...
        arrayfun( ...
        @(x) ...
        weekday(datesAll(x)), ...
        histDays);


    sameDays = ...
        histDays( ...
        histWD==targetWD);


    if length(sameDays)<max(PRICE_KL,PRICE_KS)

        error( ...
            '%s以前同星期日历史不足。', ...
            string(datesAll(d)));

    end


    %% --------------------------------------------------------
    % 日均价
    %% --------------------------------------------------------

    meanDays = ...
        sameDays( ...
        end-PRICE_KL+1:end);


    predDailyMean = ...
        mean( ...
        mean( ...
        priceAll(meanDays,:), ...
        2));


    %% --------------------------------------------------------
    % 日内相对形状
    %% --------------------------------------------------------

    shapeDays = ...
        sameDays( ...
        end-PRICE_KS+1:end);


    shapeMatrix = ...
        zeros( ...
        PRICE_KS, ...
        nTime);


    for k = 1:PRICE_KS

        onePrice = ...
            priceAll( ...
            shapeDays(k), ...
            :);


        oneMean = ...
            mean(onePrice);


        shapeMatrix(k,:) = ...
            onePrice ...
            /oneMean;

    end


    predShape = ...
        mean( ...
        shapeMatrix, ...
        1);


    %% --------------------------------------------------------
    % 最终144点预测
    %% --------------------------------------------------------

    priceForecastRun(kd,:) = ...
        max( ...
        predDailyMean ...
        .*predShape, ...
        0);

end


%% ============================================================
% 8. 电价预测检查
%% ============================================================

priceError = ...
    priceForecastRun ...
    -actualPriceRun;


priceMAE = ...
    mean( ...
    abs(priceError), ...
    'all');


priceRMSE = ...
    sqrt( ...
    mean( ...
    priceError.^2, ...
    'all'));


priceBias = ...
    mean( ...
    priceError, ...
    'all');


fprintf('\n');
fprintf('====================================================\n');
fprintf(' 实时电价预测结果\n');
fprintf('====================================================\n');


fprintf( ...
    'kL = %d\n', ...
    PRICE_KL);


fprintf( ...
    'kS = %d\n', ...
    PRICE_KS);


fprintf( ...
    'MAE = %.6f 元/kWh\n', ...
    priceMAE);


fprintf( ...
    'RMSE = %.6f 元/kWh\n', ...
    priceRMSE);


fprintf( ...
    'Bias = %+.6f 元/kWh\n', ...
    priceBias);


fprintf('====================================================\n\n');


%% ============================================================
% 9. 储能参数
%% ============================================================

dt = ...
    10/60;


eta_ch = ...
    0.90;


eta_dis = ...
    0.90;


Ecapacity = ...
    12000;


Emin = ...
    1200;


Emax = ...
    10800;


Einitial = ...
    6000;


EfinalTarget = ...
    6000;


Pmax = ...
    5000;


Wmax = ...
    Pmax*dt;


emergencyFactor = ...
    5;


cyclePenalty = ...
    0;


curtailPenalty = ...
    1e-5;


%% ============================================================
% 10. LP
%% ============================================================

lpOptions = ...
    optimoptions( ...
    'linprog', ...
    'Algorithm','dual-simplex-highs', ...
    'Display','none');


%% ============================================================
% 11. 16组合
%% ============================================================

comboLoadIdx = ...
    zeros(nCombo,1);


comboPVIdx = ...
    zeros(nCombo,1);


comboName = ...
    strings(nCombo,1);


c = ...
    1;


for i = 1:nModel

    for j = 1:nModel

        comboLoadIdx(c) = ...
            i;


        comboPVIdx(c) = ...
            j;


        comboName(c) = ...
            "L-" ...
            +modelNames(i) ...
            +" + PV-" ...
            +modelNames(j);


        c = ...
            c+1;

    end

end


LoadModel = ...
    modelNames(comboLoadIdx);


PVModel = ...
    modelNames(comboPVIdx);


%% ============================================================
% 12. 初始化
%% ============================================================

planGridAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


planChargeAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


planDischargeAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


planCurtailAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


actualChargeAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


actualDischargeAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


actualSpillAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


emergencyAll = ...
    zeros( ...
    nPredDay, ...
    nTime, ...
    nCombo);


SOCstartAll = ...
    zeros( ...
    nPredDay, ...
    nCombo);


SOCendAll = ...
    zeros( ...
    nPredDay, ...
    nCombo);


%% 计划阶段预测价格下的目标费用

PredictedPlanCostDayAll = ...
    zeros( ...
    nPredDay, ...
    nCombo);


%% 真正结算的计划购电费用

ActualPlanCostDayAll = ...
    zeros( ...
    nPredDay, ...
    nCombo);


EmergencyCostDayAll = ...
    zeros( ...
    nPredDay, ...
    nCombo);


q80MeanCombo = ...
    zeros(nCombo,1);


CorrectedNet_MAE = ...
    zeros(nCombo,1);


%% ============================================================
% 13. 调度断点
%% ============================================================

lastCombo = ...
    0;


if isfile(dispatchCheckpoint)

    D = ...
        load(dispatchCheckpoint);


    if isfield(D,'lastCombo') ...
            && isfield(D,'planGridAll') ...
            && isequal( ...
            size(D.planGridAll), ...
            size(planGridAll))

        lastCombo = ...
            D.lastCombo;


        planGridAll = ...
            D.planGridAll;


        planChargeAll = ...
            D.planChargeAll;


        planDischargeAll = ...
            D.planDischargeAll;


        planCurtailAll = ...
            D.planCurtailAll;


        actualChargeAll = ...
            D.actualChargeAll;


        actualDischargeAll = ...
            D.actualDischargeAll;


        actualSpillAll = ...
            D.actualSpillAll;


        emergencyAll = ...
            D.emergencyAll;


        SOCstartAll = ...
            D.SOCstartAll;


        SOCendAll = ...
            D.SOCendAll;


        PredictedPlanCostDayAll = ...
            D.PredictedPlanCostDayAll;


        ActualPlanCostDayAll = ...
            D.ActualPlanCostDayAll;


        EmergencyCostDayAll = ...
            D.EmergencyCostDayAll;


        q80MeanCombo = ...
            D.q80MeanCombo;


        CorrectedNet_MAE = ...
            D.CorrectedNet_MAE;


        fprintf( ...
            '恢复Q4-2断点：组合%d/16\n', ...
            lastCombo);

    end

else

    fprintf( ...
        '未发现Q4-2断点，从组合1开始。\n');

end


%% ============================================================
% 14. 逐组合重新调度
%% ============================================================

ticDispatch = ...
    tic;


for combo = (lastCombo+1):nCombo

    iLoad = ...
        comboLoadIdx(combo);


    iPV = ...
        comboPVIdx(combo);


    fprintf('\n');
    fprintf('####################################################\n');

    fprintf( ...
        ' Q4-2组合 %02d / 16\n', ...
        combo);

    fprintf( ...
        ' 负载：%s\n', ...
        modelNames(iLoad));

    fprintf( ...
        ' 光伏：%s\n', ...
        modelNames(iPV));

    fprintf('####################################################\n');


    %% ========================================================
    % 原始净负荷预测
    %% ========================================================

    loadForecastRaw = ...
        predLoadRun(:,:,iLoad);


    pvForecast = ...
        predPVRun(:,:,iPV);


    forecastNet = ...
        loadForecastRaw ...
        -pvForecast;


    residualNet = ...
        actualNetRun ...
        -forecastNet;


    %% ========================================================
    % Q0.8严格因果校准
    %% ========================================================

    q80Correction = ...
        zeros( ...
        nPredDay, ...
        nTime);


    calibrationActive = ...
        false( ...
        nPredDay, ...
        1);


    for d = 1:nPredDay

        histEnd = ...
            d-1;


        histStart = ...
            max( ...
            1, ...
            d-ROLLING_WINDOW_DAYS);


        if histEnd<histStart

            continue;

        end


        nHist = ...
            histEnd-histStart+1;


        if nHist<MIN_HISTORY_DAYS

            continue;

        end


        calibrationActive(d) = ...
            true;


        for t = 1:nTime

            r = ...
                residualNet( ...
                histStart:histEnd, ...
                t);


            r = ...
                r(isfinite(r));


            if length(r)>=MIN_HISTORY_DAYS

                q80Correction(d,t) = ...
                    quantile( ...
                    r, ...
                    Q_LEVEL);

            end

        end

    end


    correctedNet = ...
        forecastNet ...
        +q80Correction;


    correctedLoad = ...
        max( ...
        correctedNet ...
        +pvForecast, ...
        0);


    qUse = ...
        q80Correction( ...
        repmat( ...
        calibrationActive, ...
        1,nTime));


    if isempty(qUse)

        q80MeanCombo(combo) = ...
            0;

    else

        q80MeanCombo(combo) = ...
            mean(qUse);

    end


    eCorr = ...
        correctedNet ...
        -actualNetRun;


    CorrectedNet_MAE(combo) = ...
        mean( ...
        abs(eCorr), ...
        'all');


    %% ========================================================
    % 全年运行
    %% ========================================================

    Ecurrent = ...
        Einitial;


    for d = 1:nPredDay

        if mod(d-1,30)==0 ...
                || d==nPredDay

            fprintf( ...
                '  Day %03d/%03d\n', ...
                d,nPredDay);

        end


        EdayStart = ...
            Ecurrent;


        SOCstartAll(d,combo) = ...
            EdayStart;


        isLastDay = ...
            d==nPredDay;


        if isLastDay ...
                && FORCE_FINAL_SOC_6000

            terminalLow = ...
                EfinalTarget;


            terminalHigh = ...
                EfinalTarget;

        else

            terminalLow = ...
                Emin;


            terminalHigh = ...
                Emax;

        end


        %% ----------------------------------------------------
        % 当日预测
        %% ----------------------------------------------------

        loadForecast = ...
            correctedLoad(d,:)';


        pvForecastDay = ...
            pvForecast(d,:)';


        %% ----------------------------------------------------
        % ★计划优化使用预测实时电价
        %% ----------------------------------------------------

        predictedPriceDay = ...
            priceForecastRun(d,:)';


        %% ----------------------------------------------------
        % ★最终结算使用附件4真实实时电价
        %% ----------------------------------------------------

        actualPriceDay = ...
            actualPriceRun(d,:)';


        %% ====================================================
        % 日前计划
        %% ====================================================

        plan = ...
            solveDailyPlanTerminalSOC( ...
            loadForecast, ...
            pvForecastDay, ...
            predictedPriceDay, ...
            EdayStart, ...
            terminalLow, ...
            terminalHigh, ...
            dt, ...
            eta_ch, ...
            eta_dis, ...
            Emin, ...
            Emax, ...
            Wmax, ...
            cyclePenalty, ...
            curtailPenalty, ...
            lpOptions);


        planGridAll(d,:,combo) = ...
            plan.Wgrid';


        planChargeAll(d,:,combo) = ...
            plan.Wch';


        planDischargeAll(d,:,combo) = ...
            plan.Wdis';


        planCurtailAll(d,:,combo) = ...
            plan.Wcut';


        %% ----------------------------------------------------
        % 优化时认为的购电成本
        %% ----------------------------------------------------

        PredictedPlanCostDayAll(d,combo) = ...
            sum( ...
            predictedPriceDay ...
            .*plan.Wgrid);


        %% ----------------------------------------------------
        % 最后真正结算的计划购电费
        %% ----------------------------------------------------

        ActualPlanCostDayAll(d,combo) = ...
            sum( ...
            actualPriceDay ...
            .*plan.Wgrid);


        %% ====================================================
        % 实际严格因果回放
        %% ====================================================

        replay = ...
            replayActualDayCausalAllowSimultaneous( ...
            actualLoadRun(d,:)', ...
            actualPVRun(d,:)', ...
            plan.Wgrid, ...
            plan.Wch, ...
            plan.Wdis, ...
            EdayStart, ...
            dt, ...
            eta_ch, ...
            eta_dis, ...
            Emin, ...
            Emax, ...
            Wmax, ...
            isLastDay ...
                && FORCE_FINAL_SOC_6000, ...
            EfinalTarget);


        actualChargeAll(d,:,combo) = ...
            replay.Wch';


        actualDischargeAll(d,:,combo) = ...
            replay.Wdis';


        actualSpillAll(d,:,combo) = ...
            replay.Wspill';


        emergencyAll(d,:,combo) = ...
            replay.Wem';


        %% ----------------------------------------------------
        % 紧急购电：
        % 真实交易时刻价格 × 5
        %% ----------------------------------------------------

        EmergencyCostDayAll(d,combo) = ...
            5 ...
            *sum( ...
            actualPriceDay ...
            .*replay.Wem);


        Ecurrent = ...
            replay.Eend;


        SOCendAll(d,combo) = ...
            Ecurrent;

    end


    fprintf('\n');

    fprintf( ...
        '当前组合真实计划购电费：%.2f 元\n', ...
        sum( ...
        ActualPlanCostDayAll(:,combo)));


    fprintf( ...
        '紧急购电费：%.2f 元\n', ...
        sum( ...
        EmergencyCostDayAll(:,combo)));


    fprintf( ...
        '总成本：%.2f 元\n', ...
        sum( ...
        ActualPlanCostDayAll(:,combo)) ...
        +sum( ...
        EmergencyCostDayAll(:,combo)));


    %% ========================================================
    % 保存断点
    %% ========================================================

    lastCombo = ...
        combo;


    save( ...
        dispatchCheckpoint, ...
        'lastCombo', ...
        'planGridAll', ...
        'planChargeAll', ...
        'planDischargeAll', ...
        'planCurtailAll', ...
        'actualChargeAll', ...
        'actualDischargeAll', ...
        'actualSpillAll', ...
        'emergencyAll', ...
        'SOCstartAll', ...
        'SOCendAll', ...
        'PredictedPlanCostDayAll', ...
        'ActualPlanCostDayAll', ...
        'EmergencyCostDayAll', ...
        'q80MeanCombo', ...
        'CorrectedNet_MAE', ...
        '-v7.3');

end


dispatchTime = ...
    toc(ticDispatch);


%% ============================================================
% 15. 汇总16组合
%% ============================================================

PlanEnergy_kWh = ...
    zeros(nCombo,1);


EmergencyEnergy_kWh = ...
    zeros(nCombo,1);


ActualPlanCost_yuan = ...
    zeros(nCombo,1);


EmergencyCost_yuan = ...
    zeros(nCombo,1);


TotalCost_yuan = ...
    zeros(nCombo,1);


FinalSOC_kWh = ...
    zeros(nCombo,1);


EmergencyDays = ...
    zeros(nCombo,1);


EmergencySlots = ...
    zeros(nCombo,1);


for combo = 1:nCombo

    PlanEnergy_kWh(combo) = ...
        sum( ...
        planGridAll(:,:,combo), ...
        'all');


    EmergencyEnergy_kWh(combo) = ...
        sum( ...
        emergencyAll(:,:,combo), ...
        'all');


    ActualPlanCost_yuan(combo) = ...
        sum( ...
        ActualPlanCostDayAll(:,combo));


    EmergencyCost_yuan(combo) = ...
        sum( ...
        EmergencyCostDayAll(:,combo));


    TotalCost_yuan(combo) = ...
        ActualPlanCost_yuan(combo) ...
        +EmergencyCost_yuan(combo);


    FinalSOC_kWh(combo) = ...
        SOCendAll(end,combo);


    EmergencyDays(combo) = ...
        sum( ...
        any( ...
        emergencyAll(:,:,combo)>1e-8, ...
        2));


    EmergencySlots(combo) = ...
        nnz( ...
        emergencyAll(:,:,combo)>1e-8);

end


summaryTable = ...
    table( ...
    (1:nCombo)', ...
    comboName, ...
    LoadModel, ...
    PVModel, ...
    CorrectedNet_MAE, ...
    q80MeanCombo, ...
    PlanEnergy_kWh, ...
    ActualPlanCost_yuan, ...
    EmergencyEnergy_kWh, ...
    EmergencyCost_yuan, ...
    TotalCost_yuan, ...
    EmergencyDays, ...
    EmergencySlots, ...
    FinalSOC_kWh, ...
    'VariableNames',{ ...
    'ComboID', ...
    'Combination', ...
    'LoadModel', ...
    'PVModel', ...
    'CorrectedNet_MAE_kW', ...
    'Q80_Mean_kW', ...
    'PlanEnergy_kWh', ...
    'PlanCost_Yuan', ...
    'EmergencyEnergy_kWh', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'EmergencyDays', ...
    'EmergencySlots', ...
    'FinalSOC_kWh'} ...
    );


summaryByCost = ...
    sortrows( ...
    summaryTable, ...
    'TotalCost_Yuan', ...
    'ascend');


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-2：16组合总成本排名\n');
fprintf('====================================================\n');

disp(summaryByCost);


%% ============================================================
% 16. 最优组合
%% ============================================================

[bestCost,bestCombo] = ...
    min(TotalCost_yuan);


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-2最优组合\n');
fprintf('====================================================\n');


fprintf( ...
    'ComboID：%d\n', ...
    bestCombo);


fprintf( ...
    '负载模型：%s\n', ...
    LoadModel(bestCombo));


fprintf( ...
    '光伏模型：%s\n', ...
    PVModel(bestCombo));


fprintf( ...
    '计划购电量：%.2f kWh\n', ...
    PlanEnergy_kWh(bestCombo));


fprintf( ...
    '实际实时电价结算的计划购电费：%.2f 元\n', ...
    ActualPlanCost_yuan(bestCombo));


fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    EmergencyEnergy_kWh(bestCombo));


fprintf( ...
    '紧急购电费：%.2f 元\n', ...
    EmergencyCost_yuan(bestCombo));


fprintf( ...
    '全年总成本：%.2f 元\n', ...
    bestCost);


fprintf( ...
    '最终SOC：%.2f kWh\n', ...
    FinalSOC_kWh(bestCombo));


fprintf('====================================================\n');


%% ============================================================
% 17. 4×4总成本矩阵和热力图
%% ============================================================

costMatrix = ...
    zeros(4,4);


for combo = 1:nCombo

    i = ...
        comboLoadIdx(combo);


    j = ...
        comboPVIdx(combo);


    costMatrix(i,j) = ...
        TotalCost_yuan(combo);

end


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-2 4×4总成本矩阵 / 元\n');
fprintf(' 行 = 负载模型\n');
fprintf(' 列 = 光伏模型\n');
fprintf('====================================================\n');


disp( ...
    array2table( ...
    costMatrix, ...
    'VariableNames', ...
    cellstr(modelNames), ...
    'RowNames', ...
    cellstr(modelNames)));


fig = ...
    figure( ...
    'Color','w', ...
    'Position',[100,100,900,720]);


imagesc( ...
    costMatrix/1e4);


colorbar;


xticks(1:4);

yticks(1:4);


xticklabels(modelNames);

yticklabels(modelNames);


xlabel('光伏预测模型');

ylabel('负载预测模型');


title( ...
    '问题4-2：波动电价下16组合全年总成本 / 万元');


for i = 1:4

    for j = 1:4

        text( ...
            j,i, ...
            sprintf( ...
            '%.2f', ...
            costMatrix(i,j)/1e4), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontWeight','bold');

    end

end


exportgraphics( ...
    fig, ...
    heatmapFile, ...
    'Resolution',300);


%% ============================================================
% 18. 提取最优方案
%% ============================================================

planGrid = ...
    planGridAll(:,:,bestCombo);


actualCharge = ...
    actualChargeAll(:,:,bestCombo);


actualDischarge = ...
    actualDischargeAll(:,:,bestCombo);


emergencyGrid = ...
    emergencyAll(:,:,bestCombo);


SOCstart = ...
    SOCstartAll(:,bestCombo);


SOCend = ...
    SOCendAll(:,bestCombo);


planCostDay = ...
    ActualPlanCostDayAll(:,bestCombo);


emergencyCostDay = ...
    EmergencyCostDayAll(:,bestCombo);


%% ============================================================
% 19. 写分析Excel
%% ============================================================

if isfile(resultExcelFile)

    delete(resultExcelFile);

end


writetable( ...
    summaryTable, ...
    resultExcelFile, ...
    'Sheet','16组合结果');


writetable( ...
    summaryByCost, ...
    resultExcelFile, ...
    'Sheet','总成本排名');


%% 电价预测

write144Matrix( ...
    resultExcelFile, ...
    '预测实时电价', ...
    predDates, ...
    priceForecastRun);


write144Matrix( ...
    resultExcelFile, ...
    '实际实时电价', ...
    predDates, ...
    actualPriceRun);


%% ============================================================
% 20. 写官方 result4-2.xlsx
%% ============================================================

fprintf('\n开始写入官方result4-2.xlsx...\n');


%% ------------------------------------------------------------
% 先备份
%% ------------------------------------------------------------

backupFile = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    ['result4-2_backup_', ...
    char(datetime( ...
    'now', ...
    'Format','yyyyMMdd_HHmmss')), ...
    '.xlsx']);


copyfile( ...
    result4File, ...
    backupFile);


%% ============================================================
% 20.1 计划购电量
%
% TIMEFIX：
% 直接写原始144列
% 不旋转
%% ============================================================

dailyPlanEnergy = ...
    sum( ...
    planGrid, ...
    2);


writematrix( ...
    planGrid, ...
    result4File, ...
    'Sheet','计划购电量', ...
    'Range','B2');


writematrix( ...
    dailyPlanEnergy, ...
    result4File, ...
    'Sheet','计划购电量', ...
    'Range','EP2');


%% 全天购电费：
% 按附件4当天实际实时电价结算

writematrix( ...
    planCostDay, ...
    result4File, ...
    'Sheet','计划购电量', ...
    'Range','EQ2');


fprintf('计划购电量写入完成。\n');


%% ============================================================
% 20.2 充放电量
%% ============================================================

timeBlockName = {
    '0:00-4:00'
    '4:00-8:00'
    '8:00-12:00'
    '12:00-16:00'
    '16:00-20:00'
    '20:00-24:00'
    };


nBlock = ...
    6;


charge4h = ...
    zeros(nPredDay,nBlock);


discharge4h = ...
    zeros(nPredDay,nBlock);


for d = 1:nPredDay

    for b = 1:nBlock

        s1 = ...
            (b-1)*24+1;


        s2 = ...
            b*24;


        charge4h(d,b) = ...
            sum( ...
            actualCharge(d,s1:s2));


        discharge4h(d,b) = ...
            sum( ...
            actualDischarge(d,s1:s2));

    end

end


cdRows = ...
    cell( ...
    nPredDay*6, ...
    6);


r = ...
    1;


for d = 1:nPredDay

    for b = 1:6

        if b==1

            cdRows{r,1} = ...
                datestr( ...
                predDates(d), ...
                'yyyy-mm-dd');

        else

            cdRows{r,1} = ...
                '';

        end


        cdRows{r,2} = ...
            timeBlockName{b};


        cdRows{r,3} = ...
            charge4h(d,b);


        cdRows{r,4} = ...
            discharge4h(d,b);


        if b==1

            cdRows{r,5} = ...
                '0:00';


            cdRows{r,6} = ...
                SOCstart(d);

        elseif b==2

            cdRows{r,5} = ...
                '24:00';


            cdRows{r,6} = ...
                SOCend(d);

        else

            cdRows{r,5} = ...
                '';


            cdRows{r,6} = ...
                [];

        end


        r = ...
            r+1;

    end

end


writecell( ...
    cdRows, ...
    result4File, ...
    'Sheet','充放电量', ...
    'Range','A2');


fprintf('充放电量写入完成。\n');


%% ============================================================
% 20.3 紧急购电量
%
% 官方计划购电模板的第1个时段是：
%
% 0:10-0:20
%
% 因此这里：
%
% slot1   = 0:10-0:20
% ...
% slot143 = 23:50-0:00+1
% slot144 = 0:00-0:10+1
%% ============================================================

emergencyRows = ...
    cell(0,3);


rowOut = ...
    0;


for d = 1:nPredDay

    x = ...
        emergencyGrid(d,:);


    active = ...
        x>1e-8;


    if ~any(active)

        continue;

    end


    edge = ...
        diff( ...
        [ ...
        false, ...
        active, ...
        false ...
        ]);


    starts = ...
        find(edge==1);


    ends = ...
        find(edge==-1)-1;


    for k = 1:length(starts)

        rowOut = ...
            rowOut+1;


        if k==1

            emergencyRows{rowOut,1} = ...
                datestr( ...
                predDates(d), ...
                'yyyy-mm-dd');

        else

            emergencyRows{rowOut,1} = ...
                '';

        end


        emergencyRows{rowOut,2} = ...
            makeEmergencyTimeRange( ...
            starts(k), ...
            ends(k));


        emergencyRows{rowOut,3} = ...
            sum( ...
            x(starts(k):ends(k)));

    end

end


if ~isempty(emergencyRows)

    writecell( ...
        emergencyRows, ...
        result4File, ...
        'Sheet','紧急购电量', ...
        'Range','A2');

end


fprintf('紧急购电量写入完成。\n');


%% ============================================================
% 21. 保存MAT
%% ============================================================

save( ...
    resultMatFile, ...
    'modelNames', ...
    'summaryTable', ...
    'summaryByCost', ...
    'costMatrix', ...
    'bestCombo', ...
    'bestCost', ...
    'priceForecastRun', ...
    'actualPriceRun', ...
    'priceMAE', ...
    'priceRMSE', ...
    'priceBias', ...
    'planGridAll', ...
    'actualChargeAll', ...
    'actualDischargeAll', ...
    'emergencyAll', ...
    'SOCstartAll', ...
    'SOCendAll', ...
    'ActualPlanCostDayAll', ...
    'EmergencyCostDayAll', ...
    '-v7.3');


%% ============================================================
% 22. 删除断点
%% ============================================================

if isfile(dispatchCheckpoint)

    delete(dispatchCheckpoint);

end


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-2全部完成\n');
fprintf('====================================================\n');


fprintf( ...
    '电价预测MAE：%.6f 元/kWh\n', ...
    priceMAE);


fprintf( ...
    '最优组合：%s + %s\n', ...
    LoadModel(bestCombo), ...
    PVModel(bestCombo));


fprintf( ...
    '计划购电费：%.2f 元\n', ...
    ActualPlanCost_yuan(bestCombo));


fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    EmergencyEnergy_kWh(bestCombo));


fprintf( ...
    '紧急购电费：%.2f 元\n', ...
    EmergencyCost_yuan(bestCombo));


fprintf( ...
    '全年总成本：%.2f 元\n', ...
    bestCost);


fprintf( ...
    '最终SOC：%.2f kWh\n', ...
    FinalSOC_kWh(bestCombo));


fprintf( ...
    '调度耗时：%.2f min\n', ...
    dispatchTime/60);


fprintf('\n官方结果：\n%s\n', ...
    result4File);


fprintf('\n分析结果：\n%s\n', ...
    resultExcelFile);


fprintf('====================================================\n');


%% ============================================================
% 函数1：每日计划LP
%% ============================================================

function plan = solveDailyPlanTerminalSOC( ...
    Pload, ...
    Pv, ...
    price, ...
    Estart, ...
    terminalLow, ...
    terminalHigh, ...
    dt, ...
    eta_ch, ...
    eta_dis, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)


N = ...
    length(price);


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Pv(:)*dt;


price = ...
    price(:);


idxGrid = ...
    1:N;


idxCh = ...
    N+(1:N);


idxDis = ...
    2*N+(1:N);


idxCut = ...
    3*N+(1:N);


idxE = ...
    4*N+(1:N+1);


nVar = ...
    5*N+1;


f = ...
    zeros(nVar,1);


f(idxGrid) = ...
    price;


f(idxCh) = ...
    cyclePenalty;


f(idxDis) = ...
    cyclePenalty;


f(idxCut) = ...
    curtailPenalty;


Aeq = ...
    zeros( ...
    2*N+1, ...
    nVar);


beq = ...
    zeros( ...
    2*N+1, ...
    1);


%% 供需平衡

for t = 1:N

    Aeq(t,idxGrid(t)) = ...
        1;


    Aeq(t,idxCh(t)) = ...
        -1;


    Aeq(t,idxDis(t)) = ...
        1;


    Aeq(t,idxCut(t)) = ...
        -1;


    beq(t) = ...
        Wload(t) ...
        -Wpv(t);

end


%% SOC

for t = 1:N

    r = ...
        N+t;


    Aeq(r,idxE(t)) = ...
        -1;


    Aeq(r,idxE(t+1)) = ...
        1;


    Aeq(r,idxCh(t)) = ...
        -eta_ch;


    Aeq(r,idxDis(t)) = ...
        1/eta_dis;

end


Aeq(2*N+1,idxE(1)) = ...
    1;


beq(2*N+1) = ...
    Estart;


lb = ...
    zeros(nVar,1);


ub = ...
    inf(nVar,1);


ub(idxCh) = ...
    Wmax;


ub(idxDis) = ...
    Wmax;


ub(idxCut) = ...
    Wpv;


lb(idxE) = ...
    Emin;


ub(idxE) = ...
    Emax;


lb(idxE(end)) = ...
    terminalLow;


ub(idxE(end)) = ...
    terminalHigh;


[x,~,exitflag,output] = ...
    linprog( ...
    f, ...
    [],[], ...
    Aeq,beq, ...
    lb,ub, ...
    options);


if exitflag<=0

    error( ...
        '计划LP失败：%s', ...
        output.message);

end


plan.Wgrid = ...
    x(idxGrid);


plan.Wch = ...
    x(idxCh);


plan.Wdis = ...
    x(idxDis);


plan.Wcut = ...
    x(idxCut);


plan.E = ...
    x(idxE);

end


%% ============================================================
% 函数2：实际严格因果回放
%% ============================================================

function replay = replayActualDayCausalAllowSimultaneous( ...
    Pload, ...
    Pv, ...
    Wgrid, ...
    WchPlan, ...
    WdisPlan, ...
    Estart, ...
    dt, ...
    eta_ch, ...
    eta_dis, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    forceFinalSOC, ...
    EfinalTarget)


N = ...
    length(Wgrid);


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Pv(:)*dt;


Wgrid = ...
    Wgrid(:);


WchPlan = ...
    WchPlan(:);


WdisPlan = ...
    WdisPlan(:);


Wch = ...
    zeros(N,1);


Wdis = ...
    zeros(N,1);


Wspill = ...
    zeros(N,1);


Wem = ...
    zeros(N,1);


E = ...
    zeros(N+1,1);


E(1) = ...
    Estart;


for t = 1:N

    Ecurrent = ...
        E(t);


    EnextLow = ...
        Emin;


    EnextHigh = ...
        Emax;


    if forceFinalSOC

        remainingSlots = ...
            N-t;


        reachLow = ...
            EfinalTarget ...
            -remainingSlots ...
            *eta_ch ...
            *Wmax;


        reachHigh = ...
            EfinalTarget ...
            +remainingSlots ...
            *Wmax/eta_dis;


        EnextLow = ...
            max( ...
            Emin, ...
            reachLow);


        EnextHigh = ...
            min( ...
            Emax, ...
            reachHigh);

    end


    WchNow = ...
        min( ...
        max(WchPlan(t),0), ...
        Wmax);


    WdisNow = ...
        min( ...
        max(WdisPlan(t),0), ...
        Wmax);


    Enew = ...
        Ecurrent ...
        +eta_ch*WchNow ...
        -WdisNow/eta_dis;


    if Enew<EnextLow

        need = ...
            EnextLow-Enew;


        reduceDis = ...
            min( ...
            WdisNow, ...
            need*eta_dis);


        WdisNow = ...
            WdisNow ...
            -reduceDis;


        Enew = ...
            Ecurrent ...
            +eta_ch*WchNow ...
            -WdisNow/eta_dis;


        if Enew<EnextLow-1e-10

            addCh = ...
                min( ...
                Wmax-WchNow, ...
                (EnextLow-Enew)/eta_ch);


            WchNow = ...
                WchNow ...
                +addCh;


            Enew = ...
                Ecurrent ...
                +eta_ch*WchNow ...
                -WdisNow/eta_dis;

        end

    end


    if Enew>EnextHigh

        need = ...
            Enew-EnextHigh;


        reduceCh = ...
            min( ...
            WchNow, ...
            need/eta_ch);


        WchNow = ...
            WchNow ...
            -reduceCh;


        Enew = ...
            Ecurrent ...
            +eta_ch*WchNow ...
            -WdisNow/eta_dis;


        if Enew>EnextHigh+1e-10

            addDis = ...
                min( ...
                Wmax-WdisNow, ...
                (Enew-EnextHigh)*eta_dis);


            WdisNow = ...
                WdisNow ...
                +addDis;


            Enew = ...
                Ecurrent ...
                +eta_ch*WchNow ...
                -WdisNow/eta_dis;

        end

    end


    residual = ...
        Wload(t) ...
        +WchNow ...
        -Wpv(t) ...
        -Wgrid(t) ...
        -WdisNow;


    if residual>1e-12

        maxReduceChSOC = ...
            max( ...
            (Enew-EnextLow)/eta_ch, ...
            0);


        reduceCh = ...
            min( ...
            [ ...
            residual, ...
            WchNow, ...
            maxReduceChSOC ...
            ]);


        WchNow = ...
            WchNow ...
            -reduceCh;


        residual = ...
            residual ...
            -reduceCh;


        Enew = ...
            Enew ...
            -eta_ch*reduceCh;


        if residual>1e-12

            maxExtraDisSOC = ...
                eta_dis ...
                *max( ...
                Enew-EnextLow, ...
                0);


            extraDis = ...
                min( ...
                [ ...
                residual, ...
                Wmax-WdisNow, ...
                maxExtraDisSOC ...
                ]);


            WdisNow = ...
                WdisNow ...
                +extraDis;


            residual = ...
                residual ...
                -extraDis;


            Enew = ...
                Enew ...
                -extraDis/eta_dis;

        end


        Wem(t) = ...
            max(residual,0);


    elseif residual<-1e-12

        surplus = ...
            -residual;


        maxReduceDisSOC = ...
            eta_dis ...
            *max( ...
            EnextHigh-Enew, ...
            0);


        reduceDis = ...
            min( ...
            [ ...
            surplus, ...
            WdisNow, ...
            maxReduceDisSOC ...
            ]);


        WdisNow = ...
            WdisNow ...
            -reduceDis;


        surplus = ...
            surplus ...
            -reduceDis;


        Enew = ...
            Enew ...
            +reduceDis/eta_dis;


        if surplus>1e-12

            maxExtraChSOC = ...
                max( ...
                EnextHigh-Enew, ...
                0) ...
                /eta_ch;


            extraCh = ...
                min( ...
                [ ...
                surplus, ...
                Wmax-WchNow, ...
                maxExtraChSOC ...
                ]);


            WchNow = ...
                WchNow ...
                +extraCh;


            surplus = ...
                surplus ...
                -extraCh;


            Enew = ...
                Enew ...
                +eta_ch*extraCh;

        end


        Wspill(t) = ...
            max(surplus,0);

    end


    Wch(t) = ...
        WchNow;


    Wdis(t) = ...
        WdisNow;


    E(t+1) = ...
        Ecurrent ...
        +eta_ch*Wch(t) ...
        -Wdis(t)/eta_dis;


    if E(t+1)<Emin-1e-6 ...
            || E(t+1)>Emax+1e-6

        error( ...
            'SOC越界：t=%d,E=%.6f', ...
            t,E(t+1));

    end


    balanceError = ...
        Wgrid(t) ...
        +Wpv(t) ...
        +Wdis(t) ...
        +Wem(t) ...
        -Wload(t) ...
        -Wch(t) ...
        -Wspill(t);


    if abs(balanceError)>1e-5

        error( ...
            '实际供需平衡失败：t=%d,error=%.8f', ...
            t,balanceError);

    end

end


replay.Wch = ...
    Wch;


replay.Wdis = ...
    Wdis;


replay.Wspill = ...
    Wspill;


replay.Wem = ...
    Wem;


replay.E = ...
    E;


replay.Eend = ...
    E(end);

end


%% ============================================================
% 函数3：紧急购电时间段
%
% 按官方购电模板：
%
% slot1 = 0:10-0:20
% slot144 = 0:00-0:10+1
%% ============================================================

function txt = makeEmergencyTimeRange(s,e)


startMinute = ...
    10*s;


endMinute = ...
    10*(e+1);


txt = ...
    sprintf( ...
    '%s-%s', ...
    formatTimeLabel(startMinute), ...
    formatTimeLabel(endMinute));

end


%% ============================================================
% 函数4：分钟转时间
%% ============================================================

function txt = formatTimeLabel(totalMinute)


dayAdd = ...
    floor( ...
    totalMinute/1440);


minuteOfDay = ...
    mod( ...
    totalMinute, ...
    1440);


hh = ...
    floor( ...
    minuteOfDay/60);


mm = ...
    mod( ...
    minuteOfDay, ...
    60);


if dayAdd==0

    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh,mm);

else

    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh,mm);

end

end


%% ============================================================
% 函数5：写144点矩阵
%% ============================================================

function write144Matrix( ...
    filename, ...
    sheetName, ...
    dates, ...
    M)


dateText = ...
    string( ...
    dates, ...
    'yyyy-MM-dd');


header = ...
    cell(1,145);


header{1,1} = ...
    '日期';


for t = 1:143

    totalMin = ...
        10*t;


    hh = ...
        floor(totalMin/60);


    mm = ...
        mod(totalMin,60);


    header{1,t+1} = ...
        sprintf( ...
        '%02d:%02d', ...
        hh,mm);

end


header{1,145} = ...
    '00:00+1';


writecell( ...
    header, ...
    filename, ...
    'Sheet',sheetName, ...
    'Range','A1');


writecell( ...
    cellstr(dateText), ...
    filename, ...
    'Sheet',sheetName, ...
    'Range','A2');


writematrix( ...
    M, ...
    filename, ...
    'Sheet',sheetName, ...
    'Range','B2');

end