%% ============================================================
% 2026 C题 问题4-3
%
% 波动实时电价下重新计算问题3
%
% AS-Ridge负载
% + 0/6/12/18光伏滚动30日动态融合
% + 联合残差3情景
% + 实时电价严格因果滚动预测
% + 跨午夜24h随机滚动优化
%
% ============================================================
% TIMEFIX
%
% 附件2、附件4原始144列保持不变：
%
% col1   = 00:10
% col36  = 06:00
% col37  = 06:10
% col72  = 12:00
% col73  = 12:10
% col108 = 18:00
% col109 = 18:10
% col144 = 次日00:00
%
% 绝不使用：
%
% [144,1:143]
%
% ============================================================
% Q4实时电价：
%
% 0时：
%   最近1个同星期日日均价
%   ×
%   最近2个同星期日日内相对形状
%
% 6/12/18时：
%   只能使用截至当前时刻已经发生的真实电价
%   更新“当天价格水平”
%
%   严禁读取未来真实电价
%
% 决策：
%   使用预测电价
%
% 最终结算：
%   使用附件4真实实时电价
%
% 增购：1.5 × 实时价格
% 减购违约：0.5 × 实时价格
% 紧急购电：5 × 实时价格
%
% ============================================================
% 输出：
%
% 附件5\result4-3.xlsx
%
% Sheet：
% 1. 计划购电量
% 2. 调整购电量
% 3. 充放电量
% 4. 紧急购电量
%% ============================================================

clear;
clc;
close all;

rng(20260912,'twister');


fprintf('====================================================\n');
fprintf(' C题问题4-3 TIMEFIX\n');
fprintf(' 动态光伏 + 联合残差情景 + 滚动实时电价\n');
fprintf('====================================================\n\n');


%% ============================================================
% 1. 路径
%% ============================================================

baseDir = ...
    'E:\数模\2026年正式比赛\CUMCM2026Problems\C题\附件';


actualFile = ...
    fullfile( ...
    baseDir, ...
    '附件2.xlsx');


predictionFile = ...
    fullfile( ...
    baseDir, ...
    'Q2_16combo_4models_predictions.mat');


forecastFile = ...
    fullfile( ...
    baseDir, ...
    '附件3.xlsx');


priceFile = ...
    fullfile( ...
    baseDir, ...
    '附件4.xlsx');


%% ------------------------------------------------------------
% 负载缓存
%% ------------------------------------------------------------

loadForecastCache = ...
    fullfile( ...
    baseDir, ...
    'Q3_causal_load_ASRidge_tau08_TIMEFIX_cache.mat');


%% ------------------------------------------------------------
% Q4-3分析结果
%% ------------------------------------------------------------

resultMatFile = ...
    fullfile( ...
    baseDir, ...
    'Q4_3_RollingPrice_TIMEFIX_FINAL.mat');


resultExcelFile = ...
    fullfile( ...
    baseDir, ...
    'Q4_3_RollingPrice_TIMEFIX_FINAL.xlsx');


%% ------------------------------------------------------------
% 官方result4-3
%% ------------------------------------------------------------

result43File = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    'result4-3.xlsx');


filesNeed = {
    actualFile
    predictionFile
    forecastFile
    priceFile
    result43File
    };


for i = 1:length(filesNeed)

    if ~isfile(filesNeed{i})

        error( ...
            '找不到输入文件：\n%s', ...
            filesNeed{i});

    end

end


%% ============================================================
% 2. 参数
%% ============================================================

dt = ...
    10/60;


eta = ...
    0.90;


Ecapacity = ...
    12000;


Emin = ...
    0.10*Ecapacity;


Emax = ...
    0.90*Ecapacity;


Einitial = ...
    6000;


Efinal = ...
    6000;


Pmax = ...
    5000;


Wmax = ...
    Pmax*dt;


issueHours = ...
    [0,6,12,18];


%% ------------------------------------------------------------
% 联合残差情景
%% ------------------------------------------------------------

poolDays = ...
    30;


Kscenario = ...
    3;


%% ------------------------------------------------------------
% 动态光伏融合
%% ------------------------------------------------------------

PV_BLEND_WINDOW = ...
    30;


PV_BLEND_MIN_HISTORY = ...
    7;


%% ------------------------------------------------------------
% AS-Ridge负载
%% ------------------------------------------------------------

tauLoad = ...
    0.80;


loadWindowDays = ...
    56;


asLambda = ...
    1e-3;


asMaxIter = ...
    50;


asTol = ...
    1e-6;


%% ------------------------------------------------------------
% 实时电价预测
%% ------------------------------------------------------------

PRICE_KL = ...
    1;


PRICE_KS = ...
    2;


USE_PRICE_ROLLING_UPDATE = ...
    true;


%% ------------------------------------------------------------
% LP
%% ------------------------------------------------------------

cyclePenalty = ...
    0;


curtailPenalty = ...
    1e-5;


FORCE_FINAL_SOC_6000 = ...
    false;


USE_TERMINAL_VALUE = ...
    true;


USE_PV_ROLLING_BLEND = ...
    true;


RUN_ABLATION = ...
    true;


FORCE_REBUILD_LOAD_FORECAST = ...
    false;


%% ============================================================
% 3. 日期
%% ============================================================

dateAll = ...
    ( ...
    datetime(2025,1,1): ...
    days(1): ...
    datetime(2025,12,31) ...
    )';


targetDays = ...
    32:365;


predDates = ...
    dateAll(targetDays);


nDay = ...
    length(targetDays);


nTime = ...
    144;


%% ============================================================
% 4. 读取附件2
%% ============================================================

fprintf('读取附件2...\n');


loadRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','小区负载', ...
    'Range','B2:EO366');


pvRaw = ...
    readmatrix( ...
    actualFile, ...
    'Sheet','光伏发电实际功率', ...
    'Range','B2:EO366');


if ~isequal(size(loadRaw),[365,144]) ...
        || ~isequal(size(pvRaw),[365,144])

    error( ...
        '附件2负载和光伏必须是365×144。');

end


if any(~isfinite(loadRaw),'all') ...
        || any(~isfinite(pvRaw),'all')

    error( ...
        '附件2存在NaN或非有限值。');

end


%% TIMEFIX：直接使用

loadAll = ...
    loadRaw;


pvAll = ...
    pvRaw;


fprintf('\n');
fprintf('TIMEFIX：附件原始144列直接使用。\n');
fprintf('col1=00:10，col144=次日00:00。\n\n');


%% ============================================================
% 5. 读取附件4实时电价
%% ============================================================

fprintf('读取附件4实时电价...\n');


priceSheets = ...
    sheetnames(priceFile);


priceAll = ...
    readmatrix( ...
    priceFile, ...
    'Sheet',priceSheets(1), ...
    'Range','B2:EO366');


if ~isequal(size(priceAll),[365,144])

    error( ...
        '附件4必须读取为365×144。');

end


if any(~isfinite(priceAll),'all') ...
        || any(priceAll<0,'all')

    error( ...
        '附件4存在非法电价。');

end


actualPriceRun = ...
    priceAll(targetDays,:);


%% ============================================================
% 6. 建立0/6/12/18滚动实时电价预测
%% ============================================================

fprintf('生成严格因果滚动实时电价预测...\n');


[ ...
    priceForecastCache, ...
    priceForecastDiagTable, ...
    price0hMAE, ...
    priceBlockMAE ...
    ] = ...
    buildRollingPriceForecastCache( ...
    priceAll, ...
    dateAll, ...
    targetDays, ...
    issueHours, ...
    PRICE_KL, ...
    PRICE_KS, ...
    USE_PRICE_ROLLING_UPDATE);


fprintf('\n');
fprintf('====================================================\n');
fprintf(' 实时电价预测诊断\n');
fprintf('====================================================\n');


fprintf( ...
    '0时完整144点MAE：%.6f 元/kWh\n', ...
    price0hMAE);


for ki = 1:4

    fprintf( ...
        '%2d时后未来6h MAE：%.6f 元/kWh\n', ...
        issueHours(ki), ...
        priceBlockMAE(ki));

end


fprintf('====================================================\n\n');


%% ------------------------------------------------------------
% 与Q4-2核验
%% ------------------------------------------------------------

if abs(price0hMAE-0.044027)>0.002

    warning( ...
        ['0时价格预测MAE与Q4-2的0.044027差异较大，', ...
         '建议先检查附件4和时间轴。']);

end


%% ============================================================
% 7. 读取附件3
%% ============================================================

fprintf('读取附件3光伏预报...\n');


F = ...
    readForecastSingleSheet( ...
    forecastFile, ...
    'Sheet1');


if ~all( ...
        ismember( ...
        issueHours, ...
        unique(F.issueHour)'))

    error( ...
        '附件3未完整包含0、6、12、18时预报。');

end


%% ============================================================
% 8. 严格因果AS-Ridge负载预测缓存
%% ============================================================

cacheOK = ...
    false;


if isfile(loadForecastCache) ...
        && ~FORCE_REBUILD_LOAD_FORECAST

    C = ...
        load(loadForecastCache);


    cacheOK = ...
        isfield(C,'loadForecastToday') ...
        && isfield(C,'loadForecastNext') ...
        && isfield(C,'tauLoad') ...
        && isfield(C,'asLambda') ...
        && isfield(C,'asMaxIter') ...
        && isfield(C,'asTol') ...
        && isfield(C,'loadWindowDays') ...
        && isfield(C,'timeAxisVersion') ...
        && strcmp( ...
        C.timeAxisVersion, ...
        'ORIGINAL_0010_TO_NEXT_0000') ...
        && isequal( ...
        size(C.loadForecastToday), ...
        [365,144]) ...
        && isequal( ...
        size(C.loadForecastNext), ...
        [365,144]) ...
        && abs(C.tauLoad-tauLoad)<1e-12 ...
        && abs(C.asLambda-asLambda)<1e-12 ...
        && C.asMaxIter==asMaxIter ...
        && abs(C.asTol-asTol)<1e-12 ...
        && C.loadWindowDays==loadWindowDays;


    if cacheOK

        loadForecastToday = ...
            C.loadForecastToday;


        loadForecastNext = ...
            C.loadForecastNext;


        fprintf('读取TIMEFIX负载缓存完成。\n');

    end

end


if ~cacheOK

    fprintf( ...
        '重新生成严格因果AS-Ridge负载预测...\n');


    [loadForecastToday,loadForecastNext] = ...
        buildCausalLoadASRidge( ...
        loadAll, ...
        dateAll, ...
        tauLoad, ...
        asLambda, ...
        asMaxIter, ...
        asTol, ...
        loadWindowDays);


    timeAxisVersion = ...
        'ORIGINAL_0010_TO_NEXT_0000';


    save( ...
        loadForecastCache, ...
        'loadForecastToday', ...
        'loadForecastNext', ...
        'tauLoad', ...
        'asLambda', ...
        'asMaxIter', ...
        'asTol', ...
        'loadWindowDays', ...
        'timeAxisVersion', ...
        '-v7.3');

end


%% ============================================================
% 9. 使用问题2最终AS-Ridge负载预测
%% ============================================================

fprintf('读取问题2 AS-Ridge负载预测...\n');


S2 = ...
    load(predictionFile);


if ~isfield(S2,'predLoad') ...
        || ~isfield(S2,'modelNames')

    error( ...
        '问题2预测文件缺少predLoad或modelNames。');

end


modelNamesQ2 = ...
    string(S2.modelNames(:));


loadModelID = ...
    find( ...
    strcmpi( ...
    modelNamesQ2, ...
    'AS-Ridge'), ...
    1);


if isempty(loadModelID)

    error( ...
        '问题2预测缓存中找不到AS-Ridge。');

end


predLoadQ2 = ...
    S2.predLoad(:,:,loadModelID);


if ~isequal(size(predLoadQ2),[334,144])

    error( ...
        '问题2AS-Ridge负载预测不是334×144。');

end


loadForecastToday(targetDays,:) = ...
    max( ...
    predLoadQ2, ...
    0);


fprintf('Q4-3负载使用AS-Ridge。\n');
fprintf('不使用问题2 Q0.8净负荷校准。\n\n');


%% ============================================================
% 10. 建立光伏融合标定库
%% ============================================================

fprintf('建立光伏动态融合标定库...\n');


PVlib = ...
    buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll);


fprintf( ...
    '完整光伏历史路径：%d条。\n\n', ...
    sum(PVlib.complete));


%% ============================================================
% 11. 动态光伏融合权重
%% ============================================================

wDynamic = ...
    ones( ...
    nDay, ...
    4);


nWeightHistory = ...
    zeros( ...
    nDay, ...
    4);


fprintf('计算0/6/12/18时动态光伏权重...\n');


for kd = 1:nDay

    d = ...
        targetDays(kd);


    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        currentTime = ...
            dateAll(d) ...
            +hours(hIssue);


        if USE_PV_ROLLING_BLEND

            [ ...
                wDynamic(kd,ki), ...
                nWeightHistory(kd,ki) ...
                ] = ...
                getRollingPVBlendWeight( ...
                PVlib, ...
                hIssue, ...
                currentTime, ...
                PV_BLEND_WINDOW, ...
                PV_BLEND_MIN_HISTORY);

        else

            wDynamic(kd,ki) = ...
                1;


            nWeightHistory(kd,ki) = ...
                0;

        end

    end

end


fprintf('\n');
fprintf('动态光伏权重统计：\n');


for ki = 1:4

    fprintf( ...
        '%2d时：mean %.4f, median %.4f, min %.4f, max %.4f\n', ...
        issueHours(ki), ...
        mean(wDynamic(:,ki)), ...
        median(wDynamic(:,ki)), ...
        min(wDynamic(:,ki)), ...
        max(wDynamic(:,ki)));

end


weightTable = ...
    table( ...
    predDates, ...
    wDynamic(:,1), ...
    wDynamic(:,2), ...
    wDynamic(:,3), ...
    wDynamic(:,4), ...
    nWeightHistory(:,1), ...
    nWeightHistory(:,2), ...
    nWeightHistory(:,3), ...
    nWeightHistory(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'Weight_0h', ...
    'Weight_6h', ...
    'Weight_12h', ...
    'Weight_18h', ...
    'HistoryN_0h', ...
    'HistoryN_6h', ...
    'HistoryN_12h', ...
    'HistoryN_18h'} ...
    );


%% ============================================================
% 12. 建立联合残差库
%% ============================================================

fprintf('建立动态融合联合残差库...\n');


Rlib = ...
    buildJointResidualLibraryDynamic( ...
    F, ...
    loadAll, ...
    pvAll, ...
    loadForecastToday, ...
    loadForecastNext, ...
    dateAll, ...
    PVlib, ...
    PV_BLEND_WINDOW, ...
    PV_BLEND_MIN_HISTORY, ...
    USE_PV_ROLLING_BLEND);


fprintf( ...
    '完整联合残差路径：%d条。\n\n', ...
    sum(Rlib.complete));


%% ============================================================
% 13. 预计算3情景
%% ============================================================

fprintf('预计算联合残差3情景...\n');


scenarioCache = ...
    cell( ...
    nDay, ...
    4);


for kd = 1:nDay

    d = ...
        targetDays(kd);


    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        currentTime = ...
            dateAll(d) ...
            +hours(hIssue);


        scenarioCache{kd,ki} = ...
            getJointScenarioCenters( ...
            Rlib, ...
            hIssue, ...
            currentTime, ...
            poolDays, ...
            Kscenario, ...
            100000 ...
            +100*d ...
            +hIssue);

    end

end


%% ============================================================
% 14. 五组策略
%% ============================================================

strategyNames = [
    "仅0时预报，不调整"
    "0时+6时滚动调整"
    "0时+6时+12时滚动调整"
    "四次动态滚动（Q4-3主方案）"
    "三次调整，冻结0时光伏（电价仍滚动）"
    ];


updateMask = logical([
    1 0 0 0
    1 1 0 0
    1 1 1 0
    1 1 1 1
    1 1 1 1
    ]);


freezePV = [
    false
    false
    false
    false
    true
    ];


if RUN_ABLATION

    strategyID = ...
        1:length(strategyNames);

else

    strategyID = ...
        4;

end


%% ============================================================
% 15. LP
%% ============================================================

lpOptions = ...
    optimoptions( ...
    'linprog', ...
    'Algorithm','dual-simplex-highs', ...
    'Display','none');


%% ============================================================
% 16. 运行五个策略
%% ============================================================

allResult = ...
    struct([]);


timerAll = ...
    tic;


for ir = 1:length(strategyID)

    sID = ...
        strategyID(ir);


    fprintf('\n');
    fprintf('====================================================\n');

    fprintf( ...
        '[%d/%d] %s\n', ...
        ir, ...
        length(strategyID), ...
        strategyNames(sID));

    fprintf('====================================================\n');


    thisResult = ...
        runOneStrategyQ43( ...
        strategyNames(sID), ...
        updateMask(sID,:), ...
        freezePV(sID), ...
        targetDays, ...
        predDates, ...
        dateAll, ...
        loadAll, ...
        pvAll, ...
        loadForecastToday, ...
        loadForecastNext, ...
        F, ...
        scenarioCache, ...
        wDynamic, ...
        priceAll, ...
        priceForecastCache, ...
        USE_TERMINAL_VALUE, ...
        dt, ...
        eta, ...
        Emin, ...
        Emax, ...
        Einitial, ...
        Efinal, ...
        Wmax, ...
        cyclePenalty, ...
        curtailPenalty, ...
        FORCE_FINAL_SOC_6000, ...
        lpOptions);


    if isempty(allResult)

        allResult = ...
            thisResult;

    else

        allResult(end+1,1) = ...
            thisResult;

    end

end


runtimeMin = ...
    toc(timerAll)/60;


%% ============================================================
% 17. 汇总
%% ============================================================

summaryTable = ...
    table();


for i = 1:length(allResult)

    R = ...
        allResult(i);


    row = ...
        table( ...
        string(R.name), ...
        R.totalRetainedPlanCost, ...
        R.totalIncreaseCost, ...
        R.totalDecreasePenalty, ...
        R.totalEmergencyCost, ...
        R.totalCost, ...
        R.totalIncreaseEnergy, ...
        R.totalDecreaseEnergy, ...
        R.totalEmergencyEnergy, ...
        R.emergencyDays, ...
        R.emergencySlots, ...
        R.finalSOC, ...
        R.maxLPConstraintViolation, ...
        'VariableNames',{ ...
        'Strategy', ...
        'RetainedPlanCost_Yuan', ...
        'IncreaseCost_Yuan', ...
        'DecreasePenalty_Yuan', ...
        'EmergencyCost_Yuan', ...
        'TotalCost_Yuan', ...
        'IncreaseEnergy_kWh', ...
        'DecreaseEnergy_kWh', ...
        'EmergencyEnergy_kWh', ...
        'EmergencyDays', ...
        'EmergencySlots', ...
        'FinalSOC_kWh', ...
        'MaxLPViolation'} ...
        );


    summaryTable = ...
        [summaryTable;row];

end


if RUN_ABLATION

    baseCost = ...
        summaryTable.TotalCost_Yuan(1);


    summaryTable.SavingVsNoUpdate_Yuan = ...
        baseCost ...
        -summaryTable.TotalCost_Yuan;

else

    summaryTable.SavingVsNoUpdate_Yuan = ...
        NaN( ...
        height(summaryTable), ...
        1);

end


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-3策略汇总\n');
fprintf('====================================================\n');

disp(summaryTable);


%% ============================================================
% 18. 主方案
%% ============================================================

mainRow = ...
    find( ...
    arrayfun( ...
    @(x) ...
    string(x.name)==strategyNames(4), ...
    allResult), ...
    1);


if isempty(mainRow)

    error('找不到Q4-3主方案。');

end


Main = ...
    allResult(mainRow);


costIdentityError = ...
    abs( ...
    Main.totalCost ...
    -( ...
    Main.totalRetainedPlanCost ...
    +Main.totalIncreaseCost ...
    +Main.totalDecreasePenalty ...
    +Main.totalEmergencyCost));


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-3主方案\n');
fprintf('====================================================\n');


fprintf( ...
    '保留0时计划购电费：%.2f 元\n', ...
    Main.totalRetainedPlanCost);


fprintf( ...
    '增加购电费用：%.2f 元\n', ...
    Main.totalIncreaseCost);


fprintf( ...
    '减少购电违约费用：%.2f 元\n', ...
    Main.totalDecreasePenalty);


fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    Main.totalEmergencyCost);


fprintf( ...
    '全年总成本：%.2f 元\n', ...
    Main.totalCost);


fprintf( ...
    '增加购电量：%.2f kWh\n', ...
    Main.totalIncreaseEnergy);


fprintf( ...
    '减少购电量：%.2f kWh\n', ...
    Main.totalDecreaseEnergy);


fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    Main.totalEmergencyEnergy);


fprintf( ...
    '紧急购电天数：%d\n', ...
    Main.emergencyDays);


fprintf( ...
    '紧急购电时段数：%d\n', ...
    Main.emergencySlots);


fprintf( ...
    '年末SOC：%.6f kWh\n', ...
    Main.finalSOC);


fprintf( ...
    '最大LP违反量：%.3e\n', ...
    Main.maxLPConstraintViolation);


fprintf( ...
    '成本加总误差：%.3e 元\n', ...
    costIdentityError);


fprintf('====================================================\n');


%% ============================================================
% 19. 月度结果
%% ============================================================

monthList = ...
    (2:12)';


monthlyTable = ...
    table( ...
    monthList, ...
    'VariableNames',{'Month'} ...
    );


monthlyTable.MainCost_Yuan = ...
    zeros(11,1);


monthlyTable.NoUpdateCost_Yuan = ...
    nan(11,1);


for im = 1:11

    hit = ...
        month(predDates) ...
        ==monthList(im);


    monthlyTable.MainCost_Yuan(im) = ...
        sum( ...
        Main.dailyCost(hit));


    if RUN_ABLATION

        monthlyTable.NoUpdateCost_Yuan(im) = ...
            sum( ...
            allResult(1).dailyCost(hit));

    end

end


monthlyTable.Saving_Yuan = ...
    monthlyTable.NoUpdateCost_Yuan ...
    -monthlyTable.MainCost_Yuan;


%% ============================================================
% 20. 保存分析Excel
%% ============================================================

if isfile(resultExcelFile)

    delete(resultExcelFile);

end


writetable( ...
    summaryTable, ...
    resultExcelFile, ...
    'Sheet','策略对照');


writetable( ...
    monthlyTable, ...
    resultExcelFile, ...
    'Sheet','逐月结果');


writetable( ...
    Main.dailyTable, ...
    resultExcelFile, ...
    'Sheet','主方案每日结果');


writetable( ...
    Main.adjustmentTable, ...
    resultExcelFile, ...
    'Sheet','主方案调整明细');


writetable( ...
    weightTable, ...
    resultExcelFile, ...
    'Sheet','动态光伏权重');


writetable( ...
    priceForecastDiagTable, ...
    resultExcelFile, ...
    'Sheet','滚动电价预测误差');


%% ============================================================
% 21. 写入官方 result4-3.xlsx
%% ============================================================

fprintf('\n');
fprintf('开始写入官方result4-3.xlsx...\n');


%% ------------------------------------------------------------
% 备份
%% ------------------------------------------------------------

backupFile = ...
    fullfile( ...
    baseDir, ...
    '附件5', ...
    ['result4-3_backup_', ...
    char(datetime( ...
    'now', ...
    'Format','yyyyMMdd_HHmmss')), ...
    '.xlsx']);


copyfile( ...
    result43File, ...
    backupFile);


fprintf('已备份：\n%s\n', ...
    backupFile);


%% ============================================================
% 21.1 计划购电量
%
% 模板：
%
% A = 日期
% B:EO = 144个购电时段
% EP = 全天购电量
% EQ = 全天购电费
%% ============================================================

planOut = ...
    Main.plan0;


if ~isequal( ...
        size(planOut), ...
        [334,144])

    error( ...
        'Main.plan0尺寸不是334×144。');

end


planEnergyDay = ...
    sum( ...
    planOut, ...
    2);


%% ------------------------------------------------------------
% 初始0时计划购电费用
%
% 最终结果结算使用附件4真实实时电价
%% ------------------------------------------------------------

planCostDay = ...
    sum( ...
    planOut ...
    .*actualPriceRun, ...
    2);


%% TIMEFIX：直接写，不循环移位

writematrix( ...
    planOut, ...
    result43File, ...
    'Sheet','计划购电量', ...
    'Range','B2');


writematrix( ...
    planEnergyDay, ...
    result43File, ...
    'Sheet','计划购电量', ...
    'Range','EP2');


writematrix( ...
    planCostDay, ...
    result43File, ...
    'Sheet','计划购电量', ...
    'Range','EQ2');


fprintf('计划购电量写入完成。\n');


%% ============================================================
% 21.2 调整购电量
%
% Main.executedPlan：
% 经过6/12/18滚动调整以后，
% 最终实际执行的普通购电计划。
%% ============================================================

adjustedOut = ...
    Main.executedPlan;


if ~isequal( ...
        size(adjustedOut), ...
        [334,144])

    error( ...
        'Main.executedPlan尺寸不是334×144。');

end


adjustedEnergyDay = ...
    sum( ...
    adjustedOut, ...
    2);


%% ------------------------------------------------------------
% 调整后普通购电费用
%
% 保留计划部分
% + 增购1.5倍费用
% + 减购50%违约费用
%
% 不含紧急购电
%% ------------------------------------------------------------

adjustedCostDay = ...
    Main.dailyTable.RetainedPlanCost_Yuan ...
    +Main.dailyTable.IncreaseCost_Yuan ...
    +Main.dailyTable.DecreasePenalty_Yuan;


writematrix( ...
    adjustedOut, ...
    result43File, ...
    'Sheet','调整购电量', ...
    'Range','B2');


writematrix( ...
    adjustedEnergyDay, ...
    result43File, ...
    'Sheet','调整购电量', ...
    'Range','EP2');


writematrix( ...
    adjustedCostDay, ...
    result43File, ...
    'Sheet','调整购电量', ...
    'Range','EQ2');


fprintf('调整购电量写入完成。\n');


%% ============================================================
% 21.3 充放电量
%
% 每天6个4小时区间
%% ============================================================

timeBlockName = {
    '0:00-4:00'
    '4:00-8:00'
    '8:00-12:00'
    '12:00-16:00'
    '16:00-20:00'
    '20:00-24:00'
    };


nBlock = ...
    6;


charge4h = ...
    zeros( ...
    nDay, ...
    nBlock);


discharge4h = ...
    zeros( ...
    nDay, ...
    nBlock);


for kd = 1:nDay

    for b = 1:nBlock

        s1 = ...
            (b-1)*24+1;


        s2 = ...
            b*24;


        charge4h(kd,b) = ...
            sum( ...
            Main.actualCharge( ...
            kd, ...
            s1:s2));


        discharge4h(kd,b) = ...
            sum( ...
            Main.actualDischarge( ...
            kd, ...
            s1:s2));

    end

end


nCDRow = ...
    nDay*nBlock;


cdOut = ...
    cell( ...
    nCDRow, ...
    6);


r = ...
    1;


for kd = 1:nDay

    for b = 1:nBlock

        if b==1

            cdOut{r,1} = ...
                datestr( ...
                predDates(kd), ...
                'yyyy-mm-dd');

        else

            cdOut{r,1} = ...
                '';

        end


        cdOut{r,2} = ...
            timeBlockName{b};


        cdOut{r,3} = ...
            charge4h(kd,b);


        cdOut{r,4} = ...
            discharge4h(kd,b);


        if b==1

            cdOut{r,5} = ...
                '0:00';


            cdOut{r,6} = ...
                Main.SOCstart(kd);


        elseif b==2

            cdOut{r,5} = ...
                '24:00';


            cdOut{r,6} = ...
                Main.SOCend(kd);

        else

            cdOut{r,5} = ...
                '';


            cdOut{r,6} = ...
                [];

        end


        r = ...
            r+1;

    end

end


writecell( ...
    cdOut, ...
    result43File, ...
    'Sheet','充放电量', ...
    'Range','A2');


fprintf( ...
    '充放电量写入完成，共%d行。\n', ...
    nCDRow);


%% ============================================================
% 21.4 紧急购电量
%
% 连续10min紧急购电合并成连续区间
%
% 注意：
%
% slot1代表：
% 00:00-00:10
%
% 所以：
%
% startMinute = 10*(s-1)
% endMinute   = 10*e
%% ============================================================

emergencyRows = ...
    cell(0,3);


outRow = ...
    0;


for kd = 1:nDay

    x = ...
        Main.actualEmergency(kd,:);


    active = ...
        x>1e-8;


    if ~any(active)

        continue;

    end


    edge = ...
        diff( ...
        [ ...
        false, ...
        active, ...
        false ...
        ]);


    starts = ...
        find(edge==1);


    ends = ...
        find(edge==-1)-1;


    for kk = 1:length(starts)

        s = ...
            starts(kk);


        e = ...
            ends(kk);


        outRow = ...
            outRow+1;


        if kk==1

            emergencyRows{outRow,1} = ...
                datestr( ...
                predDates(kd), ...
                'yyyy-mm-dd');

        else

            emergencyRows{outRow,1} = ...
                '';

        end


        emergencyRows{outRow,2} = ...
            makeEmergencyTimeRangeQ43( ...
            s, ...
            e);


        emergencyRows{outRow,3} = ...
            sum( ...
            x(s:e));

    end

end


if isempty(emergencyRows)

    fprintf('全年没有紧急购电。\n');

else

    writecell( ...
        emergencyRows, ...
        result43File, ...
        'Sheet','紧急购电量', ...
        'Range','A2');


    fprintf( ...
        '紧急购电量写入完成，共%d个连续时段。\n', ...
        size(emergencyRows,1));

end


%% ============================================================
% 22. 官方结果校验
%% ============================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf(' result4-3.xlsx 写入校验\n');
fprintf('====================================================\n');


fprintf( ...
    '0时计划购电量：%.2f kWh\n', ...
    sum( ...
    Main.plan0, ...
    'all'));


fprintf( ...
    '最终调整后普通购电量：%.2f kWh\n', ...
    sum( ...
    Main.executedPlan, ...
    'all'));


fprintf( ...
    '实际充电量：%.2f kWh\n', ...
    sum( ...
    Main.actualCharge, ...
    'all'));


fprintf( ...
    '实际放电量：%.2f kWh\n', ...
    sum( ...
    Main.actualDischarge, ...
    'all'));


fprintf( ...
    '紧急购电量：%.2f kWh\n', ...
    sum( ...
    Main.actualEmergency, ...
    'all'));


fprintf( ...
    '调整后普通购电费用：%.2f 元\n', ...
    sum(adjustedCostDay));


fprintf( ...
    '紧急购电费用：%.2f 元\n', ...
    Main.totalEmergencyCost);


fprintf( ...
    '总费用：%.2f 元\n', ...
    sum(adjustedCostDay) ...
    +Main.totalEmergencyCost);


fprintf( ...
    'Main.totalCost：%.2f 元\n', ...
    Main.totalCost);


fprintf( ...
    '费用核对误差：%.6e 元\n', ...
    abs( ...
    Main.totalCost ...
    -( ...
    sum(adjustedCostDay) ...
    +Main.totalEmergencyCost)));


fprintf('====================================================\n');


%% ============================================================
% 23. 保存MAT
%% ============================================================

save( ...
    resultMatFile, ...
    'allResult', ...
    'summaryTable', ...
    'monthlyTable', ...
    'weightTable', ...
    'priceForecastDiagTable', ...
    'wDynamic', ...
    'nWeightHistory', ...
    'Main', ...
    'PVlib', ...
    'Rlib', ...
    'strategyNames', ...
    'predDates', ...
    'priceForecastCache', ...
    'price0hMAE', ...
    'priceBlockMAE', ...
    'PRICE_KL', ...
    'PRICE_KS', ...
    'PV_BLEND_WINDOW', ...
    'PV_BLEND_MIN_HISTORY', ...
    'Kscenario', ...
    'poolDays', ...
    'runtimeMin', ...
    '-v7.3');


fprintf('\n');
fprintf('====================================================\n');
fprintf(' Q4-3运行完成\n');
fprintf('====================================================\n');


fprintf( ...
    '0时电价预测MAE：%.6f 元/kWh\n', ...
    price0hMAE);


fprintf( ...
    '主方案总成本：%.2f 元\n', ...
    Main.totalCost);


fprintf( ...
    '主方案紧急购电量：%.2f kWh\n', ...
    Main.totalEmergencyEnergy);


fprintf( ...
    '主方案紧急购电费用：%.2f 元\n', ...
    Main.totalEmergencyCost);


fprintf( ...
    '最终SOC：%.2f kWh\n', ...
    Main.finalSOC);


fprintf( ...
    '运行时间：%.2f min\n', ...
    runtimeMin);


fprintf('\n官方文件：\n%s\n', ...
    result43File);


fprintf('\n分析Excel：\n%s\n', ...
    resultExcelFile);


fprintf('\nMAT：\n%s\n', ...
    resultMatFile);


fprintf('====================================================\n');


%% ============================================================
% 局部函数1
% Q4-3运行一个策略
%% ============================================================

function R = runOneStrategyQ43( ...
    strategyName, ...
    updateMask, ...
    freezePV, ...
    targetDays, ...
    predDates, ...
    dateAll, ...
    loadAll, ...
    pvAll, ...
    loadForecastToday, ...
    loadForecastNext, ...
    F, ...
    scenarioCache, ...
    wDynamic, ...
    priceAll, ...
    priceForecastCache, ...
    useTerminalValue, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Einitial, ...
    Efinal, ...
    Wmax, ...
    cyclePenalty, ...
    curtailPenalty, ...
    forceFinalSOC6000, ...
    lpOptions)


nDay = ...
    length(targetDays);


nTime = ...
    144;


issueHours = ...
    [0,6,12,18];


plan0 = ...
    zeros(nDay,nTime);


executedPlan = ...
    zeros(nDay,nTime);


planAfter = ...
    nan(nDay,nTime,4);


actualCharge = ...
    zeros(nDay,nTime);


actualDischarge = ...
    zeros(nDay,nTime);


actualEmergency = ...
    zeros(nDay,nTime);


actualSurplus = ...
    zeros(nDay,nTime);


SOCstart = ...
    zeros(nDay,1);


SOCend = ...
    zeros(nDay,1);


retainedPlanCostDay = ...
    zeros(nDay,1);


increaseCostDay = ...
    zeros(nDay,1);


decreasePenaltyDay = ...
    zeros(nDay,1);


emergencyCostDay = ...
    zeros(nDay,1);


increaseEnergyDay = ...
    zeros(nDay,1);


decreaseEnergyDay = ...
    zeros(nDay,1);


adjustmentTable = ...
    table();


maxLPViolation = ...
    0;


Ecurrent = ...
    Einitial;


for kd = 1:nDay

    d = ...
        targetDays(kd);


    thisDate = ...
        dateAll(d);


    actualPriceDay = ...
        priceAll(d,:)';


    isLastDay = ...
        d==365;


    forceFinalToday = ...
        isLastDay ...
        &&forceFinalSOC6000;


    SOCstart(kd) = ...
        Ecurrent;


    if mod(kd-1,20)==0 ...
            ||isLastDay

        fprintf( ...
            '  [%03d/%03d] %s，SOC %.2f\n', ...
            kd, ...
            nDay, ...
            string(thisDate), ...
            Ecurrent);

    end


    %% --------------------------------------------------------
    % 冻结0时光伏对照
    %% --------------------------------------------------------

    w0 = ...
        wDynamic(kd,1);


    frozenPV48 = ...
        buildFrozenPV48( ...
        F, ...
        pvAll, ...
        dateAll, ...
        d, ...
        w0);


    currentPlan = ...
        zeros(nTime,1);


    g0 = ...
        zeros(nTime,1);


    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        startSlot = ...
            hIssue*6+1;


        endSlot = ...
            min( ...
            startSlot+35, ...
            nTime);


        shouldOptimize = ...
            ki==1 ...
            ||updateMask(ki);


        if shouldOptimize

            %% ------------------------------------------------
            % 负载未来24h
            %% ------------------------------------------------

            baseLoad24 = ...
                makeLoadForecast24( ...
                loadForecastToday, ...
                loadForecastNext, ...
                d, ...
                hIssue);


            %% ------------------------------------------------
            % 光伏未来24h
            %% ------------------------------------------------

            if freezePV ...
                    &&ki>1

                basePV24 = ...
                    frozenPV48( ...
                    startSlot: ...
                    startSlot+143);

            else

                wNow = ...
                    wDynamic(kd,ki);


                basePV24 = ...
                    makeOfficialPV24Blend( ...
                    F, ...
                    pvAll, ...
                    dateAll, ...
                    d, ...
                    hIssue, ...
                    wNow);

            end


            %% ------------------------------------------------
            % 联合残差3情景
            %% ------------------------------------------------

            S = ...
                scenarioCache{kd,ki};


            loadScenario = ...
                max( ...
                baseLoad24(:) ...
                +S.loadCenter, ...
                0);


            pvScenario = ...
                max( ...
                basePV24(:) ...
                +S.pvCenter, ...
                0);


            prob = ...
                S.prob;


            %% ------------------------------------------------
            % ★Q4未来24h预测电价
            %% ------------------------------------------------

            price24 = ...
                priceForecastCache{kd,ki};


            price24 = ...
                price24(:);


            if length(price24)~=144

                error( ...
                    '滚动电价预测长度不是144。');

            end


            qCurrent = ...
                nTime-startSlot+1;


            if ki==1

                basePlanRemain = ...
                    [];

            else

                basePlanRemain = ...
                    g0(startSlot:end);

            end


            %% ------------------------------------------------
            % 终端储能价值
            %% ------------------------------------------------

            if useTerminalValue ...
                    &&~isLastDay

                terminalValueNow = ...
                    eta ...
                    *mean(price24);

            else

                terminalValueNow = ...
                    0;

            end


            %% ------------------------------------------------
            % 24h随机LP
            %% ------------------------------------------------

            P = ...
                solveRolling24hLP( ...
                loadScenario, ...
                pvScenario, ...
                prob, ...
                price24, ...
                qCurrent, ...
                basePlanRemain, ...
                Ecurrent, ...
                forceFinalToday, ...
                Efinal, ...
                dt, ...
                eta, ...
                Emin, ...
                Emax, ...
                Wmax, ...
                terminalValueNow, ...
                cyclePenalty, ...
                curtailPenalty, ...
                lpOptions);


            maxLPViolation = ...
                max( ...
                maxLPViolation, ...
                P.maxConstraintViolation);


            if ki==1

                g0 = ...
                    P.currentGrid;


                currentPlan = ...
                    g0;


                plan0(kd,:) = ...
                    g0';

            else

                oldPlan = ...
                    currentPlan(startSlot:end);


                currentPlan(startSlot:end) = ...
                    P.currentGrid;


                oneInc = ...
                    sum( ...
                    max( ...
                    P.currentGrid ...
                    -g0(startSlot:end), ...
                    0));


                oneDec = ...
                    sum( ...
                    max( ...
                    g0(startSlot:end) ...
                    -P.currentGrid, ...
                    0));


                logRow = ...
                    table( ...
                    string(strategyName), ...
                    thisDate, ...
                    hIssue, ...
                    wDynamic(kd,ki), ...
                    mean(price24), ...
                    sum( ...
                    abs( ...
                    P.currentGrid ...
                    -oldPlan)>1e-6), ...
                    oneInc, ...
                    oneDec, ...
                    P.objective, ...
                    P.maxConstraintViolation, ...
                    'VariableNames',{ ...
                    'Strategy', ...
                    'Date', ...
                    'IssueHour', ...
                    'PVBlendWeight', ...
                    'ForecastPriceMean', ...
                    'ChangedSlots', ...
                    'IncreaseVs0_kWh', ...
                    'DecreaseVs0_kWh', ...
                    'RollingObjective', ...
                    'MaxConstraintViolation'} ...
                    );


                adjustmentTable = ...
                    [adjustmentTable;logRow];

            end

        end


        planAfter(kd,:,ki) = ...
            currentPlan';


        %% ----------------------------------------------------
        % 仅执行下一6小时
        %% ----------------------------------------------------

        blockSlots = ...
            startSlot:endSlot;


        A = ...
            replayActualBlock( ...
            loadAll(d,blockSlots)', ...
            pvAll(d,blockSlots)', ...
            currentPlan(blockSlots), ...
            Ecurrent, ...
            blockSlots, ...
            forceFinalToday, ...
            Efinal, ...
            dt, ...
            eta, ...
            Emin, ...
            Emax, ...
            Wmax);


        executedPlan(kd,blockSlots) = ...
            currentPlan(blockSlots)';


        actualCharge(kd,blockSlots) = ...
            A.Wch';


        actualDischarge(kd,blockSlots) = ...
            A.Wdis';


        actualEmergency(kd,blockSlots) = ...
            A.Wem';


        actualSurplus(kd,blockSlots) = ...
            A.Wsur';


        Ecurrent = ...
            A.Eend;

    end


    SOCend(kd) = ...
        Ecurrent;


    %% ========================================================
    % 实际实时电价结算
    %% ========================================================

    inc = ...
        max( ...
        executedPlan(kd,:)' ...
        -g0, ...
        0);


    dec = ...
        max( ...
        g0 ...
        -executedPlan(kd,:)', ...
        0);


    retainedPlanCostDay(kd) = ...
        sum( ...
        actualPriceDay ...
        .*min( ...
        g0, ...
        executedPlan(kd,:)'));


    increaseCostDay(kd) = ...
        1.5 ...
        *sum( ...
        actualPriceDay ...
        .*inc);


    decreasePenaltyDay(kd) = ...
        0.5 ...
        *sum( ...
        actualPriceDay ...
        .*dec);


    emergencyCostDay(kd) = ...
        5 ...
        *sum( ...
        actualPriceDay ...
        .*actualEmergency(kd,:)');


    increaseEnergyDay(kd) = ...
        sum(inc);


    decreaseEnergyDay(kd) = ...
        sum(dec);

end


if forceFinalSOC6000 ...
        &&abs(SOCend(end)-Efinal)>1e-5

    error( ...
        '%s最终SOC未回到6000。', ...
        strategyName);

end


if any(SOCend<Emin-1e-5) ...
        ||any(SOCend>Emax+1e-5)

    error( ...
        '%s存在SOC越界。', ...
        strategyName);

end


dailyCost = ...
    retainedPlanCostDay ...
    +increaseCostDay ...
    +decreasePenaltyDay ...
    +emergencyCostDay;


dailyTable = ...
    table( ...
    predDates, ...
    SOCstart, ...
    SOCend, ...
    retainedPlanCostDay, ...
    increaseCostDay, ...
    decreasePenaltyDay, ...
    emergencyCostDay, ...
    dailyCost, ...
    increaseEnergyDay, ...
    decreaseEnergyDay, ...
    sum(actualEmergency,2), ...
    'VariableNames',{ ...
    'Date', ...
    'SOCstart_kWh', ...
    'SOCend_kWh', ...
    'RetainedPlanCost_Yuan', ...
    'IncreaseCost_Yuan', ...
    'DecreasePenalty_Yuan', ...
    'EmergencyCost_Yuan', ...
    'TotalCost_Yuan', ...
    'IncreaseEnergy_kWh', ...
    'DecreaseEnergy_kWh', ...
    'EmergencyEnergy_kWh'} ...
    );


R.name = ...
    strategyName;


R.plan0 = ...
    plan0;


R.executedPlan = ...
    executedPlan;


R.planAfter = ...
    planAfter;


R.actualCharge = ...
    actualCharge;


R.actualDischarge = ...
    actualDischarge;


R.actualEmergency = ...
    actualEmergency;


R.actualSurplus = ...
    actualSurplus;


R.SOCstart = ...
    SOCstart;


R.SOCend = ...
    SOCend;


R.dailyCost = ...
    dailyCost;


R.dailyTable = ...
    dailyTable;


R.adjustmentTable = ...
    adjustmentTable;


R.totalRetainedPlanCost = ...
    sum(retainedPlanCostDay);


R.totalIncreaseCost = ...
    sum(increaseCostDay);


R.totalDecreasePenalty = ...
    sum(decreasePenaltyDay);


R.totalEmergencyCost = ...
    sum(emergencyCostDay);


R.totalCost = ...
    sum(dailyCost);


R.totalIncreaseEnergy = ...
    sum(increaseEnergyDay);


R.totalDecreaseEnergy = ...
    sum(decreaseEnergyDay);


R.totalEmergencyEnergy = ...
    sum( ...
    actualEmergency, ...
    'all');


R.emergencyDays = ...
    sum( ...
    any( ...
    actualEmergency>1e-8, ...
    2));


R.emergencySlots = ...
    nnz( ...
    actualEmergency>1e-8);


R.finalSOC = ...
    SOCend(end);


R.maxLPConstraintViolation = ...
    maxLPViolation;

end


%% ============================================================
% 局部函数2
% 滚动24h随机线性规划
%% ============================================================

function P = solveRolling24hLP( ...
    PloadScenario, ...
    PpvScenario, ...
    prob, ...
    price24, ...
    qCurrent, ...
    g0Remain, ...
    Estart, ...
    forceFinalToday, ...
    Efinal, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax, ...
    terminalValue, ...
    cyclePenalty, ...
    curtailPenalty, ...
    options)


[H,nScenario] = ...
    size(PloadScenario);


if H~=144 ...
        ||~isequal( ...
        size(PpvScenario), ...
        [H,nScenario])

    error( ...
        '场景必须为144×S。');

end


prob = ...
    prob(:);


prob = ...
    prob/sum(prob);


price24 = ...
    price24(:);


nextN = ...
    H-qCurrent;


isInitial = ...
    isempty(g0Remain);


iCurrent = ...
    1:qCurrent;


if isInitial

    commonN = ...
        qCurrent;


    iInc = ...
        [];


    iDec = ...
        [];

else

    iInc = ...
        qCurrent+(1:qCurrent);


    iDec = ...
        2*qCurrent+(1:qCurrent);


    commonN = ...
        3*qCurrent;


    g0Remain = ...
        g0Remain(:);

end


scenarioBlock = ...
    nextN ...
    +5*H ...
    +1;


nVar = ...
    commonN ...
    +nScenario*scenarioBlock;


f = ...
    zeros(nVar,1);


%% 当前自然日普通购电

f(iCurrent) = ...
    price24(1:qCurrent);


%% ------------------------------------------------------------
% 调整成本
%
% g = g0 + inc - dec
%
% 基础p*g
% + 0.5p*inc
% + 0.5p*dec
%
% 等价于：
%
% 增购：1.5p
%
% 减购时：
% 原实际保留部分p
% + 减少部分0.5p违约
%% ------------------------------------------------------------

if ~isInitial

    f(iInc) = ...
        0.5 ...
        *price24(1:qCurrent);


    f(iDec) = ...
        0.5 ...
        *price24(1:qCurrent);

end


lb = ...
    zeros(nVar,1);


ub = ...
    inf(nVar,1);


nDeviationEq = ...
    double(~isInitial) ...
    *qCurrent;


nEq = ...
    nDeviationEq ...
    +nScenario*(2*H+1);


Aeq = ...
    spalloc( ...
    nEq, ...
    nVar, ...
    max( ...
    1, ...
    nDeviationEq*3 ...
    +nScenario*(10*H+2)));


beq = ...
    zeros(nEq,1);


row = ...
    0;


if ~isInitial

    for t = 1:qCurrent

        row = ...
            row+1;


        Aeq(row,iCurrent(t)) = ...
            1;


        Aeq(row,iInc(t)) = ...
            -1;


        Aeq(row,iDec(t)) = ...
            1;


        beq(row) = ...
            g0Remain(t);

    end


    ub(iDec) = ...
        g0Remain;

end


for s = 1:nScenario

    base = ...
        commonN ...
        +(s-1)*scenarioBlock;


    iNext = ...
        base+(1:nextN);


    iCh = ...
        base+nextN+(1:H);


    iDis = ...
        base+nextN+H+(1:H);


    iSur = ...
        base+nextN+2*H+(1:H);


    iEm = ...
        base+nextN+3*H+(1:H);


    iE = ...
        base+nextN+4*H+(1:H+1);


    if nextN>0

        f(iNext) = ...
            prob(s) ...
            *price24(qCurrent+1:end);

    end


    f(iEm) = ...
        prob(s) ...
        *5 ...
        *price24;


    f(iCh) = ...
        prob(s) ...
        *cyclePenalty;


    f(iDis) = ...
        prob(s) ...
        *cyclePenalty;


    f(iSur) = ...
        prob(s) ...
        *curtailPenalty;


    f(iE(end)) = ...
        f(iE(end)) ...
        -prob(s)*terminalValue;


    ub(iCh) = ...
        Wmax;


    ub(iDis) = ...
        Wmax;


    lb(iE) = ...
        Emin;


    ub(iE) = ...
        Emax;


    if forceFinalToday

        midnightState = ...
            iE(qCurrent+1);


        lb(midnightState) = ...
            Efinal;


        ub(midnightState) = ...
            Efinal;

    end


    Wload = ...
        PloadScenario(:,s)*dt;


    Wpv = ...
        PpvScenario(:,s)*dt;


    for t = 1:H

        row = ...
            row+1;


        if t<=qCurrent

            iGrid = ...
                iCurrent(t);

        else

            iGrid = ...
                iNext(t-qCurrent);

        end


        Aeq(row,iGrid) = ...
            1;


        Aeq(row,iDis(t)) = ...
            1;


        Aeq(row,iEm(t)) = ...
            1;


        Aeq(row,iCh(t)) = ...
            -1;


        Aeq(row,iSur(t)) = ...
            -1;


        beq(row) = ...
            Wload(t) ...
            -Wpv(t);

    end


    for t = 1:H

        row = ...
            row+1;


        Aeq(row,iE(t)) = ...
            -1;


        Aeq(row,iE(t+1)) = ...
            1;


        Aeq(row,iCh(t)) = ...
            -eta;


        Aeq(row,iDis(t)) = ...
            1/eta;

    end


    row = ...
        row+1;


    Aeq(row,iE(1)) = ...
        1;


    beq(row) = ...
        Estart;

end


[x,fval,exitflag,output] = ...
    linprog( ...
    f, ...
    [], ...
    [], ...
    Aeq, ...
    beq, ...
    lb, ...
    ub, ...
    options);


if exitflag<=0

    error( ...
        '滚动LP失败：%s', ...
        output.message);

end


eqViolation = ...
    max( ...
    abs( ...
    Aeq*x-beq));


boundViolation = ...
    max( ...
    [ ...
    max(lb-x), ...
    max(x-ub), ...
    0 ...
    ]);


maxViolation = ...
    max( ...
    eqViolation, ...
    boundViolation);


P.currentGrid = ...
    x(iCurrent);


P.objective = ...
    fval;


P.exitflag = ...
    exitflag;


P.maxConstraintViolation = ...
    maxViolation;

end


%% ============================================================
% 局部函数3
% 实际6h严格因果执行
%% ============================================================

function A = replayActualBlock( ...
    Pload, ...
    Ppv, ...
    Wgrid, ...
    Estart, ...
    globalSlots, ...
    forceFinalToday, ...
    Efinal, ...
    dt, ...
    eta, ...
    Emin, ...
    Emax, ...
    Wmax)


Wload = ...
    Pload(:)*dt;


Wpv = ...
    Ppv(:)*dt;


Wgrid = ...
    Wgrid(:);


N = ...
    length(Wgrid);


Wch = ...
    zeros(N,1);


Wdis = ...
    zeros(N,1);


Wem = ...
    zeros(N,1);


Wsur = ...
    zeros(N,1);


E = ...
    Estart;


for j = 1:N

    tGlobal = ...
        globalSlots(j);


    if forceFinalToday

        remainingSlots = ...
            144-tGlobal;


        nextLow = ...
            max( ...
            Emin, ...
            Efinal ...
            -remainingSlots*eta*Wmax);


        nextHigh = ...
            min( ...
            Emax, ...
            Efinal ...
            +remainingSlots*Wmax/eta);

    else

        nextLow = ...
            Emin;


        nextHigh = ...
            Emax;

    end


    balance = ...
        Wpv(j) ...
        +Wgrid(j) ...
        -Wload(j);


    ch = ...
        0;


    dis = ...
        0;


    em = ...
        0;


    surplus = ...
        0;


    if balance>=0

        if E>nextHigh

            dis = ...
                min( ...
                Wmax, ...
                (E-nextHigh)*eta);


            Enew = ...
                E ...
                -dis/eta;


            surplus = ...
                balance ...
                +dis;

        else

            ch = ...
                min( ...
                [ ...
                balance, ...
                Wmax, ...
                max( ...
                (nextHigh-E)/eta, ...
                0) ...
                ]);


            Enew = ...
                E ...
                +eta*ch;


            surplus = ...
                balance ...
                -ch;


            if Enew<nextLow-1e-9

                extraCh = ...
                    min( ...
                    (nextLow-Enew)/eta, ...
                    Wmax-ch);


                ch = ...
                    ch ...
                    +extraCh;


                em = ...
                    extraCh;


                Enew = ...
                    E ...
                    +eta*ch;

            end

        end

    else

        deficit = ...
            -balance;


        if E<=nextLow

            ch = ...
                min( ...
                max( ...
                (nextLow-E)/eta, ...
                0), ...
                Wmax);


            em = ...
                deficit ...
                +ch;


            Enew = ...
                E ...
                +eta*ch;

        else

            dis = ...
                min( ...
                [ ...
                deficit, ...
                Wmax, ...
                (E-nextLow)*eta ...
                ]);


            em = ...
                deficit ...
                -dis;


            Enew = ...
                E ...
                -dis/eta;


            if Enew>nextHigh+1e-9

                extraDis = ...
                    min( ...
                    (Enew-nextHigh)*eta, ...
                    Wmax-dis);


                dis = ...
                    dis ...
                    +extraDis;


                surplus = ...
                    extraDis;


                Enew = ...
                    E ...
                    -dis/eta;

            end

        end

    end


    if Enew<nextLow-1e-5 ...
            || Enew>nextHigh+1e-5

        error( ...
            '实际回放SOC不可达。');

    end


    E = ...
        min( ...
        max( ...
        Enew, ...
        Emin), ...
        Emax);


    Wch(j) = ...
        ch;


    Wdis(j) = ...
        dis;


    Wem(j) = ...
        em;


    Wsur(j) = ...
        surplus;

end


A.Wch = ...
    Wch;


A.Wdis = ...
    Wdis;


A.Wem = ...
    Wem;


A.Wsur = ...
    Wsur;


A.Eend = ...
    E;

end


%% ============================================================
% 局部函数4
% 光伏融合标定库
%% ============================================================

function L = buildPVBlendCalibrationLibrary( ...
    F, ...
    pvAll, ...
    dateAll)


nRec = ...
    length(F.dates);


formal = ...
    nan(nRec,144);


history = ...
    nan(nRec,144);


actual = ...
    nan(nRec,144);


complete = ...
    false(nRec,1);


for i = 1:nRec

    d = ...
        find( ...
        dateAll==F.dates(i), ...
        1);


    if isempty(d) ...
            ||d<=3

        continue;

    end


    hIssue = ...
        F.issueHour(i);


    actual24 = ...
        extractActual24( ...
        pvAll, ...
        d, ...
        hIssue);


    if isempty(actual24)

        continue;

    end


    formal24 = ...
        makeFormalPV24( ...
        F, ...
        pvAll, ...
        dateAll, ...
        d, ...
        hIssue);


    history24 = ...
        makeHistoryPV24( ...
        pvAll, ...
        d, ...
        hIssue);


    formal(i,:) = ...
        formal24';


    history(i,:) = ...
        history24';


    actual(i,:) = ...
        actual24';


    complete(i) = ...
        all(isfinite(formal(i,:))) ...
        &&all(isfinite(history(i,:))) ...
        &&all(isfinite(actual(i,:)));

end


L.date = ...
    F.dates;


L.issueHour = ...
    F.issueHour;


L.issueTime = ...
    F.issueTime;


L.formal = ...
    formal;


L.history = ...
    history;


L.actual = ...
    actual;


L.complete = ...
    complete;

end


%% ============================================================
% 局部函数5
% 动态融合权重
%% ============================================================

function [w,nHistory] = getRollingPVBlendWeight( ...
    L, ...
    issueHour, ...
    currentTime, ...
    windowN, ...
    minHistory)


valid = ...
    L.complete ...
    &L.issueHour==issueHour ...
    &( ...
    L.issueTime+hours(24) ...
    <=currentTime);


rows = ...
    find(valid);


if isempty(rows)

    w = ...
        1;


    nHistory = ...
        0;


    return;

end


[~,ord] = ...
    sort( ...
    L.issueTime(rows));


rows = ...
    rows(ord);


firstKeep = ...
    max( ...
    1, ...
    length(rows)-windowN+1);


rows = ...
    rows(firstKeep:end);


nHistory = ...
    length(rows);


if nHistory<minHistory

    w = ...
        1;


    return;

end


formal = ...
    L.formal(rows,:);


history = ...
    L.history(rows,:);


actual = ...
    L.actual(rows,:);


formal = ...
    formal(:);


history = ...
    history(:);


actual = ...
    actual(:);


good = ...
    isfinite(formal) ...
    &isfinite(history) ...
    &isfinite(actual);


formal = ...
    formal(good);


history = ...
    history(good);


actual = ...
    actual(good);


den = ...
    sum( ...
    (formal-history).^2);


if isempty(actual) ...
        ||den<1e-12

    w = ...
        1;


    return;

end


w = ...
    sum( ...
    (actual-history) ...
    .*(formal-history)) ...
    /den;


w = ...
    min( ...
    max(w,0), ...
    1);

end


%% ============================================================
% 局部函数6
% 联合残差库
%% ============================================================

function Rlib = buildJointResidualLibraryDynamic( ...
    F, ...
    loadAll, ...
    pvAll, ...
    loadPredToday, ...
    loadPredNext, ...
    dateAll, ...
    PVlib, ...
    blendWindow, ...
    blendMinHistory, ...
    useBlend)


nRec = ...
    length(F.dates);


eLoad = ...
    nan(nRec,144);


ePV = ...
    nan(nRec,144);


blendWeight = ...
    nan(nRec,1);


complete = ...
    false(nRec,1);


for i = 1:nRec

    d = ...
        find( ...
        dateAll==F.dates(i), ...
        1);


    if isempty(d) ...
            ||d<16

        continue;

    end


    if any(~isfinite(loadPredToday(d,:))) ...
            ||any(~isfinite(loadPredNext(d,:)))

        continue;

    end


    hIssue = ...
        F.issueHour(i);


    actualLoad24 = ...
        extractActual24( ...
        loadAll, ...
        d, ...
        hIssue);


    actualPV24 = ...
        extractActual24( ...
        pvAll, ...
        d, ...
        hIssue);


    if isempty(actualLoad24) ...
            ||isempty(actualPV24)

        continue;

    end


    baseLoad24 = ...
        makeLoadForecast24( ...
        loadPredToday, ...
        loadPredNext, ...
        d, ...
        hIssue);


    if useBlend

        [wHist,~] = ...
            getRollingPVBlendWeight( ...
            PVlib, ...
            hIssue, ...
            F.issueTime(i), ...
            blendWindow, ...
            blendMinHistory);

    else

        wHist = ...
            1;

    end


    blendWeight(i) = ...
        wHist;


    basePV24 = ...
        makeOfficialPV24Blend( ...
        F, ...
        pvAll, ...
        dateAll, ...
        d, ...
        hIssue, ...
        wHist);


    eLoad(i,:) = ...
        ( ...
        actualLoad24 ...
        -baseLoad24 ...
        )';


    ePV(i,:) = ...
        ( ...
        actualPV24 ...
        -basePV24 ...
        )';


    complete(i) = ...
        all(isfinite(eLoad(i,:))) ...
        &&all(isfinite(ePV(i,:)));

end


Rlib.date = ...
    F.dates;


Rlib.issueHour = ...
    F.issueHour;


Rlib.issueTime = ...
    F.issueTime;


Rlib.eLoad = ...
    eLoad;


Rlib.ePV = ...
    ePV;


Rlib.blendWeight = ...
    blendWeight;


Rlib.complete = ...
    complete;

end


%% ============================================================
% 局部函数7
% 联合残差K-means情景
%% ============================================================

function S = getJointScenarioCenters( ...
    Rlib, ...
    issueHour, ...
    currentTime, ...
    poolDays, ...
    Kscenario, ...
    seed)


valid = ...
    Rlib.complete ...
    &Rlib.issueHour==issueHour ...
    &( ...
    Rlib.issueTime+hours(24) ...
    <=currentTime);


rows = ...
    find(valid);


if isempty(rows)

    S.loadCenter = ...
        zeros(144,1);


    S.pvCenter = ...
        zeros(144,1);


    S.prob = ...
        1;


    S.nHistory = ...
        0;


    return;

end


[~,ord] = ...
    sort( ...
    Rlib.issueTime(rows));


rows = ...
    rows(ord);


firstKeep = ...
    max( ...
    1, ...
    length(rows)-poolDays+1);


rows = ...
    rows(firstKeep:end);


EL = ...
    Rlib.eLoad(rows,:);


EP = ...
    Rlib.ePV(rows,:);


nHistory = ...
    size(EL,1);


K = ...
    min( ...
    Kscenario, ...
    nHistory);


if K==1

    centerL = ...
        mean( ...
        EL, ...
        1);


    centerP = ...
        mean( ...
        EP, ...
        1);


    prob = ...
        1;

else

    scaleL = ...
        max( ...
        std( ...
        EL, ...
        0, ...
        'all'), ...
        1);


    scaleP = ...
        max( ...
        std( ...
        EP, ...
        0, ...
        'all'), ...
        1);


    Z = ...
        [ ...
        EL/scaleL, ...
        EP/scaleP ...
        ];


    rng( ...
        seed, ...
        'twister');


    clusterID = ...
        kmeans( ...
        Z, ...
        K, ...
        'Distance','sqeuclidean', ...
        'Replicates',10, ...
        'MaxIter',300, ...
        'EmptyAction','singleton');


    centerL = ...
        zeros(K,144);


    centerP = ...
        zeros(K,144);


    prob = ...
        zeros(K,1);


    for k = 1:K

        hit = ...
            clusterID==k;


        centerL(k,:) = ...
            mean( ...
            EL(hit,:), ...
            1);


        centerP(k,:) = ...
            mean( ...
            EP(hit,:), ...
            1);


        prob(k) = ...
            mean(hit);

    end


    netResidualMean = ...
        mean( ...
        centerL-centerP, ...
        2);


    [~,sortID] = ...
        sort(netResidualMean);


    centerL = ...
        centerL(sortID,:);


    centerP = ...
        centerP(sortID,:);


    prob = ...
        prob(sortID);

end


S.loadCenter = ...
    centerL';


S.pvCenter = ...
    centerP';


S.prob = ...
    prob(:)/sum(prob);


S.nHistory = ...
    nHistory;

end


%% ============================================================
% 局部函数8
% 正式光伏24h预测
%% ============================================================

function formal24 = makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour)


date0 = ...
    dateAll(d);


id = ...
    find( ...
    F.dates==date0 ...
    &F.issueHour==issueHour, ...
    1);


if isempty(id)

    error( ...
        '找不到%s %02d时正式光伏预报。', ...
        string(date0), ...
        issueHour);

end


anchor = ...
    observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour);


xSlot = ...
    0:6:144;


querySlot = ...
    1:144;


formal24 = ...
    interp1( ...
    xSlot, ...
    [ ...
    anchor, ...
    F.forecast(id,:) ...
    ], ...
    querySlot, ...
    'linear')';


formal24 = ...
    max( ...
    formal24, ...
    0);

end


%% ============================================================
% 局部函数9
% 动态融合光伏预测
%% ============================================================

function pv24 = makeOfficialPV24Blend( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    w)


formal24 = ...
    makeFormalPV24( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    issueHour);


history24 = ...
    makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour);


pv24 = ...
    w*formal24 ...
    +(1-w)*history24;


pv24 = ...
    max( ...
    pv24, ...
    0);

end


%% ============================================================
% 局部函数10
% 前3条同发布时间历史光伏路径
%% ============================================================

function history24 = makeHistoryPV24( ...
    pvAll, ...
    d, ...
    issueHour)


paths = ...
    zeros(144,3);


for k = 1:3

    histDay = ...
        d-k;


    onePath = ...
        extractActual24( ...
        pvAll, ...
        histDay, ...
        issueHour);


    if isempty(onePath)

        error( ...
            '历史光伏路径不足。');

    end


    paths(:,k) = ...
        onePath;

end


history24 = ...
    mean( ...
    paths, ...
    2);

end


%% ============================================================
% 局部函数11
% 未来24h负载预测
%% ============================================================

function load24 = makeLoadForecast24( ...
    predToday, ...
    predNext, ...
    d, ...
    issueHour)


startSlot = ...
    issueHour*6+1;


load24 = ...
    [ ...
    predToday( ...
    d, ...
    startSlot:end), ...
    predNext( ...
    d, ...
    1:startSlot-1) ...
    ]';

end


%% ============================================================
% 局部函数12
% 冻结0时光伏48h
%% ============================================================

function frozen48 = buildFrozenPV48( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    w0)


today = ...
    makeOfficialPV24Blend( ...
    F, ...
    pvAll, ...
    dateAll, ...
    d, ...
    0, ...
    w0);


historyNext = ...
    mean( ...
    pvAll( ...
    d-(1:3), ...
    :), ...
    1)';


frozen48 = ...
    max( ...
    [ ...
    today; ...
    historyNext ...
    ], ...
    0);

end


%% ============================================================
% 局部函数13
% 当前发布时间真实光伏锚点
%% ============================================================

function value = observedPVAtIssue( ...
    pvAll, ...
    d, ...
    issueHour)


if issueHour==0

    if d<=1

        error( ...
            '第1天无法取得前一天0时锚点。');

    end


    value = ...
        pvAll(d-1,144);

else

    issueCol = ...
        issueHour*6;


    value = ...
        pvAll(d,issueCol);

end

end


%% ============================================================
% 局部函数14
% 提取发布时间后连续24h实际路径
%% ============================================================

function path = extractActual24( ...
    data, ...
    d, ...
    issueHour)


startSlot = ...
    issueHour*6+1;


if issueHour==0

    path = ...
        data(d,:)';


elseif d<size(data,1)

    todayPart = ...
        data( ...
        d, ...
        startSlot:end);


    nextPart = ...
        data( ...
        d+1, ...
        1:startSlot-1);


    path = ...
        [ ...
        todayPart, ...
        nextPart ...
        ]';

else

    path = ...
        [];

end

end


%% ============================================================
% 局部函数15
% AS-Ridge负载
%% ============================================================

function [predToday,predNext] = buildCausalLoadASRidge( ...
    loadAll, ...
    dateAll, ...
    tau, ...
    lambda, ...
    maxIter, ...
    tol, ...
    windowDays)


[nDay,nTime] = ...
    size(loadAll);


predToday = ...
    nan(nDay,nTime);


predNext = ...
    nan(nDay,nTime);


slot = ...
    (0:nTime-1)';


sinDay = ...
    sin( ...
    2*pi*slot/nTime);


cosDay = ...
    cos( ...
    2*pi*slot/nTime);


for d = 16:nDay

    firstDay = ...
        max( ...
        15, ...
        d-windowDays);


    trainDays = ...
        firstDay:(d-1);


    X = ...
        zeros( ...
        length(trainDays)*nTime, ...
        7);


    y = ...
        zeros( ...
        length(trainDays)*nTime, ...
        1);


    r0 = ...
        1;


    for j = trainDays

        rr = ...
            r0:(r0+nTime-1);


        wd = ...
            weekday(dateAll(j));


        X(rr,:) = ...
            [ ...
            loadAll(j-1,:)', ...
            loadAll(j-7,:)', ...
            loadAll(j-14,:)', ...
            sinDay, ...
            cosDay, ...
            repmat( ...
            sin(2*pi*(wd-1)/7), ...
            nTime,1), ...
            repmat( ...
            cos(2*pi*(wd-1)/7), ...
            nTime,1) ...
            ];


        y(rr) = ...
            loadAll(j,:)';


        r0 = ...
            r0+nTime;

    end


    wdToday = ...
        weekday(dateAll(d));


    Xtoday = ...
        [ ...
        loadAll(d-1,:)', ...
        loadAll(d-7,:)', ...
        loadAll(d-14,:)', ...
        sinDay, ...
        cosDay, ...
        repmat( ...
        sin(2*pi*(wdToday-1)/7), ...
        nTime,1), ...
        repmat( ...
        cos(2*pi*(wdToday-1)/7), ...
        nTime,1) ...
        ];


    yToday = ...
        fitASRidgeLocal( ...
        X, ...
        y, ...
        Xtoday, ...
        tau, ...
        lambda, ...
        maxIter, ...
        tol);


    wdNext = ...
        weekday( ...
        dateAll(d) ...
        +days(1));


    Xnext = ...
        [ ...
        yToday, ...
        loadAll(d+1-7,:)', ...
        loadAll(d+1-14,:)', ...
        sinDay, ...
        cosDay, ...
        repmat( ...
        sin(2*pi*(wdNext-1)/7), ...
        nTime,1), ...
        repmat( ...
        cos(2*pi*(wdNext-1)/7), ...
        nTime,1) ...
        ];


    yNext = ...
        fitASRidgeLocal( ...
        X, ...
        y, ...
        Xnext, ...
        tau, ...
        lambda, ...
        maxIter, ...
        tol);


    predToday(d,:) = ...
        max( ...
        yToday, ...
        0)';


    predNext(d,:) = ...
        max( ...
        yNext, ...
        0)';

end

end


%% ============================================================
% 局部函数16
% AS-Ridge拟合
%% ============================================================

function yPred = fitASRidgeLocal( ...
    Xtrain, ...
    Ytrain, ...
    Xtest, ...
    tau, ...
    lambda, ...
    maxIter, ...
    tol)


muX = ...
    mean( ...
    Xtrain, ...
    1);


sdX = ...
    std( ...
    Xtrain, ...
    0, ...
    1);


sdX( ...
    sdX<1e-10 ...
    |~isfinite(sdX)) = ...
    1;


Xtr = ...
    (Xtrain-muX) ...
    ./sdX;


Xte = ...
    (Xtest-muX) ...
    ./sdX;


muY = ...
    mean(Ytrain);


sdY = ...
    std(Ytrain);


if sdY<1e-10 ...
        ||~isfinite(sdY)

    sdY = ...
        1;

end


y = ...
    (Ytrain-muY) ...
    /sdY;


X1 = ...
    [ ...
    ones(size(Xtr,1),1), ...
    Xtr ...
    ];


Xt = ...
    [ ...
    ones(size(Xte,1),1), ...
    Xte ...
    ];


R = ...
    eye(size(X1,2));


R(1,1) = ...
    0;


beta = ...
    ( ...
    X1'*X1 ...
    +lambda*R ...
    ) ...
    \(X1'*y);


for iter = 1:maxIter

    e = ...
        y ...
        -X1*beta;


    w = ...
        (1-tau) ...
        *ones(size(e));


    w(e>=0) = ...
        tau;


    w = ...
        max( ...
        w, ...
        1e-6);


    Xw = ...
        X1 ...
        .*sqrt(w);


    yw = ...
        y ...
        .*sqrt(w);


    betaNew = ...
        ( ...
        Xw'*Xw ...
        +lambda*R ...
        ) ...
        \(Xw'*yw);


    change = ...
        norm( ...
        betaNew-beta) ...
        /max( ...
        norm(beta), ...
        1e-8);


    beta = ...
        betaNew;


    if change<tol

        break;

    end

end


yPred = ...
    (Xt*beta) ...
    *sdY ...
    +muY;


yPred = ...
    yPred(:);

end


%% ============================================================
% 局部函数17
% 读取附件3
%% ============================================================

function F = readForecastSingleSheet( ...
    filename, ...
    sheetName)


C = ...
    readcell( ...
    filename, ...
    'Sheet',sheetName);


[nRow,nCol] = ...
    size(C);


headerRow = ...
    NaN;


for r = 1:min(nRow,30)

    for c = 1:nCol

        txt = ...
            replace( ...
            strtrim( ...
            string(C{r,c})), ...
            " ", ...
            "");


        if txt=="预报1小时" ...
                ||txt=="预测1小时"

            headerRow = ...
                r;

            break;

        end

    end


    if ~isnan(headerRow)

        break;

    end

end


if isnan(headerRow)

    error( ...
        '附件3找不到预报表头。');

end


dateCol = ...
    NaN;


issueCol = ...
    NaN;


for c = 1:nCol

    txt = ...
        replace( ...
        strtrim( ...
        string(C{headerRow,c})), ...
        " ", ...
        "");


    if contains(txt,"日期")

        dateCol = ...
            c;

    end


    if contains(txt,"预报时刻") ...
            ||contains(txt,"预测时刻")

        issueCol = ...
            c;

    end

end


forecastCols = ...
    nan(1,24);


for h = 1:24

    for c = 1:nCol

        txt = ...
            replace( ...
            strtrim( ...
            string(C{headerRow,c})), ...
            " ", ...
            "");


        if txt==sprintf( ...
                '预报%d小时',h) ...
                ||txt==sprintf( ...
                '预测%d小时',h)

            forecastCols(h) = ...
                c;

            break;

        end

    end


    if isnan(forecastCols(h))

        error( ...
            '缺少预报%d小时列。', ...
            h);

    end

end


maxN = ...
    nRow-headerRow;


dates = ...
    NaT(maxN,1);


issueHour = ...
    nan(maxN,1);


forecast = ...
    nan(maxN,24);


count = ...
    0;


currentDate = ...
    NaT;


for r = headerRow+1:nRow

    newDate = ...
        parseOneDate( ...
        C{r,dateCol});


    if ~isnat(newDate)

        currentDate = ...
            dateshift( ...
            newDate, ...
            'start','day');

    end


    if isnat(currentDate)

        continue;

    end


    hIssue = ...
        parseIssueHour( ...
        C{r,issueCol});


    if isnan(hIssue) ...
            ||~ismember( ...
            hIssue, ...
            [0,6,12,18])

        continue;

    end


    vals = ...
        nan(1,24);


    for h = 1:24

        vals(h) = ...
            valueToDouble( ...
            C{r,forecastCols(h)});

    end


    if all(isnan(vals))

        continue;

    end


    count = ...
        count+1;


    dates(count) = ...
        currentDate;


    issueHour(count) = ...
        hIssue;


    forecast(count,:) = ...
        vals;

end


dates = ...
    dates(1:count);


issueHour = ...
    issueHour(1:count);


forecast = ...
    forecast(1:count,:);


T = ...
    table( ...
    dates, ...
    issueHour, ...
    (1:count)', ...
    'VariableNames',{ ...
    'Date', ...
    'Hour', ...
    'ID'} ...
    );


T = ...
    sortrows( ...
    T, ...
    {'Date','Hour'} ...
    );


id = ...
    T.ID;


F.dates = ...
    dates(id);


F.issueHour = ...
    issueHour(id);


F.forecast = ...
    forecast(id,:);


F.issueTime = ...
    F.dates ...
    +hours(F.issueHour);

end


%% ============================================================
% 局部函数18
% 日期解析
%% ============================================================

function d = parseOneDate(x)


d = ...
    NaT;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isdatetime(x)

    if ~isnat(x)

        d = ...
            x(1);

    end


    return;

end


if isnumeric(x)

    if isempty(x) ...
            ||isnan(x)

        return;

    end


    try

        d = ...
            datetime( ...
            x, ...
            'ConvertFrom','excel');


        return;

    catch

    end

end


s = ...
    strtrim(string(x));


if ismissing(s) ...
        ||strlength(s)==0

    return;

end


try

    d = ...
        datetime(s);

catch

    d = ...
        NaT;

end

end


%% ============================================================
% 局部函数19
% 发布时间解析
%% ============================================================

function h = parseIssueHour(x)


h = ...
    NaN;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isduration(x)

    h = ...
        mod( ...
        round(hours(x)), ...
        24);


    return;

end


if isdatetime(x)

    if ~isnat(x)

        h = ...
            hour(x);

    end


    return;

end


if isnumeric(x)

    if isempty(x) ...
            ||isnan(x)

        return;

    end


    if x>=0 ...
            &&x<1

        h = ...
            mod( ...
            round(24*x), ...
            24);


        return;

    end


    if x>=0 ...
            &&x<=24

        h = ...
            round(x);


        if h==24

            h = ...
                0;

        end


        return;

    end

end


s = ...
    strtrim(string(x));


token = ...
    regexp( ...
    char(s), ...
    '(\d{1,2})\s*:', ...
    'tokens','once');


if ~isempty(token)

    h = ...
        mod( ...
        str2double(token{1}), ...
        24);

end

end


%% ============================================================
% 局部函数20
% 单元格转数值
%% ============================================================

function y = valueToDouble(x)


y = ...
    NaN;


if iscell(x)

    if isempty(x)

        return;

    end


    x = ...
        x{1};

end


if isnumeric(x)

    if ~isempty(x)

        y = ...
            double(x(1));

    end


    return;

end


if islogical(x)

    y = ...
        double(x);


    return;

end


s = ...
    strtrim(string(x));


if ismissing(s) ...
        ||strlength(s)==0

    return;

end


y = ...
    str2double(s);

end


%% ============================================================
% 局部函数21
% 建立0/6/12/18滚动实时电价预测
%% ============================================================

function [ ...
    priceCache, ...
    diagTable, ...
    zeroHourMAE, ...
    blockMAE ...
    ] = ...
    buildRollingPriceForecastCache( ...
    priceAll, ...
    dateAll, ...
    targetDays, ...
    issueHours, ...
    kL, ...
    kS, ...
    useRollingUpdate)


nDay = ...
    length(targetDays);


priceCache = ...
    cell(nDay,4);


blockError = ...
    nan(nDay,4);


zeroPred = ...
    nan(nDay,144);


for kd = 1:nDay

    d = ...
        targetDays(kd);


    for ki = 1:4

        hIssue = ...
            issueHours(ki);


        p24 = ...
            makeRollingPrice24( ...
            priceAll, ...
            dateAll, ...
            d, ...
            hIssue, ...
            kL, ...
            kS, ...
            useRollingUpdate);


        priceCache{kd,ki} = ...
            p24(:);


        startSlot = ...
            hIssue*6+1;


        endSlot = ...
            min( ...
            startSlot+35, ...
            144);


        nExec = ...
            endSlot-startSlot+1;


        realBlock = ...
            priceAll( ...
            d, ...
            startSlot:endSlot)';


        predBlock = ...
            p24(1:nExec);


        blockError(kd,ki) = ...
            mean( ...
            abs( ...
            predBlock ...
            -realBlock));


        if ki==1

            zeroPred(kd,:) = ...
                p24';

        end

    end

end


actualZero = ...
    priceAll( ...
    targetDays, ...
    :);


zeroHourMAE = ...
    mean( ...
    abs( ...
    zeroPred ...
    -actualZero), ...
    'all');


blockMAE = ...
    mean( ...
    blockError, ...
    1, ...
    'omitnan');


diagTable = ...
    table( ...
    dateAll(targetDays), ...
    blockError(:,1), ...
    blockError(:,2), ...
    blockError(:,3), ...
    blockError(:,4), ...
    'VariableNames',{ ...
    'Date', ...
    'MAE_0to6', ...
    'MAE_6to12', ...
    'MAE_12to18', ...
    'MAE_18to24'} ...
    );

end


%% ============================================================
% 局部函数22
% 某发布时间预测未来24h实时电价
%% ============================================================

function price24 = makeRollingPrice24( ...
    priceAll, ...
    dateAll, ...
    d, ...
    issueHour, ...
    kL, ...
    kS, ...
    useRollingUpdate)


%% ------------------------------------------------------------
% 当天0时基础预测
%% ------------------------------------------------------------

[ ...
    todayBase, ...
    todayShape, ...
    ~ ...
    ] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    dateAll(d), ...
    d-1, ...
    kL, ...
    kS);


todayForecast = ...
    todayBase;


%% ------------------------------------------------------------
% 6/12/18时：
%
% 使用已经发生的真实价格重新估计
% “当天价格水平”
%% ------------------------------------------------------------

if useRollingUpdate ...
        &&issueHour>0

    obsN = ...
        issueHour*6;


    observedPrice = ...
        priceAll( ...
        d, ...
        1:obsN)';


    observedShape = ...
        todayShape( ...
        1:obsN)';


    denom = ...
        sum( ...
        observedShape.^2);


    if denom>1e-12

        updatedLevel = ...
            sum( ...
            observedShape ...
            .*observedPrice) ...
            /denom;


        if isfinite(updatedLevel) ...
                &&updatedLevel>=0

            todayForecast = ...
                updatedLevel ...
                .*todayShape;

        end

    end

end


todayForecast = ...
    max( ...
    todayForecast, ...
    0);


%% ------------------------------------------------------------
% 次日价格：
%
% 当前日未完整结束，
% 因此只能使用截至前一天的完整历史数据
%% ------------------------------------------------------------

nextDate = ...
    dateAll(d) ...
    +days(1);


[nextForecast,~,~] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    nextDate, ...
    d-1, ...
    kL, ...
    kS);


%% ------------------------------------------------------------
% 拼成发布时间后的连续24小时
%% ------------------------------------------------------------

startSlot = ...
    issueHour*6+1;


price24 = ...
    [ ...
    todayForecast( ...
    startSlot:end), ...
    nextForecast( ...
    1:startSlot-1) ...
    ]';


if length(price24)~=144

    error( ...
        '滚动实时电价预测不是144点。');

end

end


%% ============================================================
% 局部函数23
% 基础电价预测：
%
% 日均价 × 日内相对形状
%% ============================================================

function [ ...
    forecastDay, ...
    shapeDay, ...
    levelDay ...
    ] = ...
    makeBaseCalendarPriceForecast( ...
    priceAll, ...
    dateAll, ...
    targetDate, ...
    lastCompleteDay, ...
    kL, ...
    kS)


histDays = ...
    (1:lastCompleteDay)';


targetWeekday = ...
    weekday(targetDate);


histWeekday = ...
    weekday( ...
    dateAll(histDays));


sameWeekDays = ...
    histDays( ...
    histWeekday==targetWeekday);


if length(sameWeekDays)<max(kL,kS)

    error( ...
        '实时电价同星期历史数据不足。');

end


%% 日均价水平

meanDays = ...
    sameWeekDays( ...
    end-kL+1:end);


historicalDailyMean = ...
    mean( ...
    priceAll(meanDays,:), ...
    2);


levelDay = ...
    mean(historicalDailyMean);


%% 日内相对形状

shapeDays = ...
    sameWeekDays( ...
    end-kS+1:end);


shapeMatrix = ...
    zeros(kS,144);


for k = 1:kS

    onePrice = ...
        priceAll( ...
        shapeDays(k), ...
        :);


    oneMean = ...
        mean(onePrice);


    if abs(oneMean)<1e-12

        error( ...
            '历史日均电价接近0。');

    end


    shapeMatrix(k,:) = ...
        onePrice ...
        /oneMean;

end


shapeDay = ...
    mean( ...
    shapeMatrix, ...
    1);


forecastDay = ...
    levelDay ...
    .*shapeDay;


forecastDay = ...
    max( ...
    forecastDay, ...
    0);

end


%% ============================================================
% 局部函数24
% 紧急购电连续时段转文字
%
% ★正确TIMEFIX：
%
% slot1 = 00:00-00:10
%
% 因此：
%
% start = 10*(s-1)
% end   = 10*e
%% ============================================================

function txt = makeEmergencyTimeRangeQ43(s,e)


startMinute = ...
    10*(s-1);


endMinute = ...
    10*e;


txt = ...
    sprintf( ...
    '%s-%s', ...
    formatResultTimeQ43(startMinute), ...
    formatResultTimeQ43(endMinute));

end


%% ============================================================
% 局部函数25
% 分钟转时间文字
%% ============================================================

function txt = formatResultTimeQ43(totalMinute)


dayAdd = ...
    floor(totalMinute/1440);


minuteOfDay = ...
    mod(totalMinute,1440);


hh = ...
    floor(minuteOfDay/60);


mm = ...
    mod(minuteOfDay,60);


if dayAdd==0

    txt = ...
        sprintf( ...
        '%d:%02d', ...
        hh, ...
        mm);

else

    txt = ...
        sprintf( ...
        '%d:%02d+1', ...
        hh, ...
        mm);

end

end